/** Auto-generated by scripts/build-lectionary-readings.mjs — do not edit by hand. */
import type { DayReadings } from './types';

export const aprilReadings: DayReadings[] = [
  {
    gregorianMonth: 4,
    gregorianDay: 1,
    gregorianDate: "Apr 1",
    ethiopianDate: "7/22",
    morning: ["Job 25","Act 21 : 17-40","Jhn 11"],
    qidase: {
      epistle: "Heb 11 : 32 - f",
      catholicEpistle: "2Pt 1 : 19 - f",
      acts: "Act 7 : 51 - 55",
      psalm: "Ps  104 : 14, 15",
      gospel: "Mat 21 : 18 - 23"
    },
    evening: ["Job            26","Act 22","Jhn 12"],
    ana: 4,
  },
  {
    gregorianMonth: 4,
    gregorianDay: 2,
    gregorianDate: "Apr 2",
    ethiopianDate: "7/23",
    morning: ["Act 23","Jhn 13","Gal  4 : 12 - 21"],
    qidase: {
      catholicEpistle: "1Pt 1 : 21 - f",
      acts: "Act 28 : 28 - f",
      psalm: "Ps 81 : 1, 2",
      gospel: "Mat 26 : 1 - 6"
    },
    evening: ["Job            28","Act 24","Jhn 14"],
    ana: 5,
  },
  {
    gregorianMonth: 4,
    gregorianDay: 3,
    gregorianDate: "Apr 3",
    ethiopianDate: "7/24",
    morning: ["Job 29","Act 25","Jhn 15"],
    qidase: {
      epistle: "2Tm 1 : 10 - f",
      catholicEpistle: "2Pt 2 : 1 - 6",
      acts: "Act 20 : 22 - 28",
      psalm: "Ps 18 : 3, 4",
      gospel: "Luk 7 : 11 - 18"
    },
    evening: ["Job            30","Act 26","Jhn 16"],
    ana: 1,
  },
  {
    gregorianMonth: 4,
    gregorianDay: 4,
    gregorianDate: "Apr 4",
    ethiopianDate: "7/25",
    morning: ["Job 31","Act 27","Jhn 17"],
    qidase: {
      epistle: "1Cr 11 : 20 - 30",
      catholicEpistle: "1Jn 3 : 18 - f",
      acts: "Act 4 : 24 - 31",
      psalm: "Ps 50 : 7, 8",
      gospel: "Mat 26 : 14 - 31"
    },
    evening: ["Job            32","Act 28","Jhn 18"],
    ana: 9,
  },
  {
    gregorianMonth: 4,
    gregorianDay: 5,
    gregorianDate: "Apr 5",
    ethiopianDate: "7/26",
    morning: ["Festal hiatus","1Pt 3 : 15 - 20","Act 10 : 30 - 40","Ps 73 : 12, 13"],
    qidase: {
      psalm: "UNCLEAR - please verify",
      gospel: "Mat 27 : 1 - 55"
    },
    evening: ["Job          33","Rom 1","Jhn 19"],
    ana: 10,
  },
  {
    gregorianMonth: 4,
    gregorianDay: 6,
    gregorianDate: "Apr 6",
    ethiopianDate: "7/27",
    morning: ["Job 34","Rom 2","Jhn 20"],
    qidase: {
      epistle: "Phl 2 : 5 - 12",
      catholicEpistle: "1Pt 1 : 1 - 10",
      acts: "Act 3 : 12 - 17",
      psalm: "Ps 104 : 9",
      gospel: "Mat 27 : 62 - f"
    },
    evening: ["Job          35","Rom 3","Jhn 21"],
    ana: 10,
  },
  {
    gregorianMonth: 4,
    gregorianDay: 7,
    gregorianDate: "Apr 7",
    ethiopianDate: "7/28",
    morning: ["Ps 2 : 6 - 7","Lk 1 : 26 - 39","Heb 1 : 1 - f"],
    qidase: {
      catholicEpistle: "1Pt 1 : 13 - 22",
      acts: "Act 17 : 13 - 30",
      psalm: "Ps  101 : 25, 26",
      gospel: "Jhn 1 : 1 - 15"
    },
    evening: ["Job  36","Rom 4","Mat 1"],
    ana: 4,
  },
  {
    gregorianMonth: 4,
    gregorianDay: 8,
    gregorianDate: "Apr 8",
    ethiopianDate: "7/29",
    morning: ["Job 37","Rom 5","Mat 2"],
    qidase: {
      epistle: "Heb 11 : 32 - 35",
      catholicEpistle: "2Pt  3 : 3 - 6",
      acts: "Act  12 : 6 - 18",
      psalm: "Ps 137 : 1, 2",
      gospel: "Luk  1 : 26 - 39"
    },
    evening: ["Job            38","Rom 6","Mat  3"],
    ana: 4,
  },
  {
    gregorianMonth: 4,
    gregorianDay: 9,
    gregorianDate: "Apr 9",
    ethiopianDate: "7/30",
    morning: ["Job 39","Rom 7","Mat 4"],
    qidase: {
      epistle: "Heb 5 : 1 - 10",
      catholicEpistle: "1Pt 3 : 8 - 18",
      acts: "Act 7 : 35 - 44",
      psalm: "Ps 104 : 26, 27",
      gospel: "Mat 6 : 1 - 16"
    },
    evening: ["Job            40","Rom 8 :1-17","Mat 5"],
    ana: 9,
  },
  {
    gregorianMonth: 4,
    gregorianDay: 10,
    gregorianDate: "Apr 10",
    ethiopianDate: "8/1",
    morning: ["Job 41","Rom 8 :18 - 39","Mat 6"],
    qidase: {
      epistle: "Rom 11 : 13 - 25",
      catholicEpistle: "Jam  3 : 1 - 13",
      acts: "Act 14 : 11 - 19",
      psalm: "Ps  104 : 27, 28",
      gospel: "Mat 15 : 21 - 29"
    },
    evening: ["Job          42","Rom 9","Mat 7"],
    ana: 13,
  },
  {
    gregorianMonth: 4,
    gregorianDay: 11,
    gregorianDate: "Apr 11",
    ethiopianDate: "8/2",
    morning: ["Pro 1","Rom 10","Mat 8"],
    qidase: {
      epistle: "Gal  1 : 20 - 6",
      catholicEpistle: "1Pt 2 : 3 - 11",
      acts: "Act 17 : 22 - 28",
      psalm: "Ps 134 : 5, 6",
      gospel: "Mat 16 : 5 - 13"
    },
    evening: ["Pro          2","Rom 11","Mat 9"],
    ana: 13,
  },
  {
    gregorianMonth: 4,
    gregorianDay: 12,
    gregorianDate: "Apr 12",
    ethiopianDate: "8/3",
    morning: ["Pro 3","Rom 12","Mat 10"],
    qidase: {
      epistle: "2Tm 3 : 1 - 10",
      catholicEpistle: "1Pt 3 : 18 - f",
      acts: "Act 17 : 23 - 30",
      psalm: "Ps 88:47b, 48",
      gospel: "Mat 19 : 1 - 16"
    },
    evening: ["Pro            4","Rom 13","Mat 11"],
    ana: 2,
  },
  {
    gregorianMonth: 4,
    gregorianDay: 13,
    gregorianDate: "Apr 13",
    ethiopianDate: "8/4",
    morning: ["Pro 5","Rom 14","Mat 12"],
    qidase: {
      epistle: "Heb 4 : 1 - 14",
      catholicEpistle: "1Pt 1 : 17 - f",
      acts: "Act 13 : 27 - 32",
      psalm: "Ps 94 : 7",
      gospel: "Luk 11 : 45 - f"
    },
    evening: ["Pro            6","Rom 15","Mat 13"],
    ana: 4,
  },
  {
    gregorianMonth: 4,
    gregorianDay: 14,
    gregorianDate: "Apr 14",
    ethiopianDate: "8/5",
    morning: ["Pro 7","Rom 16","Mat 14"],
    qidase: {
      epistle: "1Tm 2 : 9 - f",
      catholicEpistle: "2Pt 3 : 4 - 10",
      acts: "Act 17 : 13 - 19",
      psalm: "Ps 115 : 6, 7",
      gospel: "Mat 18 : 12 - 15"
    },
    evening: ["Pro            8","1Cr 1","Mat 15"],
    ana: 5,
  },
  {
    gregorianMonth: 4,
    gregorianDay: 15,
    gregorianDate: "Apr 15",
    ethiopianDate: "8/6",
    morning: ["Pro 9","1Cr 2","Mat 16"],
    qidase: {
      epistle: "Heb 13 : 1 - 17",
      catholicEpistle: "1Pt 2 : 3 - 11",
      acts: "Act 13 : 21 - 28",
      psalm: "Ps 86 : 1, 2",
      gospel: "Mat 1 : 1 - 18"
    },
    evening: ["Pro            10","1Cr 3","Mat 17"],
    ana: 4,
  },
  {
    gregorianMonth: 4,
    gregorianDay: 16,
    gregorianDate: "Apr 16",
    ethiopianDate: "8/7",
    morning: ["Pro 11","1Cr 4","Mat 18"],
    qidase: {
      epistle: "1Tm 2 : 8 - f",
      catholicEpistle: "1Pt 2 : 11 - 13",
      acts: "Act 13 : 44 - f",
      psalm: "Ps 78 : 10, 11",
      gospel: "Luk 12 : 1 - 13"
    },
    evening: ["Pro            12","1Cr 5","Mat 19"],
    ana: 5,
  },
  {
    gregorianMonth: 4,
    gregorianDay: 17,
    gregorianDate: "Apr 17",
    ethiopianDate: "8/8",
    morning: ["Pro 13","1Cr 6","Mat 20"],
    qidase: {
      epistle: "1Tm 2 : 8 - f",
      catholicEpistle: "1Pt 2 : 11 - 13",
      acts: "Act 13 : 44 - f",
      psalm: "Ps 78 : 10, 11",
      gospel: "Luk. 12 : 1 - 13"
    },
    evening: ["Pro            14","1Cr  7","Mat 21"],
    ana: 3,
  },
  {
    gregorianMonth: 4,
    gregorianDay: 18,
    gregorianDate: "Apr 18",
    ethiopianDate: "8/9",
    morning: ["Pro 15","1Cr 8","Mat 22"],
    qidase: {
      epistle: "2Cr 12 : 1 - 7",
      catholicEpistle: "1Jn 2 : 20 - f",
      acts: "Act 14 : 1 - 8",
      psalm: "Ps 8 : 2",
      gospel: "Mat 18 : 1 - 12"
    },
    evening: ["Pro            16","1Cr 9","Mat 23"],
    ana: 7,
  },
  {
    gregorianMonth: 4,
    gregorianDay: 19,
    gregorianDate: "Apr 19",
    ethiopianDate: "8/10",
    morning: ["Pro 17","1Cr 10 : 1-13","Mat 24"],
    qidase: {
      epistle: "2Ts 3 : 6 - f",
      catholicEpistle: "1Jn 3 : 13 - f",
      acts: "Act 15 : 30 - 36",
      psalm: "Ps 131 : 9, 10",
      gospel: "Mat 6 : 16 - 24"
    },
    evening: ["Pro            18","1Cr 10:14-33","Mat 25"],
    ana: 4,
  },
  {
    gregorianMonth: 4,
    gregorianDay: 20,
    gregorianDate: "Apr 20",
    ethiopianDate: "8/11",
    morning: ["Pro 19","1Cr  11:1-16","Mat 26"],
    qidase: {
      epistle: "Rom 16  : 1 - 3",
      catholicEpistle: "Jam 1 : 19 - f",
      acts: "Act 13 : 16 - 21",
      psalm: "Ps 44 : 9",
      gospel: "Mat 17 : 14 - 24"
    },
    evening: ["Pro          20","1Cr 11:17-34","Mat 27"],
    ana: 12,
  },
  {
    gregorianMonth: 4,
    gregorianDay: 21,
    gregorianDate: "Apr 21",
    ethiopianDate: "8/12",
    morning: ["Pro 21","1Cr 12","Mat 28"],
    qidase: {
      epistle: "1Tm 4 : 9 - f",
      catholicEpistle: "1Pt  2 :13 - 17",
      acts: "Act 24 : 14 - 22",
      psalm: "Ps 141 : 6",
      gospel: "Mat 24 : 8 - 20"
    },
    evening: ["Pro            22","1Cr 13","Mrk 1"],
    ana: 1,
  },
  {
    gregorianMonth: 4,
    gregorianDay: 22,
    gregorianDate: "Apr 22",
    ethiopianDate: "8/13",
    morning: ["Pro 23","1Cr 14:1-25","Mrk 2"],
    qidase: {
      epistle: "1Tm 5 : 9 - 11",
      catholicEpistle: "1Pt 2 : 20 - f",
      acts: "Act 13 : 1 - 7",
      psalm: "Ps 45 : 1, 2",
      gospel: "Mat 16 :13 - 15"
    },
    evening: ["Pro            24","1Cr 14:26-40","Mrk 3"],
    ana: 5,
  },
  {
    gregorianMonth: 4,
    gregorianDay: 23,
    gregorianDate: "Apr 23",
    ethiopianDate: "8/14",
    morning: ["Pro 25","1Cr 15:1-32","Mrk 4"],
    qidase: {
      epistle: "2Ts  2 : 1 - 11",
      catholicEpistle: "1Jn  4 : 1 - 9",
      acts: "Act 5 : 35 - f",
      psalm: "Ps 77 : 56, 57",
      gospel: "Mat  12 : 22 - 38"
    },
    evening: ["Pro            26","1Cr 15:33-58","Mrk 5"],
    ana: 1,
  },
  {
    gregorianMonth: 4,
    gregorianDay: 24,
    gregorianDate: "Apr 24",
    ethiopianDate: "8/15",
    morning: ["Pro 27","1Cr 16","Mrk 6"],
    qidase: {
      epistle: "2Cr  8 : 1 - 10",
      catholicEpistle: "1Pt  3 : 1 - 4",
      acts: "Act  11 : 27 - f",
      psalm: "Ps 30 : 4, 5",
      gospel: "Mat  14 : 1 - 13"
    },
    evening: ["Pro            28","2Cr 1","Mrk 7"],
    ana: 3,
  },
  {
    gregorianMonth: 4,
    gregorianDay: 25,
    gregorianDate: "Apr 25",
    ethiopianDate: "8/16",
    morning: ["Festal hiatus","3Jn  1 : 1 - 9","Act  5 : 34 - f","Ps 113 : 23, 24"],
    qidase: {
      psalm: "UNCLEAR - please verify",
      gospel: "Jhn 15 : 17 - 26"
    },
    evening: ["Pro 29","2Cr 2","Mrk 8"],
    ana: 1,
  },
  {
    gregorianMonth: 4,
    gregorianDay: 26,
    gregorianDate: "Apr 26",
    ethiopianDate: "8/17",
    morning: ["Pro 30","2Cr  3","Mrk 9"],
    qidase: {
      epistle: "2Cr   6 : 3 - 12",
      catholicEpistle: "1Pt  5 : 12 - f",
      acts: "Act  14 : 19 - f",
      psalm: "Ps 43 : 22, 23",
      gospel: "Luk  17 : 7 - 11"
    },
    evening: ["Pro            31","2Cr 4","Mrk 10"],
    ana: 7,
  },
  {
    gregorianMonth: 4,
    gregorianDay: 27,
    gregorianDate: "Apr 27",
    ethiopianDate: "8/18",
    morning: ["Ecc 1","2Cr 5","Mrk 11"],
    qidase: {
      epistle: "Rom  8 : 12 - 18",
      catholicEpistle: "1Jn  4 : 3 - 9",
      acts: "Act  5 : 33 - 36",
      psalm: "Ps 65 : 10, 11",
      gospel: "Mat  10 : 16 - 23"
    },
    evening: ["Ecc            2","2Cr 6","Mrk 12"],
    ana: 7,
  },
  {
    gregorianMonth: 4,
    gregorianDay: 28,
    gregorianDate: "Apr 28",
    ethiopianDate: "8/19",
    morning: ["Ecc 3","2Cr 7","Mrk 13"],
    qidase: {
      epistle: "2Cr  3 : 7 - 12",
      catholicEpistle: "Jam  3 : 13 - f",
      acts: "Act  5 : 38 - f",
      psalm: "Ps 78 : 10, 11",
      gospel: "Mat 25 : 14 - 31"
    },
    evening: ["Ecc            4","2Cr 8","Mrk 14"],
    ana: 5,
  },
  {
    gregorianMonth: 4,
    gregorianDay: 29,
    gregorianDate: "Apr 29",
    ethiopianDate: "8/20",
    morning: ["Ecc 5","2Cr 9","Mrk 15"],
    qidase: {
      epistle: "Eph 5 : 15 - 21",
      catholicEpistle: "1Pt  2 : 4 - 11",
      acts: "Act 17 : 30 - f",
      psalm: "Ps 44 : 12, 13",
      gospel: "Luk  17 : 1 - 11"
    },
    evening: ["Ecc            6","2Cr 10","Mrk 16"],
    ana: 4,
  },
  {
    gregorianMonth: 4,
    gregorianDay: 30,
    gregorianDate: "Apr 30",
    ethiopianDate: "8/21",
    morning: ["Ecc 7","2Cr  11:1-15","Luk 1"],
    qidase: {
      epistle: "1Tm 1:1-12",
      catholicEpistle: "1Jn  2 : 22 - f",
      acts: "Act  12 : 12 - 18",
      psalm: "Ps 131 : 9, 10",
      gospel: "Mat  18 : 15 - 21"
    },
    evening: ["Ecc            8","2Cr 11:16-33","Luk 2"],
    ana: 5,
  }
];
