/** Auto-generated by scripts/build-lectionary-readings.mjs — do not edit by hand. */
import type { DayReadings } from './types';

export const augustReadings: DayReadings[] = [
  {
    gregorianMonth: 8,
    gregorianDay: 1,
    gregorianDate: "Aug 1",
    ethiopianDate: "11/24",
    morning: ["TWS 2","Gal 3:15-29","Mat 21:1-32"],
    qidase: {
      epistle: "1Cr 2:1-f",
      catholicEpistle: "Jud 1:11-17",
      acts: "Act 26:6-12",
      psalm: "Ps 67:35",
      gospel: "Mrk 13:5 -14"
    },
    evening: ["TWS         3","Gal 4","Mat 21:33-46"],
    ana: 3,
  },
  {
    gregorianMonth: 8,
    gregorianDay: 2,
    gregorianDate: "Aug 2",
    ethiopianDate: "11/25",
    morning: ["TWS 4","Gal 5","Mat 22:1-14"],
    qidase: {
      epistle: "1Tm 6 : 3 - 20",
      catholicEpistle: "1Jn 2 : 1 - 12",
      acts: "Act 5 : 28 - 34",
      psalm: "Ps 67:31,32",
      gospel: "Mat 1 : 18 - f"
    },
    evening: ["TWS         5","Gal 7","Mat 22:15-45"],
    ana: 2,
  },
  {
    gregorianMonth: 8,
    gregorianDay: 3,
    gregorianDate: "Aug 3",
    ethiopianDate: "11/26",
    morning: ["TWS 6","Eph 1","Mat 23"],
    qidase: {
      epistle: "Heb 5 : 7 - f",
      catholicEpistle: "1Jn 5 : 16 - f",
      acts: "Act 4 : 10 - 19",
      psalm: "Ps 88:18,19",
      gospel: "Jhn 10 : 34 - f"
    },
    evening: ["TWS        7","Eph 2","Mat 24:1-35"],
    ana: 10,
  },
  {
    gregorianMonth: 8,
    gregorianDay: 4,
    gregorianDate: "Aug 4",
    ethiopianDate: "11/27",
    morning: ["TWS 8","Eph 3","Mat 24:36-51"],
    qidase: {
      epistle: "1Cr 7 : 1 - f",
      catholicEpistle: "1Pt 3 : 1 - 8",
      acts: "Act 7 : 1 - 9",
      psalm: "Ps 54 :13,14",
      gospel: "Mat 19:1-13"
    },
    evening: ["TWS         9","Eph 4","Mat 26:1-30"],
    ana: 4,
  },
  {
    gregorianMonth: 8,
    gregorianDay: 5,
    gregorianDate: "Aug 5",
    ethiopianDate: "11/28",
    morning: ["TWS 10","Eph 5","Mat 25:31-46"],
    qidase: {
      epistle: "Gal 3:15– f",
      catholicEpistle: "1Jn 4:9 –18",
      acts: "Act  9 : 20 – 32",
      psalm: "Ps 33:19,20",
      gospel: "Luk 12:1-13"
    },
    evening: ["TWS 11","Eph 6","Mat 27:1-46"],
    ana: 12,
  },
  {
    gregorianMonth: 8,
    gregorianDay: 6,
    gregorianDate: "Aug 6",
    ethiopianDate: "11/29",
    morning: ["TWS 12","Phl 1","Mat 26:47-75"],
    qidase: {
      epistle: "1Cr 2 : 1 – 9",
      catholicEpistle: "2Pt 1 : 12 – 17",
      acts: "Act3  : 1 – 10",
      psalm: "Ps 123:4,5",
      gospel: "Mrk 4 : 35 - f"
    },
    evening: ["TWS         13","Phl 2","Mat 27"],
    ana: 1,
  },
  {
    gregorianMonth: 8,
    gregorianDay: 7,
    gregorianDate: "Aug 7",
    ethiopianDate: "11/30",
    morning: ["Sir 12","1Tm 4","Mrk 16"],
    qidase: {
      psalm: "UNCLEAR - please verify",
      gospel: "UNCLEAR - please verify"
    },
    evening: [],
    ana: null,
  },
  {
    gregorianMonth: 8,
    gregorianDay: 8,
    gregorianDate: "Aug 8",
    ethiopianDate: "12/1",
    morning: ["TWS 16","Col 1","Mrk 2"],
    qidase: {
      epistle: "1Tm 2 : 8 - f",
      catholicEpistle: "1Pt 3: 1 - 7",
      acts: "Act 16 : 13 - 19",
      psalm: "Ps 44:14,15",
      gospel: "UNCLEAR - please verify"
    },
    evening: ["Jn 8 : 1 - 12","Col 2","Mrk 3"],
    ana: null,
  },
  {
    gregorianMonth: 8,
    gregorianDay: 9,
    gregorianDate: "Aug 9",
    ethiopianDate: "12/2",
    morning: ["TWS 18","Col 3","Mrk 4"],
    qidase: {
      epistle: "1Ts 3 : 1 - f",
      catholicEpistle: "1Pt 3 : 10 - 15",
      acts: "Ac 14 : 20 - f",
      psalm: "UNCLEAR - please verify",
      gospel: "UNCLEAR - please verify"
    },
    evening: ["Ps 44:12,13","Luk 18 : 9 - 18","Mrk 5"],
    ana: null,
  },
  {
    gregorianMonth: 8,
    gregorianDay: 10,
    gregorianDate: "Aug 10",
    ethiopianDate: "12/3",
    morning: ["Sir 18","Tts 1","Luk 5"],
    qidase: {
      psalm: "UNCLEAR - please verify",
      gospel: "UNCLEAR - please verify"
    },
    evening: [],
    ana: null,
  },
  {
    gregorianMonth: 8,
    gregorianDay: 11,
    gregorianDate: "Aug 11",
    ethiopianDate: "12/4",
    morning: ["Sir 6","2Ts:1","Mrk 10"],
    qidase: {
      psalm: "UNCLEAR - please verify",
      gospel: "UNCLEAR - please verify"
    },
    evening: [],
    ana: null,
  },
  {
    gregorianMonth: 8,
    gregorianDay: 12,
    gregorianDate: "Aug 12",
    ethiopianDate: "12/5",
    morning: ["Sir 5","1Ts:5","Mrk 9:33-50"],
    qidase: {
      epistle: "1Cr 3 : 10 - 22",
      catholicEpistle: "1Pt 3 : 1 - 7",
      psalm: "UNCLEAR - please verify",
      gospel: "UNCLEAR - please verify"
    },
    evening: ["Act 16 : 13 - 19","Ps 44:12,13","Mrk 16 : 9 - 19"],
    ana: null,
  },
  {
    gregorianMonth: 8,
    gregorianDay: 13,
    gregorianDate: "Aug 13",
    ethiopianDate: "12/6",
    morning: ["Sir 7","2Ts:2","Mrk  11"],
    qidase: {
      epistle: "Heb 9 : 1 - 11",
      catholicEpistle: "1Pt 2 : 6 - 18",
      acts: "Act 10 : 1 - 30",
      psalm: "Ps 93:12",
      gospel: "Mat 1:1-17"
    },
    evening: ["Mat 16:13-24","2Ts:3","Mrk 12"],
    ana: null,
  },
  {
    gregorianMonth: 8,
    gregorianDay: 14,
    gregorianDate: "Aug 14",
    ethiopianDate: "12/7",
    morning: ["Sir 9","1Tm 1","Mrk  13"],
    qidase: {
      epistle: "Rom 9 : 24 - f",
      catholicEpistle: "1Pt 4 : 12 - f",
      acts: "Act 16 : 35 - f",
      psalm: "Ps",
      gospel: "Mat 7 : 12 - 26"
    },
    evening: ["Sir 10","1Tm 2","Mrk 14"],
    ana: null,
  },
  {
    gregorianMonth: 8,
    gregorianDay: 15,
    gregorianDate: "Aug 15",
    ethiopianDate: "12/8",
    morning: ["Sir 11","1Tm 3","Mrk  15"],
    qidase: {
      epistle: "Phl 1 : 12 - 24",
      catholicEpistle: "2J n 1 : 6 - f",
      psalm: "UNCLEAR - please verify",
      gospel: "UNCLEAR - please verify"
    },
    evening: ["Act 15 : 19 – 25","Ps 44: 9","Jn 10 : 1 - 22"],
    ana: null,
  },
  {
    gregorianMonth: 8,
    gregorianDay: 16,
    gregorianDate: "Aug 16",
    ethiopianDate: "12/9",
    morning: ["Sir 13","2Tm 1","Luk 1:1-38"],
    qidase: {
      epistle: "Heb 12 : 22 - f",
      catholicEpistle: "1Pt 1:6-13",
      acts: "Act 4:31-f",
      psalm: "Ps 73",
      gospel: "UNCLEAR - please verify"
    },
    evening: ["Luk 16:9 -19","1Tm 2","Luk 1:39-80"],
    ana: null,
  },
  {
    gregorianMonth: 8,
    gregorianDay: 17,
    gregorianDate: "Aug 17",
    ethiopianDate: "12/10",
    morning: ["Sir 15","2Tm 3","Luk 2"],
    qidase: {
      epistle: "1Cr  5 : 11 - f",
      catholicEpistle: "1Jn 2 : 14 - 20",
      acts: "Act 12 : 18 - f",
      psalm: "Ps 44:16, 17a",
      gospel: "Luk 6:20-24"
    },
    evening: ["Sir 16","1Tm 4","Luk 3"],
    ana: null,
  },
  {
    gregorianMonth: 8,
    gregorianDay: 18,
    gregorianDate: "Aug 18",
    ethiopianDate: "12/11",
    morning: ["Sir 17","2Tm 3","Luk  4"],
    qidase: {
      epistle: "1Cr 9 : 17 - f",
      catholicEpistle: "Jud 1 : 8 - 14",
      psalm: "Ps 137:1,2",
      gospel: "Mt 25 : 31 - f"
    },
    evening: ["Act 24 : 1 - 22","Ps 71:1,2","Mat 22:1-15"],
    ana: null,
  },
  {
    gregorianMonth: 8,
    gregorianDay: 19,
    gregorianDate: "Aug 19",
    ethiopianDate: "4/12",
    morning: ["Festal hiatus","Ps 67:15,16","Mt 17 : 1 - 14","Heb 11 : 23 - 30"],
    qidase: {
      catholicEpistle: "2Pt 1 : 15 - f",
      acts: "Act 7 : 44 - 51",
      psalm: "Ps 88:12,13",
      gospel: "Luk 9 : 28 - 38"
    },
    evening: ["Sir 19","Tts 1","Luk  6"],
    ana: null,
  },
  {
    gregorianMonth: 8,
    gregorianDay: 20,
    gregorianDate: "Aug 20",
    ethiopianDate: "4/10",
    morning: ["Sir 20","Tts 2","Luk 7"],
    qidase: {
      epistle: "1Cr  1 : 10 - 19",
      catholicEpistle: "Jam 1 : 12 - 24",
      acts: "Act 10 : 30 - 44",
      psalm: "Ps 43:4,5",
      gospel: "Mat 17 : 14 - 24"
    },
    evening: ["Sir 21","Tts 3","Luk 8"],
    ana: null,
  },
  {
    gregorianMonth: 8,
    gregorianDay: 21,
    gregorianDate: "Aug 21",
    ethiopianDate: "12/14",
    morning: ["Sir 22","Luk 9:1-27","1Cr 12 : 18 - f"],
    qidase: {
      epistle: "Jd 1 : 17 - f",
      acts: "Act 1 : 12 - 15",
      psalm: "Ps 18:4,5",
      gospel: "UNCLEAR - please verify"
    },
    evening: ["Mat 10 : 1 - 15","Heb 1","Luk 9:28-62"],
    ana: null,
  },
  {
    gregorianMonth: 8,
    gregorianDay: 22,
    gregorianDate: "Aug 22",
    ethiopianDate: "12/15",
    morning: ["Festal hiatus","Ps 44:9","Lk 1: 39 - 57","Rm 8 : 31 - f"],
    qidase: {
      catholicEpistle: "1Jn 2 : 1 - 7",
      acts: "Act 1 : 12 - 15",
      psalm: "Ps 45:4,5",
      gospel: "Mat 26 : 26 - 31"
    },
    evening: ["Sir       24","Heb 2","Luk 10"],
    ana: 2,
  },
  {
    gregorianMonth: 8,
    gregorianDay: 23,
    gregorianDate: "Aug 23",
    ethiopianDate: "12/16",
    morning: ["Sir 25","Heb 3","Luk 11:1-26"],
    qidase: {
      epistle: "Phl  3 : 1  - 15",
      catholicEpistle: "1Pt 4 : 12  - f",
      acts: "Act 9 : 1 - 8",
      psalm: "Ps 117:18,19",
      gospel: "Jn 15 : 12 - 27"
    },
    evening: ["Sir 26","Heb 4","Luk 11:27-54"],
    ana: 4,
  },
  {
    gregorianMonth: 8,
    gregorianDay: 24,
    gregorianDate: "Aug 24",
    ethiopianDate: "12/17",
    morning: ["Sir 27","Heb 5","Luk  12"],
    qidase: {
      epistle: "Phl 3 : 1 - 6",
      catholicEpistle: "1Jn 2 : 1 - 20",
      acts: "Act 20 : 28 - 31",
      psalm: "Ps 2:12",
      gospel: "Mat 15 : 6 - 21"
    },
    evening: ["Sir 28","Heb 6","Luk 13"],
    ana: 4,
  },
  {
    gregorianMonth: 8,
    gregorianDay: 25,
    gregorianDate: "Aug 25",
    ethiopianDate: "12/18",
    morning: ["Sir 29","Heb 7","Luk 14"],
    qidase: {
      epistle: "Rom 1 : 8 - 15",
      catholicEpistle: "1Pt 3 : 8 -15",
      acts: "Act 16 : 35 - f",
      psalm: "Ps 55:10,11",
      gospel: "Mat 27 : 50 - 57"
    },
    evening: ["Sir     30","Heb 8","Luk 15"],
    ana: 4,
  },
  {
    gregorianMonth: 8,
    gregorianDay: 26,
    gregorianDate: "Aug 26",
    ethiopianDate: "12/19",
    morning: ["Sir 31","Heb 9","Luk 16"],
    qidase: {
      epistle: "1Cr 15 : 33 - 51",
      catholicEpistle: "Jm 4 : 11 - f",
      acts: "Act 23 : 22 - f",
      psalm: "Ps 12:3",
      gospel: "Mat 22 : 23 - 34"
    },
    evening: ["Sir       32","Heb 10:1-18","Luk 17"],
    ana: 4,
  },
  {
    gregorianMonth: 8,
    gregorianDay: 27,
    gregorianDate: "Aug 27",
    ethiopianDate: "12/20",
    morning: ["Sir 33","Heb 10:19-39","Luk 18"],
    qidase: {
      epistle: "1Cr 7 : 25 - f",
      catholicEpistle: "2Jn 1 : 1 - 7",
      acts: "Act 16 : 13 - 18",
      psalm: "Ps 44:9,10",
      gospel: "Mat 2:1-14"
    },
    evening: ["Sir       34","Heb 11:1-16","Luk 19"],
    ana: 4,
  },
  {
    gregorianMonth: 8,
    gregorianDay: 28,
    gregorianDate: "Aug 28",
    ethiopianDate: "12/21",
    morning: ["Sir 35","Heb 11:17-40","Luk 20"],
    qidase: {
      epistle: "Rom 11 : 25 - f",
      catholicEpistle: "2Pt 1 : 19 - f",
      acts: "Act 7 : 51 - 54",
      psalm: "Ps 104,14,15",
      gospel: "Mat 2:1-7"
    },
    evening: ["Sir 36","Jam 1","Luk 21"],
    ana: 4,
  },
  {
    gregorianMonth: 8,
    gregorianDay: 29,
    gregorianDate: "Aug 29",
    ethiopianDate: "12/22",
    morning: ["Sir 37","Heb 13","Luk 22"],
    qidase: {
      epistle: "1Cr 13 : 1 - f",
      catholicEpistle: "1Pt 5 : 1 - 12",
      acts: "Act 12 : 18 - f",
      psalm: "Ps 45:2,3",
      gospel: "Mat 21:18-23"
    },
    evening: ["Sir     38","Jam 1","Luk 23"],
    ana: 4,
  },
  {
    gregorianMonth: 8,
    gregorianDay: 30,
    gregorianDate: "Aug 30",
    ethiopianDate: "12/23",
    morning: ["Festal hiatus","Ps 83:6","Jn 10 : 1 - 22","Rom 8 : 35 - f"],
    qidase: {
      catholicEpistle: "1Pt 5 : 1 - 6",
      acts: "Act 20 : 28 - 31",
      psalm: "Ps 43:22,23",
      gospel: "Mat 10:16-f"
    },
    evening: ["Sir 39","Jam 2","Luk 24"],
    ana: 5,
  },
  {
    gregorianMonth: 8,
    gregorianDay: 31,
    gregorianDate: "Aug 31",
    ethiopianDate: "12/24",
    morning: ["Sir 40","Jam 3","Jhn 1"],
    qidase: {
      epistle: "Eph 6 : 10 - 19",
      catholicEpistle: "1Pt 3 : 1 - 10",
      acts: "Act 12 : 12 - 20",
      psalm: "Ps 38:7,8",
      gospel: "Mrk 3:7-13"
    },
    evening: ["Sir       41","Jam 4","Jhn 2","Exodus                                       Exo","Leviticus                        Lev","Numbers                          Num","Deuteronomy        Deu","Joshua                                       Jos","Ezra                                       Ezr","Nehemiah                       Neh","Esther                                       Est","Job                                       Job","Proverbs                         Pro","Ecclesiastes              Ecc","Song of Solomon SOS","Isaiah                                       Isa","Jeremiah                         Jer","Lamentations        Lam","Ezekiel                                       Eze","Daniel                                                    Dan","Hosea                                       Hos","Joel                                       Joe","Amos                                       Amo","Obadiah                           Oba","Jonah                                       Jon","Micah                                       Mic","Nahum                                       Nah","Habakkuk                       Hab","Zephaniah                      Zep","Haggai                                       Hab","Zechariah                       Zec","Malachi                          Mal","Tobit                                       Tob","Esther (Greek)    EsG","Sirach                                       Sir","      Jeremiah","Psalm 151  151","Matthew                      Mat","Mark                                    Mrk","Luke                                    Luk","John                                    Jhn","Acts                                    Act","Romans                       Rom","Galatians                     Gal","Ephesians                Eph","Philippians            Phl","Colossians              Col","Hebrews                      Heb","Jude                                    Jud"],
    ana: 7,
  }
];
