/** Auto-generated by scripts/build-lectionary-readings.mjs — do not edit by hand. */
import type { DayReadings } from './types';

export const decemberReadings: DayReadings[] = [
  {
    gregorianMonth: 12,
    gregorianDay: 1,
    gregorianDate: "Dec 1",
    ethiopianDate: "3/21",
    morning: ["Jdg 8","Heb 13:16-25","Mrk 8"],
    qidase: {
      epistle: "2Cr   6 : 12 - f",
      catholicEpistle: "1Pt 2:5-11",
      acts: "Act  7:44- 54",
      psalm: "Ps 131:13, 14",
      gospel: "Mt  21:42-f"
    },
    evening: ["Jdg 9","Jam 1","Mrk 9"],
    ana: 4,
  },
  {
    gregorianMonth: 12,
    gregorianDay: 2,
    gregorianDate: "Dec 2",
    ethiopianDate: "3/22",
    morning: ["Jdg 10, 11","Jam 2","Mrk 9:33-50"],
    qidase: {
      epistle: "2Cr 7:1-5",
      catholicEpistle: "Jam 1:2-16",
      acts: "Act 17:2-13 or 9:36",
      psalm: "Ps 78:10, 11",
      gospel: "Mat 9:10-18"
    },
    evening: ["Jdg 12, 13","Jam 3","Mrk 8"],
    ana: 3,
  },
  {
    gregorianMonth: 12,
    gregorianDay: 3,
    gregorianDate: "Dec 3",
    ethiopianDate: "3/23",
    morning: ["Jdg 14, 15","Jam 4;  Mrk 11","Ps 83:11"],
    qidase: {
      epistle: "Heb  11 : 32 - f",
      catholicEpistle: "2Pt  1 : 19 - f",
      acts: "Act  10 : 23 - 32",
      psalm: "Ps 138 : 17, 18",
      gospel: "Mat  10 : 32 - f"
    },
    evening: ["Jdg 16","Jam 5","Mrk 12"],
    ana: 3,
  },
  {
    gregorianMonth: 12,
    gregorianDay: 4,
    gregorianDate: "Dec 4",
    ethiopianDate: "3/24",
    morning: ["Jdg 17, 18","1Pt 1: 1-12","Mrk 13"],
    qidase: {
      epistle: "Rev 12:6-12",
      catholicEpistle: "Jam 5:17 - f",
      acts: "Act 10:23-32",
      psalm: "Ps 102:19,20",
      gospel: "Mat  13 : 36 - 43"
    },
    evening: ["Jdg 19","1Pt 1:13-25","Mrk 14"],
    ana: 5,
  },
  {
    gregorianMonth: 12,
    gregorianDay: 5,
    gregorianDate: "Dec 5",
    ethiopianDate: "3/25",
    morning: ["Jdg 20","1Pt 2","Mrk 15"],
    qidase: {
      epistle: "2Cr   7 :  1 - 12",
      catholicEpistle: "1Pt  4 : 12 - f",
      acts: "Act  5 : 12 - 17",
      psalm: "Ps 67 : 23",
      gospel: "Mat  10 : 17- 32"
    },
    evening: ["Jdg 21","1Pt  3","Mrk 16"],
    ana: 3,
  },
  {
    gregorianMonth: 12,
    gregorianDay: 6,
    gregorianDate: "Dec 6",
    ethiopianDate: "3/26",
    morning: ["1Pt 4:1-14","Luk 1:1-38","2Cr  7 : 1 - f"],
    qidase: {
      catholicEpistle: "1Pt 1 :  1 - 9",
      acts: "Act  20 : 28 - 36",
      psalm: "Ps  9 : 12, 13",
      gospel: "UNCLEAR - please verify"
    },
    evening: ["Luk  21 : 12 - 21","1Pt 4:12-25","Luk 1:39-80"],
    ana: null,
  },
  {
    gregorianMonth: 12,
    gregorianDay: 7,
    gregorianDate: "Dec 7",
    ethiopianDate: "3/27",
    morning: ["Luk 2","Ps 2 : 1, 2","Mat 26 : 57 - f"],
    qidase: {
      epistle: "Pm   1 : 1 - f",
      catholicEpistle: "1Pt 5 : 9 - f",
      acts: "Act  11 : 25 - f",
      psalm: "Ps 39 : 1",
      gospel: "Luk  10 : 1 - 12"
    },
    evening: ["Isa          1","2Pt 1","Luk 3"],
    ana: 10,
  },
  {
    gregorianMonth: 12,
    gregorianDay: 8,
    gregorianDate: "Dec 8",
    ethiopianDate: "3/28",
    morning: ["Isa 2","2Pt  2","Luk 4"],
    qidase: {
      epistle: "2Cr  4 : 1 - 7",
      catholicEpistle: "Jam  2 : 21 - f",
      acts: "Act  3 : 12 - 17",
      psalm: "Ps 96:11, 12",
      gospel: "Mrk 12 : 25 - 28"
    },
    evening: ["Isa 3","2Pt 3","Luk 5"],
    ana: 5,
  },
  {
    gregorianMonth: 12,
    gregorianDay: 9,
    gregorianDate: "Dec 9",
    ethiopianDate: "3/29",
    morning: ["Isa 4","1Jn 1","Luk 6"],
    qidase: {
      epistle: "Phi  3 : 1 - 15",
      catholicEpistle: "1Pt  5 : 1 - 13",
      acts: "Act 27 : 39 - f",
      psalm: "Ps 118:95, 96",
      gospel: "Jhn  10 : 1 - 22"
    },
    evening: ["Isa 5","1Jn 2","Luk 7"],
    ana: 7,
  },
  {
    gregorianMonth: 12,
    gregorianDay: 10,
    gregorianDate: "Dec 10",
    ethiopianDate: "3/30",
    morning: ["Isa 6","1Jn  3","Luk 8"],
    qidase: {
      epistle: "1Tm  1 : 5 - 15",
      catholicEpistle: "1Pt  2 : 13 - 21",
      acts: "Act   23 : 10 - 32",
      psalm: "Ps 25 : 5, 6",
      gospel: "Luk  19 : 11 - 28"
    },
    evening: ["Isa 7","1Jn 4","Luk 9"],
    ana: 4,
  },
  {
    gregorianMonth: 12,
    gregorianDay: 11,
    gregorianDate: "Dec 11",
    ethiopianDate: "4/1",
    morning: ["Isa 8","1Jn 5; Luk 10","Ps 68 : 9, 10"],
    qidase: {
      epistle: "Rom  11 : 1 - 13",
      catholicEpistle: "Jam  5 :  16 - f",
      acts: "Act  3 : 19 - f",
      psalm: "Ps 104:14, 15",
      gospel: "Luk  4 : 25 - 33"
    },
    evening: ["Isa 9","2Jn 1","Luk 11:1-26"],
    ana: 4,
  },
  {
    gregorianMonth: 12,
    gregorianDay: 12,
    gregorianDate: "Dec 12",
    ethiopianDate: "4/2",
    morning: ["Isa 10","3Jn  1","Luk  11:27-54"],
    qidase: {
      epistle: "Heb  11 : 32 - f",
      catholicEpistle: "1Pt  4 : 12 - f",
      acts: "Act  20 : 9 - 13",
      psalm: "Ps 65:12, 13",
      gospel: "Mat  19 : 10 - 15"
    },
    evening: ["Isa 11","Jud 1","Luk  12"],
    ana: 4,
  },
  {
    gregorianMonth: 12,
    gregorianDay: 13,
    gregorianDate: "Dec 13",
    ethiopianDate: "4/3",
    morning: ["Isa 12;  Act 1","Luk 13","Ps 65 : 13, 14"],
    qidase: {
      epistle: "Heb  9 : 1 - 17",
      catholicEpistle: "2Jn 1 : 5 - 8",
      acts: "Act  1:12-15",
      psalm: "Ps 44:10, 11",
      gospel: "Luk  1 : 39-57"
    },
    evening: ["Isa 13","Act 2:1-21","Luk 14"],
    ana: 4,
  },
  {
    gregorianMonth: 12,
    gregorianDay: 14,
    gregorianDate: "Dec 14",
    ethiopianDate: "4/4",
    morning: ["Ps 18 : 4, 5","Jhn  1 :  38 - 46","2Cr  11 : 21 - f"],
    qidase: {
      catholicEpistle: "Jud  1 : 16 - 23",
      acts: "Act   4 : 29 - f",
      psalm: "Ps 105:18, 19",
      gospel: "Luk  9 : 46 - 56"
    },
    evening: ["Isa 14","Act 2:22-47","Luk 15"],
    ana: 1,
  },
  {
    gregorianMonth: 12,
    gregorianDay: 15,
    gregorianDate: "Dec 15",
    ethiopianDate: "4/5",
    morning: ["Isa 15","Act 3","Luk 16"],
    qidase: {
      epistle: "Gal  3 : 21 - f",
      catholicEpistle: "1Pt  5 : 9 - f",
      acts: "Act  16 : 14 - 16",
      psalm: "Ps 34:11, 12",
      gospel: "Mat   10 : 35 - f"
    },
    evening: ["Isa  16","Act 4","Luk 17"],
    ana: 5,
  },
  {
    gregorianMonth: 12,
    gregorianDay: 16,
    gregorianDate: "Dec 16",
    ethiopianDate: "4/6",
    morning: ["Isa  17","Act 5:1-16","Luk 18"],
    qidase: {
      epistle: "Gal 4:12-21",
      catholicEpistle: "1Pt 5:2-9",
      acts: "Act 5:1-11",
      psalm: "Ps 45:1, 2",
      gospel: "Mat 17:14-24"
    },
    evening: ["Isa  18","Act 5:17-42","Luk 19"],
    ana: 7,
  },
  {
    gregorianMonth: 12,
    gregorianDay: 17,
    gregorianDate: "Dec 17",
    ethiopianDate: "4/7",
    morning: ["Isa  19","Act 6","Luk 20"],
    qidase: {
      epistle: "Eph  6 : 10 - f",
      catholicEpistle: "1Pt  3 : 10 - 15",
      acts: "Act  16 : 16 - 25",
      psalm: "Ps 76:6, 7",
      gospel: "Mrk  16 : 15 - f"
    },
    evening: ["Isa  20,21","Act 7:1-34","Luk 21"],
    ana: 11,
  },
  {
    gregorianMonth: 12,
    gregorianDay: 18,
    gregorianDate: "Dec 18",
    ethiopianDate: "4/8",
    morning: ["Isa  22","Act 7:35-60","Luk 22:1-21"],
    qidase: {
      epistle: "2Cr  12 : 1 - 8",
      catholicEpistle: "1Pt  3 : 8 - 15",
      acts: "Act 21 : 1 - 8",
      psalm: "Ps 26:5",
      gospel: "Mat  11 : 16 - 20"
    },
    evening: ["Isa  23","Act 8:1-25","Luk  22:31-71"],
    ana: 10,
  },
  {
    gregorianMonth: 12,
    gregorianDay: 19,
    gregorianDate: "Dec 19",
    ethiopianDate: "4/9",
    morning: ["Isa  24","Act  8:26-40","Luk 23"],
    qidase: {
      epistle: "1Ts  2 : 13 - f",
      catholicEpistle: "Jam  5 : 8 : 12",
      acts: "Act 3 : 22 - f",
      psalm: "Ps 93 : 6, 7",
      gospel: "Mrk  5 : 25 - 35"
    },
    evening: ["Isa  25","Act 9","Luk 24"],
    ana: 3,
  },
  {
    gregorianMonth: 12,
    gregorianDay: 20,
    gregorianDate: "Dec 20",
    ethiopianDate: "4/10",
    morning: ["Isa  26","Act 10:1-29","Jhn 1"],
    qidase: {
      epistle: "1Cr  9 : 1 - 15",
      catholicEpistle: "1Jn  2 : 20 - f",
      acts: "Act  20 : 16 - 22",
      psalm: "Ps 111 : 9",
      gospel: "Mat  6 : 1 - 5"
    },
    evening: ["Isa  27","Act 10:30-48","Jhn 2"],
    ana: 5,
  },
  {
    gregorianMonth: 12,
    gregorianDay: 21,
    gregorianDate: "Dec 21",
    ethiopianDate: "4/11",
    morning: ["Isa  28","Act 11","Jhn 3"],
    qidase: {
      epistle: "Rom   12 : 9 - f",
      catholicEpistle: "1Pt  4 : 6 - 12",
      acts: "Act  17 : 28  -f",
      psalm: "Ps 87 : 11, 12",
      gospel: "Mat  6 : 7 - 17"
    },
    evening: ["Isa  29","Act 12","Jhn 4"],
    ana: 5,
  },
  {
    gregorianMonth: 12,
    gregorianDay: 22,
    gregorianDate: "Dec 22",
    ethiopianDate: "4/12",
    morning: ["Isa  30","Act 13 :1-15","Jhn 5"],
    qidase: {
      epistle: "Heb  6 : 1 - 13",
      catholicEpistle: "Jam  5 : 14 - f",
      acts: "Act  5 : 29 - 39",
      psalm: "Ps 43 : 7, 8",
      gospel: "Mat  18 : 12 - 23"
    },
    evening: ["Isa  31, 32","Act 13: 16-52","Jhn 6"],
    ana: 10,
  },
  {
    gregorianMonth: 12,
    gregorianDay: 23,
    gregorianDate: "Dec 23",
    ethiopianDate: "4/13",
    morning: ["Isa  33","Act 14","Jhn 7"],
    qidase: {
      epistle: "1Ts  4 : 15 - f",
      catholicEpistle: "Jam  1 : 21 – f",
      acts: "Act  10 : 9 - 17",
      psalm: "Ps 86 : 1, 2",
      gospel: "Mat  10 : 26 - 34"
    },
    evening: ["Isa  34, 35","Act 15:1-12","Jhn 8"],
    ana: 4,
  },
  {
    gregorianMonth: 12,
    gregorianDay: 24,
    gregorianDate: "Dec 24",
    ethiopianDate: "4/14",
    morning: ["Isa  36","Act 15:13-31","Jhn 9"],
    qidase: {
      epistle: "1Cr  1 : 1 - 17",
      catholicEpistle: "1Pt  1 : 13 - f",
      acts: "Act  8 : 18 - 26",
      psalm: "Ps 138 : 12, 13",
      gospel: "Mat  10 : 16 - 23"
    },
    evening: ["Isa  37","Act 16:1-15","Jhn 10"],
    ana: 5,
  },
  {
    gregorianMonth: 12,
    gregorianDay: 25,
    gregorianDate: "Dec 25",
    ethiopianDate: "4/15",
    morning: ["Isa  38, 39","Act 16:16-40","Jhn 11"],
    qidase: {
      epistle: "Pl  2 : 5 - 12",
      catholicEpistle: "Jam  1 : 19 - f",
      acts: "Act 20 : 18 - 26",
      psalm: "Ps  30 : 12, 13",
      gospel: "Luk  15 : 11 - 25"
    },
    evening: ["Isa  40","Act 17, 18","Jhn 12"],
    ana: 5,
  },
  {
    gregorianMonth: 12,
    gregorianDay: 26,
    gregorianDate: "Dec 26",
    ethiopianDate: "4/16",
    morning: ["Isa  41","Act 19 : 1-20","Jhn 13"],
    qidase: {
      epistle: "Heb  11 : 32 - f",
      catholicEpistle: "1Pt  3 : 5 - 7",
      acts: "Act 13 : 20 - 24",
      psalm: "Ps 17 : 39, 40",
      gospel: "Jhn  1 : 1 - 29"
    },
    evening: ["Isa  42","Act 19:21-40","Jhn 14"],
    ana: 4,
  },
  {
    gregorianMonth: 12,
    gregorianDay: 27,
    gregorianDate: "Dec 27",
    ethiopianDate: "4/17",
    morning: ["Isa  43","Act 20","Jhn 15"],
    qidase: {
      epistle: "Rom  8 : 18 - 31",
      catholicEpistle: "Jam   1 : 17 - 22",
      acts: "Act  15 : 10 - 13",
      psalm: "Ps 2 : 11, 12",
      gospel: "Luk  11 : 1 -14"
    },
    evening: ["Isa  44","Act 21","Jhn 16"],
    ana: 5,
  },
  {
    gregorianMonth: 12,
    gregorianDay: 28,
    gregorianDate: "Dec 28",
    ethiopianDate: "4/18",
    morning: ["Isa  45","Act 21:12-40","Jhn 17"],
    qidase: {
      epistle: "2Cr  7 : 13 - f",
      catholicEpistle: "Jud  1 : 17 - f",
      acts: "Act  5 :  12 - 17",
      psalm: "Ps 18 : 3, 4",
      gospel: "Jhn  11 : 9 - 17"
    },
    evening: ["Isa  46","Act 22","Jhn 18"],
    ana: 1,
  },
  {
    gregorianMonth: 12,
    gregorianDay: 29,
    gregorianDate: "Dec 29",
    ethiopianDate: "4/19",
    morning: ["Isa  47","Act 23","Jhn 19"],
    qidase: {
      epistle: "2Ts  1 : 6 - f",
      catholicEpistle: "Jud  1 :  20 - f",
      acts: "Act  7 : 30 - 35",
      psalm: "Ps 137: 1, 2",
      gospel: "Luk  1 : 11 - 21"
    },
    evening: ["Isa  48","Act 24","Jhn 20"],
    ana: 4,
  },
  {
    gregorianMonth: 12,
    gregorianDay: 30,
    gregorianDate: "Dec 30",
    ethiopianDate: "4/20",
    morning: ["Isa  49","Act 25","Jhn 21"],
    qidase: {
      epistle: "2Cr  4 : 3 - 13",
      catholicEpistle: "2Pt  1 : 19 - f",
      acts: "Act  7 : 44 - 51",
      psalm: "Ps 104 : 14, 15",
      gospel: "Jhn  1 : 6 - 15"
    },
    evening: ["Isa  50","Act 26","Mat 1"],
    ana: 3,
  },
  {
    gregorianMonth: 12,
    gregorianDay: 31,
    gregorianDate: "Dec 31",
    ethiopianDate: "4/21",
    morning: ["Ps 18 : 4, 5","Luk  10 : 1-12","Gal  2 : 1 - 14"],
    qidase: {
      epistle: "Col  4 : 1 - f",
      catholicEpistle: "Jud  1 : 17 – f",
      acts: "Act  11 : 23 - f",
      psalm: "Ps 44 : 9, 10",
      gospel: "Luk  1 : 17-39"
    },
    evening: ["Isa  51","Act 27","Mat 2"],
    ana: 4,
  }
];
