/** Auto-generated by scripts/build-lectionary-readings.mjs — do not edit by hand. */
import type { DayReadings } from './types';

export const februaryReadings: DayReadings[] = [
  {
    gregorianMonth: 2,
    gregorianDay: 1,
    gregorianDate: "Feb 1",
    ethiopianDate: "5/23",
    morning: ["2Sa 6","2Cr 11:16-33","Luk 9"],
    qidase: {
      epistle: "2Tm 1:1-10",
      catholicEpistle: "1Pt 3:13-18",
      acts: "Act 16:1-13",
      psalm: "Ps 50:12,13",
      gospel: "Luk 12:17-35"
    },
    evening: ["2Sa            7","2Cr 12","Luk 10"],
    ana: 1,
  },
  {
    gregorianMonth: 2,
    gregorianDay: 2,
    gregorianDate: "Feb 2",
    ethiopianDate: "5/24",
    morning: ["2Sa 8","2Cr 13","Luk 11"],
    qidase: {
      epistle: "Tts 2 : 1 - 9",
      catholicEpistle: "1Pt 3 : 2 - 5",
      acts: "Act 20 : 28 - 31",
      psalm: "Ps 131 : 9, 10",
      gospel: "Luk 18 : 1 - 9"
    },
    evening: ["2Sa            9","Gal 1","Luk 12"],
    ana: 7,
  },
  {
    gregorianMonth: 2,
    gregorianDay: 3,
    gregorianDate: "Feb 3",
    ethiopianDate: "5/25",
    morning: ["2Sa 10","Gal 2","Luk 13"],
    qidase: {
      epistle: "2Cr 9 : 5 - f",
      catholicEpistle: "1Jn  3 : 16 - f  A",
      acts: "Act 4 : 29 - f",
      psalm: "Ps  111 : 9",
      gospel: "Mrk 10 : 17 - 28"
    },
    evening: ["2Sa            11","Gal 3","Luk 14"],
    ana: 3,
  },
  {
    gregorianMonth: 2,
    gregorianDay: 4,
    gregorianDate: "Feb 4",
    ethiopianDate: "5/26",
    morning: ["2Sa 12","Gal 4","Luk 15"],
    qidase: {
      epistle: "2Cr 2 : 1 - 8",
      catholicEpistle: "1Pt 5 : 9 - f",
      acts: "Act 4 : 29 - f",
      psalm: "Ps 65 : 13, 14",
      gospel: "UNCLEAR - please verify"
    },
    evening: ["Luk 11 : 1 - 19","Gal 5","Luk 16"],
    ana: null,
  },
  {
    gregorianMonth: 2,
    gregorianDay: 5,
    gregorianDate: "Feb 5",
    ethiopianDate: "5/27",
    morning: ["2Sa 14","Gal 6","Luk 17"],
    qidase: {
      epistle: "Heb 11 : 5 - 8",
      catholicEpistle: "Jud 1 : 11 - 17",
      acts: "Act 17:14 - 22",
      psalm: "Ps 43 : 22,23",
      gospel: "Mat 11 : 8 - 17"
    },
    evening: ["2Sa          15","Eph 1","Luk 18"],
    ana: 12,
  },
  {
    gregorianMonth: 2,
    gregorianDay: 6,
    gregorianDate: "Feb 6",
    ethiopianDate: "5/28",
    morning: ["2Sa 16","Eph 2","Luk 19"],
    qidase: {
      epistle: "Heb 11 : 8 - 17",
      catholicEpistle: "1Pt 4 : 12 - f",
      acts: "Act 2 : 32 - 40",
      psalm: "Ps  67 : 24,25",
      gospel: "Mat 15 : 32 - f"
    },
    evening: ["2Sa            17","Eph 3","Luk 20"],
    ana: 5,
  },
  {
    gregorianMonth: 2,
    gregorianDay: 7,
    gregorianDate: "Feb 7",
    ethiopianDate: "5/29",
    morning: ["2Sa 18","Eph 4","Luk 21"],
    qidase: {
      epistle: "1Tm 3 : 14 - f",
      catholicEpistle: "1Jn 1 : 9 - f",
      acts: "Act 3 : 12 - 17",
      psalm: "Ps  38 : 12",
      gospel: "Jhn 1 : 7 - 15"
    },
    evening: ["2Sa            19","Eph 5","Luk 22"],
    ana: 4,
  },
  {
    gregorianMonth: 2,
    gregorianDay: 8,
    gregorianDate: "Feb 8",
    ethiopianDate: "5/30",
    morning: ["2Sa 20","Eph 6","Luk 23"],
    qidase: {
      epistle: "1Tm 5 : 1 - 7",
      catholicEpistle: "1Pt 5 : 2 - 5",
      acts: "Act 9 : 36 - f",
      psalm: "Ps  44 : 14,15",
      gospel: "Luk 23 26 - 32"
    },
    evening: ["2Sa            21","Phl 1","Luk 24"],
    ana: 4,
  },
  {
    gregorianMonth: 2,
    gregorianDay: 9,
    gregorianDate: "Feb 9",
    ethiopianDate: "6/1",
    morning: ["2Sa 22","Phl 2","Jhn 1"],
    qidase: {
      epistle: "Eph 4 : 17 - f",
      catholicEpistle: "Jud 1 : 17 - 23",
      acts: "Act 20 : 28 - 31",
      psalm: "Ps 32 : 5. 6",
      gospel: "Jhn 15 : 26 - 27"
    },
    evening: ["2Sa            23","Phl 3","Jhn 2"],
    ana: 5,
  },
  {
    gregorianMonth: 2,
    gregorianDay: 10,
    gregorianDate: "Feb 10",
    ethiopianDate: "6/2",
    morning: ["2Sa 24","Phl 4","Jhn 3"],
    qidase: {
      epistle: "Eph 6 : 10 - 19",
      catholicEpistle: "Jud 1 : 17 - f",
      acts: "Act 28 : 1 - 7",
      psalm: "Ps  73 : 13,14",
      gospel: "UNCLEAR - please verify"
    },
    evening: ["Mrk 16 : 14 - f","Col 1","Jhn 4"],
    ana: null,
  },
  {
    gregorianMonth: 2,
    gregorianDay: 11,
    gregorianDate: "Feb 11",
    ethiopianDate: "6/3",
    morning: ["Col 2","Jhn 5","Rom 2 : 1 - 17"],
    qidase: {
      catholicEpistle: "Jam 4 - 7 - f",
      acts: "Act 20 : 9 - 16",
      psalm: "Ps  114 : 8",
      gospel: "UNCLEAR - please verify"
    },
    evening: ["Luk 7 : 12 - 18","Col 3","Jhn 6"],
    ana: null,
  },
  {
    gregorianMonth: 2,
    gregorianDay: 12,
    gregorianDate: "Feb 12",
    ethiopianDate: "6/4",
    morning: ["Festal hiatus","Jam 1 : 17 - f","Act 21 : 10 - 15","Ps 83 : 6, 7"],
    qidase: {
      psalm: "UNCLEAR - please verify",
      gospel: "UNCLEAR - please verify"
    },
    evening: ["Luk 10 : 1 - 12","Col 4","Jhn 7"],
    ana: null,
  },
  {
    gregorianMonth: 2,
    gregorianDay: 13,
    gregorianDate: "Feb 13",
    ethiopianDate: "6/5",
    morning: ["Jhn 8","Rom 5 : 15 - f","Jud 1 : 20 - f"],
    qidase: {
      acts: "Act 21 : 15 - 27",
      psalm: "UNCLEAR - please verify",
      gospel: "UNCLEAR - please verify"
    },
    evening: ["Ps 31 : 1, 2","Mat 9 : 10 - 19","Jhn 9"],
    ana: null,
  },
  {
    gregorianMonth: 2,
    gregorianDay: 14,
    gregorianDate: "Feb 14",
    ethiopianDate: "6/6",
    morning: ["Jhn 10","Rom 1 : 15 - 18","Jam 4 : 1 - 10"],
    qidase: {
      acts: "Act 27 : 39 - f",
      psalm: "UNCLEAR - please verify",
      gospel: "UNCLEAR - please verify"
    },
    evening: ["Ps 44 : 8, 9","Mat 26 : 6 - 17","Jhn 11"],
    ana: null,
  },
  {
    gregorianMonth: 2,
    gregorianDay: 15,
    gregorianDate: "Feb 15",
    ethiopianDate: "6/7",
    morning: ["Jhn 12","Eph 6 : 10 - 19","Rev 13 : 11 - f"],
    qidase: {
      acts: "Act 20 : 28 - 31",
      psalm: "Ps 43 : 5, 6",
      gospel: "UNCLEAR - please verify"
    },
    evening: ["Luk 19 : 11 - 28","2Ts  1","Jhn 13"],
    ana: null,
  },
  {
    gregorianMonth: 2,
    gregorianDay: 16,
    gregorianDate: "Feb 16",
    ethiopianDate: "6/8",
    morning: ["Ps 102 : 5, 6","Luk 2 : 36 - 40","1Tm 5 : 5 - 11"],
    qidase: {
      catholicEpistle: "Jam 5 : 13 - f",
      acts: "Act  3 : 17 - f",
      psalm: "Ps 44 : 1, 2",
      gospel: "UNCLEAR - please verify"
    },
    evening: ["Luk 2 : 22 - 35","2Ts 2","Jhn 14"],
    ana: null,
  },
  {
    gregorianMonth: 2,
    gregorianDay: 17,
    gregorianDate: "Feb 17",
    ethiopianDate: "6/9",
    morning: ["2Ts 3","Jhn 15","Tts 3 : 8 - f"],
    qidase: {
      catholicEpistle: "2Jn 1 : 8 - f",
      acts: "Act 10 : 36 - 49",
      psalm: "Ps  111: 6",
      gospel: "UNCLEAR - please verify"
    },
    evening: ["Jhn 8 : 51 - f","1Tm  1","Jhn 16"],
    ana: null,
  },
  {
    gregorianMonth: 2,
    gregorianDay: 18,
    gregorianDate: "Feb 18",
    ethiopianDate: "6/10",
    morning: ["1Tm  2","Jhn 17","1Cr 12 : 4 - 28"],
    qidase: {
      catholicEpistle: "Jud 1 : 17 - f",
      acts: "Act 1 : 12 - 15",
      psalm: "Ps 18 : 3, 4",
      gospel: "UNCLEAR - please verify"
    },
    evening: ["Mat 10 : 1 - 9","1Tm 3","Jhn 18"],
    ana: null,
  },
  {
    gregorianMonth: 2,
    gregorianDay: 19,
    gregorianDate: "Feb 19",
    ethiopianDate: "6/11",
    morning: ["1Tm 4","Jhn 19","2Tm 4 : 14 - 19"],
    qidase: {
      catholicEpistle: "Jam 3 : 5 - 11",
      acts: "Act 14 : 19 - f",
      psalm: "Ps 49 : 10, 11",
      gospel: "UNCLEAR - please verify"
    },
    evening: ["Mrk 1 : 12 - 17","1Tm  5, 6","Jhn 20, 21"],
    ana: null,
  },
  {
    gregorianMonth: 2,
    gregorianDay: 20,
    gregorianDate: "Feb 20",
    ethiopianDate: "6/12",
    morning: ["Ps 33 : 7, 8","Mat 25: 31 - f","1Cr 5 : 6 - f"],
    qidase: {
      catholicEpistle: "Jud 1 : 9 - 19",
      acts: "Act 28 :30 - f",
      psalm: "Ps 138 : 17, 18",
      gospel: "UNCLEAR - please verify"
    },
    evening: ["Mat 20 : 24 - 29","2Tm  1","Mat 1"],
    ana: null,
  },
  {
    gregorianMonth: 2,
    gregorianDay: 21,
    gregorianDate: "Feb 21",
    ethiopianDate: "6/13",
    morning: ["2Tm  2","Mat 2","2Cr 12 : 1 - 11"],
    qidase: {
      catholicEpistle: "1Pt 1 : 6 - 11",
      acts: "Act 15 : 22 - 36",
      psalm: "Ps  138 : 7, 8",
      gospel: "UNCLEAR - please verify"
    },
    evening: ["Mat 5 : 27 - 33","2Tm  3","Mat 3"],
    ana: null,
  },
  {
    gregorianMonth: 2,
    gregorianDay: 22,
    gregorianDate: "Feb 22",
    ethiopianDate: "6/14",
    morning: ["2Tm  4","Mat 4","Tts 1 : 7 - 12"],
    qidase: {
      catholicEpistle: "1Jn 2 : 20 - f",
      acts: "Act 20 : 28 - f",
      psalm: "Ps  44 : 5",
      gospel: "UNCLEAR - please verify"
    },
    evening: ["Mat 18 : 15 - 23","Tts 1","Mat 5"],
    ana: null,
  },
  {
    gregorianMonth: 2,
    gregorianDay: 23,
    gregorianDate: "Feb 23",
    ethiopianDate: "6/15",
    morning: ["2Kg 2","Tts 2","Mat 6"],
    qidase: {
      epistle: "1Ts 5 :  4 - f",
      catholicEpistle: "2Pt 1 : 19 - f",
      acts: "Act 3 : 17 - f",
      psalm: "Ps  147 : 1, 2",
      gospel: "Mat 21 : 1 - 7"
    },
    evening: ["2Kg            3","Tts 3","Mat 7"],
    ana: 5,
  },
  {
    gregorianMonth: 2,
    gregorianDay: 24,
    gregorianDate: "Feb 24",
    ethiopianDate: "6/16",
    morning: ["Ps  112 : 9","Luk 1 : 5 - 18","Gal 4 : 1 - 12"],
    qidase: {
      catholicEpistle: "2Jn 1 : 4 - 8",
      acts: "Act 1 : 13 - 15",
      psalm: "Ps 88 : 2, 3",
      gospel: "Luk 1 : 39 - 57"
    },
    evening: ["2Kg            4","Plm 1","Mat  8"],
    ana: 5,
  },
  {
    gregorianMonth: 2,
    gregorianDay: 25,
    gregorianDate: "Feb 25",
    ethiopianDate: "6/17",
    morning: ["2Kg 5","Heb 1","Mat 9"],
    qidase: {
      epistle: "Heb 11 : 23 - 29",
      catholicEpistle: "Jud 1 : 6 - 11",
      acts: "Act 7 : 20 - 44",
      psalm: "Ps  102 : 7, 8",
      gospel: "Luk 20 : 37 - 41"
    },
    evening: ["2Kg            6","Heb  2","Mat 10"],
    ana: 4,
  },
  {
    gregorianMonth: 2,
    gregorianDay: 26,
    gregorianDate: "Feb 26",
    ethiopianDate: "6/18",
    morning: ["Heb  3","Mat 11","Gal 1 : 15 - f"],
    qidase: {
      catholicEpistle: "Jam 1 : 1 - 12",
      acts: "Act 21 : 17 - 26",
      psalm: "Ps  18 : 3, 4",
      gospel: "Mat 13 : 43 - f"
    },
    evening: ["2Kg            8","Heb  4","Mat 12"],
    ana: 2,
  },
  {
    gregorianMonth: 2,
    gregorianDay: 27,
    gregorianDate: "Feb 27",
    ethiopianDate: "6/19",
    morning: ["2Kg 9","Heb  5","Mat 13"],
    qidase: {
      epistle: "Rom 7 : 22 - f",
      catholicEpistle: "Jam 4 : 1 - 11",
      acts: "Act 16 : 16 - 22",
      psalm: "Ps  17 : 29, 30",
      gospel: "Luk 13 : 1 - 18"
    },
    evening: ["2Kg            10","Heb  6","Mat 14"],
    ana: 5,
  },
  {
    gregorianMonth: 2,
    gregorianDay: 28,
    gregorianDate: "Feb 28",
    ethiopianDate: "6/20",
    morning: ["2Kg 11","Heb  7","Mat 15"],
    qidase: {
      epistle: "2Tm 3 : 1 - 13",
      catholicEpistle: "1Pt 5 : 1 - 11",
      acts: "Act 9 : 23 -32",
      psalm: "Ps  33 : 14, 15",
      gospel: "Mat 5 : 1 - 17"
    },
    evening: ["2Kg            12","Heb  8","Mat 16"],
    ana: 5,
  }
];
