/** Auto-generated by scripts/build-lectionary-readings.mjs — do not edit by hand. */
import type { DayReadings } from './types';
import { januaryReadings } from './january';
import { februaryReadings } from './february';
import { marchReadings } from './march';
import { aprilReadings } from './april';
import { mayReadings } from './may';
import { juneReadings } from './june';
import { julyReadings } from './july';
import { augustReadings } from './august';
import { septemberReadings } from './september';
import { octoberReadings } from './october';
import { novemberReadings } from './november';
import { decemberReadings } from './december';

export const allReadings: DayReadings[] = [
  ...januaryReadings,
  ...februaryReadings,
  ...marchReadings,
  ...aprilReadings,
  ...mayReadings,
  ...juneReadings,
  ...julyReadings,
  ...augustReadings,
  ...septemberReadings,
  ...octoberReadings,
  ...novemberReadings,
  ...decemberReadings,
];

export function getTodayReadings(): DayReadings | undefined {
  const today = new Date();
  return getReadingsByDate(today.getMonth() + 1, today.getDate());
}

export function getReadingsByDate(month: number, day: number): DayReadings | undefined {
  return allReadings.find((r) => r.gregorianMonth === month && r.gregorianDay === day);
}

export function getReadingsByEthiopianDate(ethiopianDate: string): DayReadings | undefined {
  return allReadings.find((r) => r.ethiopianDate === ethiopianDate);
}

export type { DayReadings, QidaseReadings, ScriptureRef } from './types';
