/** Auto-generated by scripts/build-lectionary-readings.mjs — do not edit by hand. */
import type { DayReadings } from './types';

export const januaryReadings: DayReadings[] = [
  {
    gregorianMonth: 1,
    gregorianDay: 1,
    gregorianDate: "Jan 1",
    ethiopianDate: "4/22",
    morning: ["Ps  136 : 1-2","Luk  1 : 26 -39","2Tm  1 : 8 - f"],
    qidase: {
      catholicEpistle: "1Jn  4 : 9 –18",
      acts: "Act 12 : 7-12",
      psalm: "Ps 44 : 16-17",
      gospel: "Luk  1 : 39 -57"
    },
    evening: ["Isa 52","Act 28","Mat 3"],
    ana: 4,
  },
  {
    gregorianMonth: 1,
    gregorianDay: 2,
    gregorianDate: "Jan 2",
    ethiopianDate: "4/23",
    morning: ["Isa 53","Rom 1","Mat 4"],
    qidase: {
      epistle: "2Tm   2 : 8 - 19",
      catholicEpistle: "1Pt  5 : 2 - 8",
      acts: "Act 12:7-12",
      psalm: "Ps 18:12, 13",
      gospel: "Luk  1 : 39 - 57"
    },
    evening: ["Isa 54","Rom 2","Mat 5"],
    ana: 5,
  },
  {
    gregorianMonth: 1,
    gregorianDay: 3,
    gregorianDate: "Jan 3",
    ethiopianDate: "4/24",
    morning: ["Ps  50 : 14 - 15","Mat  11 : 25 - f","Ep   4 : 11 - 17"],
    qidase: {
      catholicEpistle: "1Pt 1 : 13 - f",
      acts: "Ac 19:11-21",
      psalm: "Ps 8 : 2",
      gospel: "Mat  18 : 1 - 12"
    },
    evening: ["Isa 55","Rom 3","Mat 6"],
    ana: 1,
  },
  {
    gregorianMonth: 1,
    gregorianDay: 4,
    gregorianDate: "Jan 4",
    ethiopianDate: "4/25",
    morning: ["Isa  56","Rom 4","Mat 7"],
    qidase: {
      epistle: "Tt  2 : 13 - f",
      catholicEpistle: "1Jn  2 : 12 - 18",
      acts: "Ac  4 : 31 - f",
      psalm: "Ps  78 : 2 - 3",
      gospel: "Mat  13 : 36 - 44"
    },
    evening: ["Isa 57","Rom 5","Mat 8"],
    ana: 5,
  },
  {
    gregorianMonth: 1,
    gregorianDay: 5,
    gregorianDate: "Jan 5",
    ethiopianDate: "4/26",
    morning: ["Isa 58","Rom 6","Mat 9"],
    qidase: {
      epistle: "1Cr  7 : 34 - f",
      catholicEpistle: "1Jn   5 : 14 -  f",
      acts: "Act  16 : 14 - 16",
      psalm: "Ps  44 : 9",
      gospel: "Mat  25 : 1 - 16"
    },
    evening: ["Isa 59","Rom 7","Mat 10"],
    ana: 3,
  },
  {
    gregorianMonth: 1,
    gregorianDay: 6,
    gregorianDate: "Jan 6",
    ethiopianDate: "4/27",
    morning: ["Isa  60","Rom 8:1-17","Mat 11"],
    qidase: {
      epistle: "Rom  17 : 16 - f",
      catholicEpistle: "1Pt  2 : 21 - f",
      acts: "Act  20 : 28 - 31",
      psalm: "Ps 79:2, 3",
      gospel: "Jhn  10 : 17 - 22"
    },
    evening: ["Isa          61","Rom 8:18-39","Mat 12"],
    ana: 10,
  },
  {
    gregorianMonth: 1,
    gregorianDay: 7,
    gregorianDate: "Jan 7",
    ethiopianDate: "4/28",
    morning: ["Isa 62","Rom 9","Mat 13"],
    qidase: {
      epistle: "Rm  8 : 3 - 18",
      catholicEpistle: "1Jn  4 : 1 - 9",
      psalm: "Ps 109 : 3",
      gospel: "Luk 1 : 26 - 57"
    },
    evening: ["Festal hiatus"],
    ana: 4,
  },
  {
    gregorianMonth: 1,
    gregorianDay: 8,
    gregorianDate: "Jan 8",
    ethiopianDate: "4/29",
    morning: ["Ps  71 : 10a-11a","Mat  1 : 18 - f","Gal  4 : 1 - 12"],
    qidase: {
      catholicEpistle: "1Jn  4 : 9 - f",
      acts: "Act 13 : 16 - 22",
      psalm: "Ps  71 : 15",
      gospel: "Luk  2 : 1 - 21"
    },
    evening: ["Isa 63, 64","Rom 10","Mat 14"],
    ana: 14,
  },
  {
    gregorianMonth: 1,
    gregorianDay: 9,
    gregorianDate: "Jan 9",
    ethiopianDate: "4/30",
    morning: ["Isa 65","Rom 11","Mat 15"],
    qidase: {
      epistle: "Phl  3 : 15 - f",
      catholicEpistle: "1Pt 2 : 12 - 21",
      acts: "Act 19 : 8 - 21",
      psalm: "Ps  78 : 10 - 11",
      gospel: "Mat  2 : 1 - 13"
    },
    evening: ["Isa 66","Rom 12","Mat  16"],
    ana: 4,
  },
  {
    gregorianMonth: 1,
    gregorianDay: 10,
    gregorianDate: "Jan 10",
    ethiopianDate: "5/1",
    morning: ["Ps  78 : 10 - 11","Mrk  13 : 9 - 23","Heb 11:32-f"],
    qidase: {
      catholicEpistle: "1Pt  4 : 12 - f",
      acts: "Act  7 : 51 - 8 : 3",
      psalm: "Ps  20 : 3 - 4",
      gospel: "Mat  21  : 33 - f"
    },
    evening: ["1Sa 1","Rom 13","Mat 17"],
    ana: 3,
  },
  {
    gregorianMonth: 1,
    gregorianDay: 11,
    gregorianDate: "Jan 11",
    ethiopianDate: "5/2",
    morning: ["1Sa 2","Rom 14","Mat 18"],
    qidase: {
      epistle: "Hb  11 : 1 - 8",
      catholicEpistle: "1Jn 3 : 6 - 13",
      acts: "Act  12 : 18 - f",
      psalm: "Ps 93 : 21 - 22",
      gospel: "Mat  23 : 13 - 23"
    },
    evening: ["1Sa 3","Rom 15","Mat 19"],
    ana: 5,
  },
  {
    gregorianMonth: 1,
    gregorianDay: 12,
    gregorianDate: "Jan 12",
    ethiopianDate: "5/3",
    morning: ["Festal hiatus","Rm  11 : 25 - f","1Pt  2 : 1 - 11","Act 28 : 17 - f"],
    qidase: {
      psalm: "Ps  43 : 22 - 23",
      gospel: "Mat  2 : 13 - f"
    },
    evening: ["1Sa 4","Rom 16","Mat 20"],
    ana: 4,
  },
  {
    gregorianMonth: 1,
    gregorianDay: 13,
    gregorianDate: "Jan 13",
    ethiopianDate: "5/4",
    morning: ["Ps  18 : 3 - 4","Mat  4 : 17 - f","1Tm  6 : 1 - 11"],
    qidase: {
      catholicEpistle: "1Jn  1 : 1 - f",
      acts: "Act 4 : 8-24",
      psalm: "Ps  138 : 17-18",
      gospel: "Jhn 21 : 20 - f"
    },
    evening: ["1Sa 5","1Cr 1","Mat 21"],
    ana: 3,
  },
  {
    gregorianMonth: 1,
    gregorianDay: 14,
    gregorianDate: "Jan 14",
    ethiopianDate: "5/5",
    morning: ["1Sa 7","1Cr 2","Mat 21, 22"],
    qidase: {
      epistle: "Heb  2 : 11 - f",
      catholicEpistle: "Jam  3 : 5 - 13",
      acts: "Act  7 : 45",
      psalm: "Ps  84 : 6 - 7",
      gospel: "Jhn  18 : 33 - 38"
    },
    evening: ["1Sa 7","1Cr 3","Mat 23"],
    ana: 8,
  },
  {
    gregorianMonth: 1,
    gregorianDay: 15,
    gregorianDate: "Jan 15",
    ethiopianDate: "5/6",
    morning: ["Ps  71 : 17","Luk  2 : 8 - 22","Rm  15 : 8 - 14"],
    qidase: {
      catholicEpistle: "2Pt  2 : 1 - 9",
      acts: "Act  7 : 2 - 9",
      psalm: "Ps  104 : 14 - 15",
      gospel: "Luk 4 : 24-33"
    },
    evening: ["1Sa 8","1Cr 4","Mat 24"],
    ana: 12,
  },
  {
    gregorianMonth: 1,
    gregorianDay: 16,
    gregorianDate: "Jan 16",
    ethiopianDate: "5/7",
    morning: ["1Sa 9","1Cr 5","Mat 25"],
    qidase: {
      epistle: "Co  2 : 10 - 16",
      catholicEpistle: "1Jn  2 : 25 - f",
      psalm: "UNCLEAR - please verify",
      gospel: "UNCLEAR - please verify"
    },
    evening: ["Act  22 : 7 - 22","Ps   71 : 15","Mat  2 : 21 - f"],
    ana: null,
  },
  {
    gregorianMonth: 1,
    gregorianDay: 17,
    gregorianDate: "Jan 17",
    ethiopianDate: "5/8",
    morning: ["1Sa 11","1Cr 7","Mat 27"],
    qidase: {
      epistle: "2Tm  4 : 5 - 14",
      catholicEpistle: "1Pt  5 : 12 - f",
      acts: "Act  15 : 36 - f",
      psalm: "Ps  117 : 15 - 16",
      gospel: "Luk  2 : 39 - f"
    },
    evening: ["1Sa 12","1Cr 8","Mat 28"],
    ana: 7,
  },
  {
    gregorianMonth: 1,
    gregorianDay: 18,
    gregorianDate: "Jan 18",
    ethiopianDate: "5/9",
    morning: ["1Sa 13","1Cr 9","Mrk 1"],
    qidase: {
      epistle: "Rom  5 : 1 - 10",
      catholicEpistle: "1Jn  2 : 8 - 18",
      acts: "Act  11 : 27 - f",
      psalm: "Ps  71 : 10 - 11",
      gospel: "Mat  5 : 39 - f"
    },
    evening: ["1Sa 14","1Cr 10:1-13","Mrk 2"],
    ana: 9,
  },
  {
    gregorianMonth: 1,
    gregorianDay: 19,
    gregorianDate: "Jan 19",
    ethiopianDate: "5/10",
    morning: ["1Sa 15","1Cr 10:14-33","Mrk 3"],
    qidase: {
      epistle: "Gal  3 : 20 - f",
      catholicEpistle: "1Jn  4 : 14 - 18",
      acts: "Act  13 : 24 - 30",
      psalm: "Ps  84 : 10 - 11",
      gospel: "Mat  3 : 1 - 13"
    },
    evening: ["Festal hiatus"],
    ana: 2,
  },
  {
    gregorianMonth: 1,
    gregorianDay: 20,
    gregorianDate: "Jan 20",
    ethiopianDate: "5/11",
    morning: ["Ps  113 : 3 - 4","Mat  3 : 13 - f","Tts  3 : 4 - 8"],
    qidase: {
      catholicEpistle: "1Jn  5 : 5 - 13",
      acts: "Act  10 : 34 - 39",
      psalm: "Ps  76 : 16",
      gospel: "Luk 3 : 21-f"
    },
    evening: ["1Sa          16","1Cr 11","Mrk  4, 5"],
    ana: 12,
  },
  {
    gregorianMonth: 1,
    gregorianDay: 21,
    gregorianDate: "Jan 21",
    ethiopianDate: "5/12",
    morning: ["Ps  83 : 6 - 7","Mat  1 : 1 - 12","Rm  9 : 1 - 17"],
    qidase: {
      catholicEpistle: "Jud  1 : 9 - 14",
      acts: "Act  10 : 34 - 39",
      psalm: "Ps  45 : 7, 8",
      gospel: "Jhn 1 : 44 - f"
    },
    evening: ["1Sa 17, 18","1Cr 12","Mrk 6"],
    ana: 9,
  },
  {
    gregorianMonth: 1,
    gregorianDay: 22,
    gregorianDate: "Jan 22",
    ethiopianDate: "5/13",
    morning: ["Festal hiatus","1Pt  1 : 10 - 22","Act  2 : 22 - 33","Ps  12 : 3"],
    qidase: {
      psalm: "Ps  76 : 13",
      gospel: "Jhn 2:1-12"
    },
    evening: ["1Sa 19","1Cr 13","Mrk 7"],
    ana: 5,
  },
  {
    gregorianMonth: 1,
    gregorianDay: 23,
    gregorianDate: "Jan 23",
    ethiopianDate: "5/14",
    morning: ["1Sa 20","1Cr 14:1-25","Mrk 8"],
    qidase: {
      epistle: "Gal  1 : 15 - f",
      catholicEpistle: "1Jn  5 : 18 - f",
      acts: "Act  22 : 14 - 22",
      psalm: "Ps  78 : 10 - 11",
      gospel: "Jhn  3 : 22 - f"
    },
    evening: ["1Sa 21","1Cr 14:26-40","Mrk 9"],
    ana: 9,
  },
  {
    gregorianMonth: 1,
    gregorianDay: 24,
    gregorianDate: "Jan 24",
    ethiopianDate: "5/15",
    morning: ["1Sa 22","1Cr 15:1-32","Mrk 10"],
    qidase: {
      epistle: "Heb  12 : 1 - 11",
      catholicEpistle: "1Pt  4 : 11 - 15",
      acts: "Act  16 : 14 - 19",
      psalm: "Ps 65 : 12, 13",
      gospel: "Mat 18 : 1-12"
    },
    evening: ["1Sa          23","1Cr 15:33-58","Mrk 11"],
    ana: 12,
  },
  {
    gregorianMonth: 1,
    gregorianDay: 25,
    gregorianDate: "Jan 25",
    ethiopianDate: "5/16",
    morning: ["1Sa 24","1Cr 16","Mrk 12"],
    qidase: {
      epistle: "1Cr  13 : 12 - f",
      catholicEpistle: "1Jn  3 : 1 - 7",
      acts: "Act  20  9 - 13",
      psalm: "Ps 105 : 39 – 40",
      gospel: "Mat 5:25-33"
    },
    evening: ["1Sa 25","2Cr 1","Mrk 13"],
    ana: 5,
  },
  {
    gregorianMonth: 1,
    gregorianDay: 26,
    gregorianDate: "Jan 26",
    ethiopianDate: "5/17",
    morning: ["1Sa 26","2Cr 2","Mrk 14"],
    qidase: {
      epistle: "2Cr  8 : 16 - f",
      catholicEpistle: "1Pt  3 : 8 - 15",
      acts: "Ac  19 : 8 - 11",
      psalm: "Ps  90 : 10 - 11",
      gospel: "Jhn   5 : 25 - 33"
    },
    evening: ["1Sa          27","2Cr 3","Mrk 15"],
    ana: 12,
  },
  {
    gregorianMonth: 1,
    gregorianDay: 27,
    gregorianDate: "Jan 27",
    ethiopianDate: "5/18",
    morning: ["1Sa 28","2Cr 4","Mrk 16"],
    qidase: {
      epistle: "Rom  8 : 35 - f",
      catholicEpistle: "1Pt  3 : 1 - 7",
      acts: "Act  17 : 30 - f",
      psalm: "Ps  33 : 19 - 20",
      gospel: "Mrk 17 : 19-f"
    },
    evening: ["1Sa 29","2Cr 5","Luk 1"],
    ana: 3,
  },
  {
    gregorianMonth: 1,
    gregorianDay: 28,
    gregorianDate: "Jan 28",
    ethiopianDate: "5/19",
    morning: ["1Sa 30","2Cr 6","Luk 2"],
    qidase: {
      epistle: "Col  1 : 27 - f",
      catholicEpistle: "1Jn  5 : 14 - f",
      acts: "Act  17 :  5 - 10",
      psalm: "Ps   78 : 10 - 11",
      gospel: "Mat  5 : 42 - f"
    },
    evening: ["1Sa 31","2Cr  7","Luk 3"],
    ana: 5,
  },
  {
    gregorianMonth: 1,
    gregorianDay: 29,
    gregorianDate: "Jan 29",
    ethiopianDate: "5/20",
    morning: ["2Sa 1","2Cr 8","Luk 4"],
    qidase: {
      epistle: "1Cr  12 : 28 - f",
      catholicEpistle: "Jud  1 : 17 - f",
      acts: "Act  2 : 1 - 9",
      psalm: "Ps  35 : 7, 8",
      gospel: "Luk  10 : 12 - 21"
    },
    evening: ["2Sa 2","2Cr 9","Luk 5"],
    ana: 9,
  },
  {
    gregorianMonth: 1,
    gregorianDay: 30,
    gregorianDate: "Jan 30",
    ethiopianDate: "5/21",
    morning: ["Ps  147 : 1 - 2","Gal  4 : 1 - 12","2Jn  1 : 1 - 7"],
    qidase: {
      acts: "Act  7 : 30 - 35",
      psalm: "Ps  47 : 8",
      gospel: "Luk  1 : 47 - 57"
    },
    evening: ["2Sa 3","2Cr 10:1-9","Luk 6"],
    ana: 4,
  },
  {
    gregorianMonth: 1,
    gregorianDay: 31,
    gregorianDate: "Jan 31",
    ethiopianDate: "5/22",
    morning: ["2Sa 4","2Cr 10:10-18","Luk 7"],
    qidase: {
      epistle: "Eph  7 : 10 - f",
      catholicEpistle: "1Pt  4 : 4 - 12",
      acts: "Act  28 : 1 - 11",
      psalm: "Ps  91:12, 13",
      gospel: "Mat  6: 6- 19"
    },
    evening: ["2Sa 5","2Cr 11:1-15","Luk 8"],
    ana: 5,
  }
];
