/** Auto-generated by scripts/build-lectionary-readings.mjs — do not edit by hand. */
import type { DayReadings } from './types';

export const julyReadings: DayReadings[] = [
  {
    gregorianMonth: 7,
    gregorianDay: 1,
    gregorianDate: "Jul 1",
    ethiopianDate: "10/23",
    morning: ["Mic 6","Act 24","Luk 13"],
    qidase: {
      epistle: "Rom  9 : 24 - f",
      catholicEpistle: "1Jn  1 : 4 - f",
      acts: "Act 14 : 1 - 7",
      psalm: "Ps 104 : 21",
      gospel: "Jn 12 : 20 - 27"
    },
    evening: ["Mic         7","Act 25","Luk 14"],
    ana: 5,
  },
  {
    gregorianMonth: 7,
    gregorianDay: 2,
    gregorianDate: "Jul 2",
    ethiopianDate: "10/24",
    morning: ["Heb  6 : 7 - 13","Jd  1 : 1 - 7","Act  14 : 16 - f"],
    qidase: {
      psalm: "Ps 132 : 1",
      gospel: "Jhn 14 : 18 – 27"
    },
    evening: ["Nah 1","Act 26","Luk 15"],
    ana: 1,
  },
  {
    gregorianMonth: 7,
    gregorianDay: 3,
    gregorianDate: "Jul 3",
    ethiopianDate: "10/25",
    morning: ["Nah 2","Act 27","Lk 16"],
    qidase: {
      epistle: "Heb  4 : 1 - 14",
      catholicEpistle: "2Pt 1 : 19 - f",
      acts: "Act  7 : 35 - 44",
      psalm: "Ps 117 : 19",
      gospel: "Mat 13 : 36-44"
    },
    evening: ["Nah       3","Act 28","Luk 17"],
    ana: 13,
  },
  {
    gregorianMonth: 7,
    gregorianDay: 4,
    gregorianDate: "Jul 4",
    ethiopianDate: "10/26",
    morning: ["Hab 1","Rom 1","Luk 18"],
    qidase: {
      epistle: "1Cr 12 : 38-f",
      catholicEpistle: "1Jn2 : 27 - 9",
      acts: "Act  9 : 10 - 20",
      psalm: "Ps  7:12-13",
      gospel: "Luk 16 : 19 - f"
    },
    evening: ["Hab      2","Rom 2","Luk 19"],
    ana: 10,
  },
  {
    gregorianMonth: 7,
    gregorianDay: 5,
    gregorianDate: "Jul 5",
    ethiopianDate: "10/27",
    morning: ["Hab 3","Rom 3","Luk 20"],
    qidase: {
      epistle: "Tts 1 : 7 - f",
      catholicEpistle: "1Pt 5 : 1 - 7",
      acts: "Act  7 : 1 - 9",
      psalm: "Ps  67 : 1",
      gospel: "Mat 3 : 23 - 32"
    },
    evening: ["Zep       1","Rom 4","Luk 21"],
    ana: 7,
  },
  {
    gregorianMonth: 7,
    gregorianDay: 6,
    gregorianDate: "Jul 6",
    ethiopianDate: "10/28",
    morning: ["Zep 2","Rom 5","Luk 22: 1-30"],
    qidase: {
      epistle: "1Tm 3 : 13 - f",
      catholicEpistle: "1Jn 4 : 9 - 18",
      acts: "Ac  9 : 20 - 23",
      psalm: "Ps 111:9",
      gospel: "Mat 16 : 24 - f"
    },
    evening: ["Zep       3","Rom 6","Luk 22:31-71"],
    ana: 7,
  },
  {
    gregorianMonth: 7,
    gregorianDay: 7,
    gregorianDate: "Jul 7",
    ethiopianDate: "10/29",
    morning: ["S.F. Rom  7 : 14 - f","1Pt 3 : 7 - 10","Act 19 : 1 - 11"],
    qidase: {
      psalm: "Ps 86 : 2",
      gospel: "Luk  1: 57 - f"
    },
    evening: ["Hag 1","Rom 7","Luk 23"],
    ana: 3,
  },
  {
    gregorianMonth: 7,
    gregorianDay: 8,
    gregorianDate: "Jul 8",
    ethiopianDate: "10/30",
    morning: ["Hag 2","Rom 8:1-16","Luk 24"],
    qidase: {
      epistle: "1Tm 5 : 1 - 18",
      catholicEpistle: "1Pt 3 : 1 - 7",
      acts: "Act  9 : 46 - f",
      psalm: "Ps  77 : 15",
      gospel: "Jhn 20 : 19 - f"
    },
    evening: ["Zec       1","Rom 8:18-39","Jhn 1"],
    ana: 9,
  },
  {
    gregorianMonth: 7,
    gregorianDay: 9,
    gregorianDate: "Jul 9",
    ethiopianDate: "11/1",
    morning: ["Zec 2, 3; Rom 9;","Jhn 2; Ps 18:4","Mrk 13 : 24 - 33"],
    qidase: {
      epistle: "1Cr  9 : 1 - 13",
      catholicEpistle: "Jud  1 : 17 - f",
      acts: "Act  5 : 16 - 33",
      psalm: "Ps  98 : 6",
      gospel: "Mat 19 : 16 - f"
    },
    evening: ["Zec 4","Rom 10","Jhn 3"],
    ana: 1,
  },
  {
    gregorianMonth: 7,
    gregorianDay: 10,
    gregorianDate: "Jul 10",
    ethiopianDate: "11/2",
    morning: ["Zec 5","Rom 11","Jhn 4"],
    qidase: {
      epistle: "Tts  3 : 8 - f",
      catholicEpistle: "1Pt 3: 15 - f",
      acts: "Act 20 : 28 - 31",
      psalm: "Ps 89:14-15",
      gospel: "Mat 18 : 15 -21"
    },
    evening: ["Zec 6","Rom 12","Jhn 5"],
    ana: 11,
  },
  {
    gregorianMonth: 7,
    gregorianDay: 11,
    gregorianDate: "Jul 11",
    ethiopianDate: "11/3",
    morning: ["Zec 7","Rom 13","Jhn 6"],
    qidase: {
      epistle: "Heb 11 : 32 - f",
      catholicEpistle: "2Pt 1 : 19 - f",
      acts: "Act 10 : 37 - f",
      psalm: "Ps 90 : 5-6",
      gospel: "Mt 21 : 33 - f"
    },
    evening: ["Zec       8","Rom 14","Jhn 7"],
    ana: 3,
  },
  {
    gregorianMonth: 7,
    gregorianDay: 12,
    gregorianDate: "Jul 12",
    ethiopianDate: "11/4",
    morning: ["Ps 18 : 4","Jn 15 : 1 - 17","1Ts 4 : 13 - f"],
    qidase: {
      catholicEpistle: "2Pt  1 : 1 - 12",
      acts: "Act 23 : 10 - 16",
      psalm: "Ps  138:17-18",
      gospel: "Jhn 21 : 15 - 20"
    },
    evening: ["Zec       9","Rom 15","Jhn 8"],
    ana: 1,
  },
  {
    gregorianMonth: 7,
    gregorianDay: 13,
    gregorianDate: "Jul 13",
    ethiopianDate: "11/5",
    morning: ["Zec 10","Rom 16","Jhn 9"],
    qidase: {
      epistle: "1Cr 15: 33-45",
      catholicEpistle: "1Jn 2 : 20 - f",
      acts: "Act 16 : 14 -18",
      psalm: "Ps 114: 8",
      gospel: "Mat 24 :15 - 37"
    },
    evening: ["Zec       11","1Cr 1","Jhn 10"],
    ana: 1,
  },
  {
    gregorianMonth: 7,
    gregorianDay: 14,
    gregorianDate: "Jul 14",
    ethiopianDate: "11/6",
    morning: ["Zec 12","1Cr 2;  Jhn 11","Ps 32 : 5-6"],
    qidase: {
      epistle: "Rom  9 : 1 - 6",
      catholicEpistle: "1Jn 4 : 11 - f",
      acts: "Act 11 : 11 - 19",
      psalm: "Ps 26 : 8-9",
      gospel: "Jhn 8 : 51 - f"
    },
    evening: ["Zec      13","1Cr 3","Jhn 12"],
    ana: 12,
  },
  {
    gregorianMonth: 7,
    gregorianDay: 15,
    gregorianDate: "Jul 15",
    ethiopianDate: "11/7",
    morning: ["Zec 14","1Cr 4","Jhn 13"],
    qidase: {
      epistle: "Eph 6 : 10 - 19",
      catholicEpistle: "1Pt 3 : 10 - 15",
      acts: "Act 26 : 12 - 19",
      psalm: "Ps 115 : 6-7",
      gospel: "Mrk 4 : 1 - 24"
    },
    evening: ["Mal       1","1Cr 5","Jhn 14"],
    ana: 5,
  },
  {
    gregorianMonth: 7,
    gregorianDay: 16,
    gregorianDate: "Jul 16",
    ethiopianDate: "11/8",
    morning: ["Mal 2","1Cr 6","Jhn 15"],
    qidase: {
      epistle: "1Tm  3 : 1 - 11",
      catholicEpistle: "1Pt 5 : 1 - f",
      acts: "Act 20 : 28 - 31",
      psalm: "Ps 63 : 6",
      gospel: "Luk 13 : 18 - 23"
    },
    evening: ["Mal       3","1Cr 7","Jhn 16"],
    ana: 5,
  },
  {
    gregorianMonth: 7,
    gregorianDay: 17,
    gregorianDate: "Jul 17",
    ethiopianDate: "11/9",
    morning: ["Mal 4","1Cr 8","Jhn 17"],
    qidase: {
      epistle: "1Cr  1 : 10 - f",
      catholicEpistle: "Jud 1 : 17 - 20",
      acts: "Act 8 : 14 - 18",
      psalm: "Ps 18 : 3",
      gospel: "Jhn  1 : 44 - f"
    },
    evening: ["       Tob       1","1Cr 9","Jhn 18"],
    ana: 1,
  },
  {
    gregorianMonth: 7,
    gregorianDay: 18,
    gregorianDate: "Jul 18",
    ethiopianDate: "11/10",
    morning: ["Tob 2","1Cr 10:1-13","Jhn 19"],
    qidase: {
      epistle: "1Tm 2 : 1 - 9",
      catholicEpistle: "1Pt 4 : 12 - 17",
      acts: "Act 14 : 20- f",
      psalm: "Ps 32 : 1, 2",
      gospel: "Luk  6 : 20 - 27"
    },
    evening: ["Tob       3","1Cr 10:14-33","Jhn 20"],
    ana: 5,
  },
  {
    gregorianMonth: 7,
    gregorianDay: 19,
    gregorianDate: "Jul 19",
    ethiopianDate: "11/11",
    morning: ["Tob 4","1Cr 11: 1- 16","Jhn 21"],
    qidase: {
      epistle: "Rm  9 : 16 - 30",
      catholicEpistle: "Jd  1 : 6 - 14",
      acts: "Act 10 : 3 - 9",
      psalm: "Ps 32:16, 17",
      gospel: "Mat 24 : 15 - 37"
    },
    evening: ["Luk 18 - 1 - 9","1Cr 11:17-34","Mat 1"],
    ana: null,
  },
  {
    gregorianMonth: 7,
    gregorianDay: 20,
    gregorianDate: "Jul 20",
    ethiopianDate: "11/12",
    morning: ["Tob 7","1Cr 12","Mat 2"],
    qidase: {
      epistle: "Rom 8 : 18 - 35",
      catholicEpistle: "1Pt 1 : 13 - f",
      acts: "Act 19 : 11 - 21",
      psalm: "Ps 1: 2,– 3",
      gospel: "Mat 10 : 32 - f"
    },
    evening: ["Tob 8","1Cr 13","Mat 3"],
    ana: 9,
  },
  {
    gregorianMonth: 7,
    gregorianDay: 21,
    gregorianDate: "Jul 21",
    ethiopianDate: "11/13",
    morning: ["Tob 9","1Cr 14:1-25","Mat 4"],
    qidase: {
      epistle: "1Ts  4 : 1 - 13",
      catholicEpistle: "1Pt  5 : 6 - f",
      acts: "Act 14 : 19 - f",
      psalm: "Ps 43 :22, 23",
      gospel: "Mat 13 : 1 - 10"
    },
    evening: ["Tob       10","1Cr 14:26-40","Mat 5"],
    ana: 5,
  },
  {
    gregorianMonth: 7,
    gregorianDay: 22,
    gregorianDate: "Jul 22",
    ethiopianDate: "11/14",
    morning: ["Tob 11","1Cr 15","Mat 6"],
    qidase: {
      epistle: "Rom  1 : 18 - 27",
      catholicEpistle: "Jam 5 : 12 - 17",
      acts: "Act 9 : 22 - 30",
      psalm: "Ps 88: 6, 7",
      gospel: "Mat  4 : 17 - 21"
    },
    evening: ["Tob       12","1Cr 16","Mat 7, 8"],
    ana: 6,
  },
  {
    gregorianMonth: 7,
    gregorianDay: 23,
    gregorianDate: "Jul 23",
    ethiopianDate: "11/15",
    morning: ["Pl  4 : 8 - 15","Jam 2 : 1 - 10","Act 14 : 21 - f"],
    qidase: {
      psalm: "Ps   68:8, 9",
      gospel: "Mrk  8 : 34 - f"
    },
    evening: ["Tob 13, 14","2Cr 1","Mat 9"],
    ana: 5,
  },
  {
    gregorianMonth: 7,
    gregorianDay: 24,
    gregorianDate: "Jul 24",
    ethiopianDate: "11/16",
    morning: ["2Cr 2","Mat 10","Rm  2 : 1 - 12"],
    qidase: {
      catholicEpistle: "1Pt  2 : 1 - 11",
      acts: "Ac 26 : 11 - 19",
      psalm: "Ps 138: 7, 8",
      gospel: "Mt 12 : 38 - 43"
    },
    evening: ["Jdt       2","2Cr 3","Mat 11"],
    ana: 3,
  },
  {
    gregorianMonth: 7,
    gregorianDay: 25,
    gregorianDate: "Jul 25",
    ethiopianDate: "11/17",
    morning: ["Mat12: 1-37","Ps 18:3","Mt 13 : 52 - f"],
    qidase: {
      epistle: "1Cr 15 : 1 - 13",
      catholicEpistle: "Jm 1 : 1 - 13",
      acts: "Ac 15 : 13 - 22",
      psalm: "Ps 25:4, 5",
      gospel: "Mk 6 : 1 - 14"
    },
    evening: ["Jdt       5","2Cr 5","Mat 12:38-50"],
    ana: 1,
  },
  {
    gregorianMonth: 7,
    gregorianDay: 26,
    gregorianDate: "Jul 26",
    ethiopianDate: "11/18",
    morning: ["Mat 13: 1-30","Ps 25:12","Mt 18 : 1 - 12"],
    qidase: {
      epistle: "Hb 11 : 33 - f",
      catholicEpistle: "1Pt 4 : 12 - f",
      acts: "Ac 23 : 10 - 15",
      psalm: "Ps 96: 7",
      gospel: "Mt 11 : 25 – f"
    },
    evening: ["Jdt      7","2Cr 7","Mat 13:31-58"],
    ana: 11,
  },
  {
    gregorianMonth: 7,
    gregorianDay: 27,
    gregorianDate: "Jul 27",
    ethiopianDate: "11/19",
    morning: ["2Cr 8","Mat 14","2Cr 4 : 7 - f"],
    qidase: {
      catholicEpistle: "1Pt 4 : 12 - f",
      acts: "Ac 24 : 17 - 22",
      psalm: "Ps 18: 7, 8",
      gospel: "Jhn 6 : 35 - 48"
    },
    evening: ["Jdt       9","2Cr 9","Mat 15:1-20"],
    ana: 4,
  },
  {
    gregorianMonth: 7,
    gregorianDay: 28,
    gregorianDate: "Jul 28",
    ethiopianDate: "11/20",
    morning: ["Mat 15:21-39","Ps 44: 9","Lk 1 : 39 - 57"],
    qidase: {
      epistle: "Ep 6 : 10 - 19",
      catholicEpistle: "1Jn 5 : 1 - 7",
      acts: "Ac  8 : 26 - f",
      psalm: "Ps 40: 1, 2",
      gospel: "Mt 19 : 1 - 16"
    },
    evening: ["Jdt       11","2Cr 11:1-15","Mat 16"],
    ana: 4,
  },
  {
    gregorianMonth: 7,
    gregorianDay: 29,
    gregorianDate: "Jul 29",
    ethiopianDate: "11/21",
    morning: ["2Cr 11:16-33","Mat 17","2Cr 12 : 1 - 11"],
    qidase: {
      epistle: "Mk 13 : 14 - 21",
      catholicEpistle: "1Pt 1 : 6 - 10",
      acts: "Ac 5 : 26 - 34",
      psalm: "Ps 15:4, 5",
      gospel: "UNCLEAR - please verify"
    },
    evening: ["Mat 18"],
    ana: 7,
  },
  {
    gregorianMonth: 7,
    gregorianDay: 30,
    gregorianDate: "Jul 30",
    ethiopianDate: "11/22",
    morning: ["Mat 19:1-15","Ps 90: 13, 14","Jn 12 : 23 - 30"],
    qidase: {
      epistle: "2Cr 9 : 5 - f",
      catholicEpistle: "Jm 2 : 14 - 20",
      acts: "Ac 16 : 13 - 16",
      psalm: "Ps 102:9, 10",
      gospel: "Jn 19 : 31 - 38"
    },
    evening: ["Jdt      15","Gal. 1","Mat 19:16-30"],
    ana: 10,
  },
  {
    gregorianMonth: 7,
    gregorianDay: 31,
    gregorianDate: "Jul 31",
    ethiopianDate: "11/23",
    morning: ["Gal 2","Mat 20:1-19","2Cr 7 : 8 - 11"],
    qidase: {
      catholicEpistle: "1Pt  5 : 1 - 6",
      acts: "Ac 16 : 35 - f",
      psalm: "Ps 54:13",
      gospel: "Mt 19 : 17 - 22"
    },
    evening: ["TWS       5","Gal 3:1-14","Mat 20:20-34"],
    ana: 5,
  }
];
