/** Auto-generated by scripts/build-lectionary-readings.mjs — do not edit by hand. */
import type { DayReadings } from './types';

export const juneReadings: DayReadings[] = [
  {
    gregorianMonth: 6,
    gregorianDay: 1,
    gregorianDate: "Jun 1",
    ethiopianDate: "9/23",
    morning: ["Lam 2","Heb 12","Mat 13:33-58"],
    qidase: {
      epistle: "Rev 12:13-f",
      catholicEpistle: "1Pt 1 : 8- 13 /",
      acts: "Act  2 : 13 – f",
      psalm: "Ps 77 : 43, 44",
      gospel: "Mat  2 : 10 – 17"
    },
    evening: ["Lam                3","Heb 13","Mat 14"],
    ana: 4,
  },
  {
    gregorianMonth: 6,
    gregorianDay: 2,
    gregorianDate: "Jun 2",
    ethiopianDate: "9/24",
    morning: ["Lam 4","Jam 1","Mat 15:1-20"],
    qidase: {
      epistle: "1Tm  2 : 8 – f",
      catholicEpistle: "1Pt  4 : 12 – f",
      acts: "Act  16 : 8 – 15",
      psalm: "Ps. 80:4, 5",
      gospel: "Mat 15:40-42"
    },
    evening: ["Lam                5","Jam 2","Mat 15:21-39"],
    ana: 4,
  },
  {
    gregorianMonth: 6,
    gregorianDay: 3,
    gregorianDate: "Jun 3",
    ethiopianDate: "9/25",
    morning: ["Ps 18:3,4","Jhn 20:24-f","Rom  8 : 22 – 31"],
    qidase: {
      catholicEpistle: "Jud  1: 1 – f",
      acts: "Act  2 : 1 – 14",
      psalm: "Ps 17:35,36",
      gospel: "Mat 5:1-17"
    },
    evening: ["Eze 1, 2","Jam 3","Mat 16"],
    ana: 1,
  },
  {
    gregorianMonth: 6,
    gregorianDay: 4,
    gregorianDate: "Jun 4",
    ethiopianDate: "9/26",
    morning: ["Eze 3, 4","Jam 4","Mat 17"],
    qidase: {
      epistle: "Rom  6 : 1 – 12",
      catholicEpistle: "1Pt 2 : 21 – f",
      acts: "Act  20 : 28 – 31",
      psalm: "Ps 83 : 6, 7",
      gospel: "Jhn 10:1-22"
    },
    evening: ["Eze 5, 6","Jam 5","Mat 18"],
    ana: 10,
  },
  {
    gregorianMonth: 6,
    gregorianDay: 5,
    gregorianDate: "Jun 5",
    ethiopianDate: "9/27",
    morning: ["Eze 6","1Pt 1:1-12","Mat 19:1-15"],
    qidase: {
      epistle: "1Cr  7 : 29 – f",
      catholicEpistle: "Jam  2 : 19 – f",
      acts: "Act 5 : 1 – 12",
      psalm: "Ps 30 : 18",
      gospel: "Lk 12 : 22 – 39"
    },
    evening: ["Eze 13","1Pt 1:13-25","Mat 19:16-30"],
    ana: 9,
  },
  {
    gregorianMonth: 6,
    gregorianDay: 6,
    gregorianDate: "Jun 6",
    ethiopianDate: "9/28",
    morning: ["Eze 14","1Pt 2","Mat 20:1-19"],
    qidase: {
      epistle: "Gal  4 : 1 – 12 1",
      acts: "Act  12 : 7 – 12",
      psalm: "Ps 17 : 35, 36",
      gospel: "Mat  5 : 1 – 17"
    },
    evening: ["Eze 18","1Pt 3","Mat 20:20-34"],
    ana: 5,
  },
  {
    gregorianMonth: 6,
    gregorianDay: 7,
    gregorianDate: "Jun 7",
    ethiopianDate: "9/29",
    morning: ["Eze 33","1Pt 4:1-11","Mat 21:1-32"],
    qidase: {
      epistle: "1Cr  15 : 1 – 12",
      catholicEpistle: "1Jn  2 : 27 –f",
      acts: "Act  18 : 23 –f",
      psalm: "Ps 83 : 12",
      gospel: "Luk  10 : 1 – 12"
    },
    evening: ["Eze 34","1Pt 4:12-19","Mat 21:33-46"],
    ana: 1,
  },
  {
    gregorianMonth: 6,
    gregorianDay: 8,
    gregorianDate: "Jun 8",
    ethiopianDate: "9/30",
    morning: ["Dan 1","1Pt 5","Mat 22"],
    qidase: {
      epistle: "Heb  11 : 21 – 32",
      catholicEpistle: "1Pt  4 : 12 – f",
      acts: "Act  6 : 9 - 23",
      psalm: "Ps 104 : 20, 21",
      gospel: "Mat  24 : 45 – f"
    },
    evening: ["Dan 2","2Pt 1","Mat 23"],
    ana: 4,
  },
  {
    gregorianMonth: 6,
    gregorianDay: 9,
    gregorianDate: "Jun 9",
    ethiopianDate: "10/1",
    morning: ["Dan 3","2Pt 2","Mat 24:1-35"],
    qidase: {
      epistle: "1Cr  14 : 29 – f",
      catholicEpistle: "Jam   5 : 12 – 16",
      acts: "Act  13 : 24 – 32",
      psalm: "Ps 131 : 1, 2",
      gospel: "Mat 11 : 1 – 16"
    },
    evening: ["Dan 4","2Pt 3","Mat 24:35-51"],
    ana: 4,
  },
  {
    gregorianMonth: 6,
    gregorianDay: 10,
    gregorianDate: "Jun 10",
    ethiopianDate: "10/2",
    morning: ["Dan 5","1Jn 1","Mat 25:1-30"],
    qidase: {
      epistle: "Tts  2 : 1 – 9",
      catholicEpistle: "1Pt  3 : 1 – 7",
      acts: "Act 20 : 16 – 25",
      psalm: "Ps 117:19",
      gospel: "Luk 7:36-f"
    },
    evening: ["Dan 6","1Jn 2","Mat 25:31-46"],
    ana: 5,
  },
  {
    gregorianMonth: 6,
    gregorianDay: 11,
    gregorianDate: "Jun 11",
    ethiopianDate: "10/3",
    morning: ["Dan 7","1Jn 3","Mat 26"],
    qidase: {
      epistle: "1Cr  3 : 9 – 18",
      catholicEpistle: "1Jn  2 : 12 – 20",
      acts: "Act 12 : 18 - f",
      psalm: "Ps 7 : 12, 13",
      gospel: "UNCLEAR - please verify"
    },
    evening: ["Luk  21 : 12 – 29","1Jn 4","Mat 27"],
    ana: null,
  },
  {
    gregorianMonth: 6,
    gregorianDay: 12,
    gregorianDate: "Jun 12",
    ethiopianDate: "10/4",
    morning: ["Dan 9","1Jn 5","Mat 28"],
    qidase: {
      epistle: "2Cr  2 : 12 – f",
      catholicEpistle: "1Jn  3 : 1 – 11",
      acts: "Act 16 : 35 – f",
      psalm: "Ps 67 : 1, 2",
      gospel: "Luk  12 : 8 – 13"
    },
    evening: ["Dan                10","2Jn  1","Mrk 1"],
    ana: 7,
  },
  {
    gregorianMonth: 6,
    gregorianDay: 13,
    gregorianDate: "Jun 13",
    ethiopianDate: "10/5",
    morning: ["Dan 11","2Jn 1","Mrk 2"],
    qidase: {
      epistle: "2Cr  9 : 13 – f;",
      catholicEpistle: "Jam  1 : 12 – 19;",
      acts: "Act  5 : 27 – f",
      psalm: "Ps 111 : 9",
      gospel: "Luk  12 : 32 – 41"
    },
    evening: ["Dan 12","Jud 1","Mrk 3"],
    ana: 5,
  },
  {
    gregorianMonth: 6,
    gregorianDay: 14,
    gregorianDate: "Jun 14",
    ethiopianDate: "10/6",
    morning: ["Hos 1","Act 1","Mrk 4"],
    qidase: {
      epistle: "2Cr  6 : 11 – f;",
      catholicEpistle: "1Pt 1 : 7 – 10",
      acts: "Ac 12 : 10 – 21",
      psalm: "Ps 86 : 1, 3",
      gospel: "Mt 17: 14 – 22"
    },
    evening: ["Hos 2, 3","Act 2:1-21","Mrk 5"],
    ana: 4,
  },
  {
    gregorianMonth: 6,
    gregorianDay: 15,
    gregorianDate: "Jun 15",
    ethiopianDate: "10/7",
    morning: ["Hos 4","Act 2:22-46","Mrk 6:1-13"],
    qidase: {
      epistle: "Eph  2 : 13 – f",
      catholicEpistle: "1Pt  1 : 10 – 13",
      acts: "Act 7 : 44 – 51",
      psalm: "Ps 77 : 15, 16",
      gospel: "Jn  4 : 1 – 15"
    },
    evening: ["Hos 5, 6","Act 3","Mrk 6:14-46"],
    ana: 4,
  },
  {
    gregorianMonth: 6,
    gregorianDay: 16,
    gregorianDate: "Jun 16",
    ethiopianDate: "10/8",
    morning: ["Hos 7","Act 4","Mrk 7"],
    qidase: {
      epistle: "Heb  11 : 32 – f",
      catholicEpistle: "2Pt  3 : 1 – 7",
      acts: "Act  13 : 17 – 24",
      psalm: "Ps 98 : 6, 7",
      gospel: "Mat 10 : 32 – f"
    },
    evening: ["Hos 8","Act 5:1-16","Mrk 8"],
    ana: 4,
  },
  {
    gregorianMonth: 6,
    gregorianDay: 17,
    gregorianDate: "Jun 17",
    ethiopianDate: "10/9",
    morning: ["Hos 9","Act 5:17-42","Mrk 9:1-32"],
    qidase: {
      epistle: "1Cr  7: 25 – 35",
      catholicEpistle: "1Jn  1 : 4 – f",
      acts: "Act 15:30- 37",
      psalm: "Ps 89 : 14, 15",
      gospel: "Mat  11 : 20 - f"
    },
    evening: ["Hos 10","Act 6","Mrk 9:33-50"],
    ana: 7,
  },
  {
    gregorianMonth: 6,
    gregorianDay: 18,
    gregorianDate: "Jun 18",
    ethiopianDate: "10/10",
    morning: ["Ps 15: 4, 5; Luk","22:31 - f","Hos 11"],
    qidase: {
      epistle: "2Cr  5 : 11 – 34",
      catholicEpistle: "1Pt  5 : 7 – 11",
      acts: "Act  17 : 35 – f",
      psalm: "Ps 90 : 5, 6",
      gospel: "Mat  10 : 17 – 32"
    },
    evening: ["Hos 12","Act 7:35-60","Mrk 11"],
    ana: 2,
  },
  {
    gregorianMonth: 6,
    gregorianDay: 19,
    gregorianDate: "Jun 19",
    ethiopianDate: "10/11",
    morning: ["Ps 33 : 7","Mat  24 : 30 - 36","Eph  1 : 13 – f"],
    qidase: {
      catholicEpistle: "Jud  1 : 9 – 14",
      acts: "Act  1 : 10 – 12",
      psalm: "Ps 48 : 10",
      gospel: "Mat 25 : 14 – 31"
    },
    evening: ["Hos              13","Act 8: 1-25","Mrk 12:1-17"],
    ana: 13,
  },
  {
    gregorianMonth: 6,
    gregorianDay: 20,
    gregorianDate: "Jun 20",
    ethiopianDate: "10/12",
    morning: ["Hos 14","Act 8:26-40","Mrk 12:18-34"],
    qidase: {
      epistle: "1Tm  6 : 7 – 20",
      catholicEpistle: "1Pt  1 : 13 – f",
      acts: "Ac  8 : 20 – 26",
      psalm: "Ps 36 : 21, 22",
      gospel: "Luk  18 : 18 – 23"
    },
    evening: ["Joe                1","Act 9","Mrk 13"],
    ana: 1,
  },
  {
    gregorianMonth: 6,
    gregorianDay: 21,
    gregorianDate: "Jun 21",
    ethiopianDate: "10/13",
    morning: ["Joe 2","Act 10:1-29","Mrk 14"],
    qidase: {
      epistle: "Heb  12 : 7 – 15",
      catholicEpistle: "2Pt  2 : 9 – 14",
      acts: "Act  27 : 1 – 7",
      psalm: "Ps 78 : 10, 11",
      gospel: "Luk  21 : 12 – 19"
    },
    evening: ["Joe                3;","Act 10:30-48","Mrk 15"],
    ana: 5,
  },
  {
    gregorianMonth: 6,
    gregorianDay: 22,
    gregorianDate: "Jun 22",
    ethiopianDate: "10/14",
    morning: ["Amo 1","Act 11","Mrk 16"],
    qidase: {
      epistle: "Eph  7 : 10 – f",
      catholicEpistle: "1Jn  4 : 17 – f",
      acts: "Act  25 : 1 – 13",
      psalm: "Ps 88 : 19",
      gospel: "Mat  13 : 44 – 51"
    },
    evening: ["Amo                2","Act 12","Luk 1:1-38"],
    ana: 3,
  },
  {
    gregorianMonth: 6,
    gregorianDay: 23,
    gregorianDate: "Jun 23",
    ethiopianDate: "10/15",
    morning: ["Amo 3","Act 13:1-15","Luk 1:39-f"],
    qidase: {
      epistle: "Eph  6 : 14 – f",
      catholicEpistle: "1Pt  3 : 10 – 15",
      acts: "Act  3 : 1 – 12",
      psalm: "Ps 138 : 17, 18",
      gospel: "Mt  2 : 19 – f"
    },
    evening: ["Amo                4;","Act 13:16-52","Luk 2"],
    ana: 4,
  },
  {
    gregorianMonth: 6,
    gregorianDay: 24,
    gregorianDate: "Jun 24",
    ethiopianDate: "10/16",
    morning: ["Amo 5","Act 14","Luk 3"],
    qidase: {
      epistle: "2Tm  1 : 1 – 10",
      catholicEpistle: "Jam  5 : 14 – 17",
      acts: "Act  13 : 44 – 49",
      psalm: "Ps 1 : 4, 5",
      gospel: "Luk  6 : 20 - 24"
    },
    evening: ["Amo                6","Act 15:1- 12","Luk 4"],
    ana: 5,
  },
  {
    gregorianMonth: 6,
    gregorianDay: 25,
    gregorianDate: "Jun 25",
    ethiopianDate: "10/17",
    morning: ["Amo 7","Act 15:13-41","Luk 5"],
    qidase: {
      epistle: "2Tm  3 : 1 – f",
      catholicEpistle: "2Pt  2 : 9 – 14",
      acts: "Act  17 : 5 – 13",
      psalm: "Ps 54 : 17",
      gospel: "Mat 18 : 15 - 19"
    },
    evening: ["Amo                8","Act 16:1-15","Luk 6"],
    ana: 7,
  },
  {
    gregorianMonth: 6,
    gregorianDay: 26,
    gregorianDate: "Jun 26",
    ethiopianDate: "10/18",
    morning: ["Amo 9","Act 16:16-40","Luk 7"],
    qidase: {
      epistle: "1Th  1 : 1 – 8",
      catholicEpistle: "1Jn  2 : 14 – 20",
      acts: "Act 19 : 11 – 18",
      psalm: "Ps 78 : 10",
      gospel: "Mt 24 : 8 – 13"
    },
    evening: ["Oba 1","Act 17","Luk 8"],
    ana: 11,
  },
  {
    gregorianMonth: 6,
    gregorianDay: 27,
    gregorianDate: "Jun 27",
    ethiopianDate: "10/19",
    morning: ["Jon 1;","Act 18","Luk 9:1-27"],
    qidase: {
      epistle: "2Tm  3 : 1 – 8",
      acts: "Act  13 : 38 – 44",
      psalm: "Ps 65 : 5, 6",
      gospel: "Lk  4 : 24 – 38"
    },
    evening: ["Jon 2, 3;","Act 19:1-20","Luk 9:28-62"],
    ana: 4,
  },
  {
    gregorianMonth: 6,
    gregorianDay: 28,
    gregorianDate: "Jun 28",
    ethiopianDate: "10/20",
    morning: ["Ps 131 : 7, 8; Lk  1 :","Jon 4;  Act 19:21-40","Luk 10:1-24"],
    qidase: {
      epistle: "Eph  2  : 13 – f",
      catholicEpistle: "1Pt  2 : 4 – 11",
      acts: "Act  1 : 12 – 15",
      psalm: "Ps 45 :4, 5",
      gospel: "Mat  16 : 13 - 20"
    },
    evening: ["Mic 1;","Act 20","Luk 10:25-42"],
    ana: 2,
  },
  {
    gregorianMonth: 6,
    gregorianDay: 29,
    gregorianDate: "Jun 29",
    ethiopianDate: "10/21",
    morning: ["Mic 2","Act 21:1-16","Luk 11:1-26"],
    qidase: {
      epistle: "1Cr  5 : 6 – f",
      catholicEpistle: "Jam  5 : 14 – f",
      acts: "Act  13 : 44 – f",
      psalm: "Ps 67 : 25, 26",
      gospel: "Mat  5 : 39 – f"
    },
    evening: ["Mic 3;","Act 21:17-40","Luk 11:26-54"],
    ana: 2,
  },
  {
    gregorianMonth: 6,
    gregorianDay: 30,
    gregorianDate: "Jun 30",
    ethiopianDate: "10/22",
    morning: ["Ps 71 : 1, 2","Mat 12 : 38 – 43","Mic 4"],
    qidase: {
      epistle: "Rom 13 : 1 – 11",
      catholicEpistle: "1Pt 2 : 13 – f",
      acts: "Act  7 : 44 – 54",
      psalm: "Ps 31 : 5",
      gospel: "Mat 11 : 12 – f"
    },
    evening: ["Mic 5","Act 23","Luk 12:1-16"],
    ana: 5,
  }
];
