/** Auto-generated by scripts/build-lectionary-readings.mjs — do not edit by hand. */
import type { DayReadings } from './types';

export const marchReadings: DayReadings[] = [
  {
    gregorianMonth: 3,
    gregorianDay: 1,
    gregorianDate: "Mar 1",
    ethiopianDate: "6/21",
    morning: ["2Kg 15","Heb 10 : 1 - 18","Mat 19"],
    qidase: {
      epistle: "1Cr 12 : 1 - 12",
      catholicEpistle: "1Pt 1 : 6 -10",
      acts: "Act 16 :16 - 19",
      psalm: "Ps 142 : 7, 8",
      gospel: "Luk 13 : 10 - 18"
    },
    evening: ["2Kg            16","Heb 10 : 19 - 39","Mat 20"],
    ana: 5,
  },
  {
    gregorianMonth: 3,
    gregorianDay: 2,
    gregorianDate: "Mar 2",
    ethiopianDate: "6/22",
    morning: ["2Kg 17","Heb 11 : 1 - 16","Mat 21"],
    qidase: {
      epistle: "2Cr 4 : 7 - f",
      catholicEpistle: "1Pt 4 : 12 - f",
      acts: "Act 9 : 23 - 32",
      psalm: "Ps 79 : 6, 7",
      gospel: "Jhn: 16 : 1 - 7"
    },
    evening: ["2Kg            18","Heb 11 : 17 - 40","Mat 22"],
    ana: 3,
  },
  {
    gregorianMonth: 3,
    gregorianDay: 3,
    gregorianDate: "Mar 3",
    ethiopianDate: "6/23",
    morning: ["2Kg 19","Heb 12 : 1- 17","Mat 23"],
    qidase: {
      epistle: "Rom 13 : 1 - 11",
      catholicEpistle: "1Pt 2 : 16 - f",
      acts: "Act 19 : 11 - 21",
      psalm: "Ps 118 : 50, 52",
      gospel: "Mrk 1 : 23 - 29"
    },
    evening: ["2Kg            20","Heb 12 : 18 - 29","Mat 24"],
    ana: 5,
  },
  {
    gregorianMonth: 3,
    gregorianDay: 4,
    gregorianDate: "Mar 4",
    ethiopianDate: "6/24",
    morning: ["2Kg 21","Heb 13","Mat 25"],
    qidase: {
      epistle: "Plm 1 : 1 - 13",
      catholicEpistle: "2Pt 1 : 10 - 15",
      acts: "Act 9 : 1 - 10",
      psalm: "Ps 64 : 4,  5",
      gospel: "Luk  9 : 12 - 17"
    },
    evening: ["2Kg            22","Jam 1","Mat 26"],
    ana: 5,
  },
  {
    gregorianMonth: 3,
    gregorianDay: 5,
    gregorianDate: "Mar 5",
    ethiopianDate: "6/25",
    morning: ["2Kg 23","Jam 2","Mat 27"],
    qidase: {
      epistle: "Rom 9 : 24 - 30",
      catholicEpistle: "2Pt 1 : 19 - f",
      acts: "Act 3 : 17 - f",
      psalm: "Ps 78 : 10, 11",
      gospel: "Mat 10 : 36 - f"
    },
    evening: ["2Kg            24","Jam 3","Mat 28"],
    ana: 3,
  },
  {
    gregorianMonth: 3,
    gregorianDay: 6,
    gregorianDate: "Mar 6",
    ethiopianDate: "6/26",
    morning: ["2Kg 25","Jam 4","Mrk 1"],
    qidase: {
      epistle: "Rom  6 : 5 - 12",
      catholicEpistle: "1Pt 2 : 21 - f",
      acts: "Act 10 : 36 - 44",
      psalm: "Ps 73 : 12, 13",
      gospel: "Jhn 19 : 16 - 25"
    },
    evening: ["Ezr          1","Jam 5","Mrk 2"],
    ana: 10,
  },
  {
    gregorianMonth: 3,
    gregorianDay: 7,
    gregorianDate: "Mar 7",
    ethiopianDate: "6/27",
    morning: ["Ezr 2, 3","1Pt 1:1-12","Mrk 3"],
    qidase: {
      epistle: "Heb  14 : 8 - 22",
      catholicEpistle: "Jam  3 : 1 - f",
      acts: "Act 7 : 1 - 16",
      psalm: "Ps 104 : 9",
      gospel: "Luk 20 : 37 - f"
    },
    evening: ["Ezr            4","1Pt 1:13-25","Mrk 4"],
    ana: 4,
  },
  {
    gregorianMonth: 3,
    gregorianDay: 8,
    gregorianDate: "Mar 8",
    ethiopianDate: "6/28",
    morning: ["Ezr 5","1Pt 2","Mrk 5"],
    qidase: {
      epistle: "Rom 8 : 3 - 12",
      catholicEpistle: "1Jn  4 : 7 - 18",
      acts: "Act 9 : 20 - 32",
      psalm: "Ps 2 : 7, 8",
      gospel: "Luk 2 : 1 - 21"
    },
    evening: ["Ezr            6","1Pt 3","Mrk 6"],
    ana: 2,
  },
  {
    gregorianMonth: 3,
    gregorianDay: 9,
    gregorianDate: "Mar 9",
    ethiopianDate: "6/29",
    morning: ["Ezr 7, 8","1Pt 4:1-11","Mrk 7"],
    qidase: {
      epistle: "1Cr 4 : 7 - f",
      catholicEpistle: "2Pt 1 : 19 - f",
      acts: "Act 13 : 24 - 32",
      psalm: "Ps 117 : 18, 19",
      gospel: "Mrk  6 : 21 - 34"
    },
    evening: ["Ezr 9, 10","1Pt 4:12-19","Mrk  8"],
    ana: 3,
  },
  {
    gregorianMonth: 3,
    gregorianDay: 10,
    gregorianDate: "Mar 10",
    ethiopianDate: "6/30",
    morning: ["Neh 1","1Pt 5","Mrk 9"],
    qidase: {
      epistle: "2Tm 2 : 1 - 17",
      catholicEpistle: "Jam 1 : 5 - 15",
      acts: "Act 15 : 1 - 13",
      psalm: "Ps 15 : 5,  6",
      gospel: "Mat 10 : 17 - 26"
    },
    evening: ["Neh            2","2Pt 1","Mrk 10"],
    ana: 5,
  },
  {
    gregorianMonth: 3,
    gregorianDay: 11,
    gregorianDate: "Mar 11",
    ethiopianDate: "7/1",
    morning: ["Neh 3, 4","2Pt 2","Mrk 11"],
    qidase: {
      epistle: "Rom 1 : 8 - 18",
      catholicEpistle: "1Jn 1 : 1 - f",
      acts: "Act 8 : 14 - 26",
      psalm: "Ps 37 : 30, 31",
      gospel: "Mat 5 : 20 - 31"
    },
    evening: ["Neh            5","2Pt 3","Mrk 12"],
    ana: 7,
  },
  {
    gregorianMonth: 3,
    gregorianDay: 12,
    gregorianDate: "Mar 12",
    ethiopianDate: "7/2",
    morning: ["Neh 6","1Jn 1","Mrk 13"],
    qidase: {
      epistle: "2Ts 1 : 3 - f",
      catholicEpistle: "2Pt 3 : 14 - f",
      acts: "Act 4 : 13 - 27",
      psalm: "Ps 61 : 4",
      gospel: "Mat 12 : 25-38"
    },
    evening: ["Neh 7, 8","1Jn 2","Mrk 14"],
    ana: 5,
  },
  {
    gregorianMonth: 3,
    gregorianDay: 13,
    gregorianDate: "Mar 13",
    ethiopianDate: "7/3",
    morning: ["Neh 9, 10","1Jn 3","Mrk 15"],
    qidase: {
      epistle: "Pl 3 : 1 - f",
      catholicEpistle: "2Jn 1 : 1 - f",
      acts: "Act 20 : 1 - 7",
      psalm: "Ps 25 : 5, 6",
      gospel: "Luk 22 : 1 - 24"
    },
    evening: ["Neh 11, 12","1Jn 4","Mrk 16"],
    ana: 13,
  },
  {
    gregorianMonth: 3,
    gregorianDay: 14,
    gregorianDate: "Mar 14",
    ethiopianDate: "7/4",
    morning: ["Neh 13","1Jn 5","Luk 1"],
    qidase: {
      epistle: "Rom 14 : 1 - f",
      catholicEpistle: "1Pt 4 : 1 - 12",
      acts: "Act 17 : 19 - f",
      psalm: "Ps 115 : 6, 7",
      gospel: "Mat 6 : 19 - f"
    },
    evening: ["Est            1","2Jn 1","Luk 2"],
    ana: 5,
  },
  {
    gregorianMonth: 3,
    gregorianDay: 15,
    gregorianDate: "Mar 15",
    ethiopianDate: "7/5",
    morning: ["Est 2","3Jn 1","Luk 3"],
    qidase: {
      epistle: "1Cr 3 : 9 - f",
      catholicEpistle: "1Pt 5 : 5 - 12",
      acts: "Act 2 : 38 - f",
      psalm: "Ps 1 : 1",
      gospel: "Luk 15 : 11 - f"
    },
    evening: ["Est            3","Jud 1","Luk 4"],
    ana: 5,
  },
  {
    gregorianMonth: 3,
    gregorianDay: 16,
    gregorianDate: "Mar 16",
    ethiopianDate: "7/6",
    morning: ["Est 4","Act 1","Luk 5"],
    qidase: {
      epistle: "Rom  8 : 31 - f",
      catholicEpistle: "1Jn 1 : 14 - 20",
      acts: "Act 5 : 17 - 34",
      psalm: "Ps 110 : 10",
      gospel: "Mat 10 : 28 - f"
    },
    evening: ["Est            5","Act 2 : 1-21","Luk 6"],
    ana: 3,
  },
  {
    gregorianMonth: 3,
    gregorianDay: 17,
    gregorianDate: "Mar 17",
    ethiopianDate: "7/7",
    morning: ["Ps 26 : 1, 2"," Luk 18 : 35 - f","Rm 2 : 1 - 17"],
    qidase: {
      catholicEpistle: "Jud 1 : 17 - fs",
      acts: "Act 1 : 15 - f",
      psalm: "Ps 18 : 3, 4",
      gospel: "Mt 10 : 1 - 16"
    },
    evening: ["Est            6","Acts 2 : 22-47","Luk 7"],
    ana: 1,
  },
  {
    gregorianMonth: 3,
    gregorianDay: 18,
    gregorianDate: "Mar 18",
    ethiopianDate: "7/8",
    morning: ["Est 7","Acts 3","Luk 8"],
    qidase: {
      epistle: "Gal 1 : 1 - 11",
      catholicEpistle: "Jam 2 : 1 - 14",
      acts: "Act 4 : 13 - 19",
      psalm: "Ps 33 : 11, 12",
      gospel: "Mrk 1 : 23 - 29"
    },
    evening: ["Est          8","Acts 4","Luk 9"],
    ana: 11,
  },
  {
    gregorianMonth: 3,
    gregorianDay: 19,
    gregorianDate: "Mar 19",
    ethiopianDate: "7/9",
    morning: ["Ps 83:6b","Mat 5 : 1 - 16","Gal 6 : 1 - f"],
    qidase: {
      catholicEpistle: "Jam 4 : 1 - 11",
      acts: "Act   4 : 1 - 13",
      psalm: "Ps 59 : 3, 5",
      gospel: "Mat 16 : 24 - f"
    },
    evening: ["Est 9, 10","Acts 5 : 1-16","Luk 10"],
    ana: 10,
  },
  {
    gregorianMonth: 3,
    gregorianDay: 20,
    gregorianDate: "Mar 20",
    ethiopianDate: "7/10",
    morning: ["Job 1","Acts 5 : 17-42","Luk 11"],
    qidase: {
      epistle: "Tts 1 : 1 - 6",
      catholicEpistle: "Jam 2 : 14 - f",
      acts: "Act 27 : 22 - 27",
      psalm: "Ps 25 : 1",
      gospel: "Mat 18 : 1 - 12"
    },
    evening: ["Job            2","Acts 6","Luk 12"],
    ana: 7,
  },
  {
    gregorianMonth: 3,
    gregorianDay: 21,
    gregorianDate: "Mar 21",
    ethiopianDate: "7/11",
    morning: ["Job 3","Acts 7 : 1-34","Luk 13"],
    qidase: {
      epistle: "1Cr 7 : 1 - 8",
      catholicEpistle: "2Pt 2 : 9 - f",
      acts: "Act  27 : 1 - 11",
      psalm: "Ps 33 : 7, 8",
      gospel: "Mat 18 : 10 - 21"
    },
    evening: ["Job          4","Acts 7 : 35-60","Luk 14"],
    ana: 12,
  },
  {
    gregorianMonth: 3,
    gregorianDay: 22,
    gregorianDate: "Mar 22",
    ethiopianDate: "7/12",
    morning: ["Job 5","Acts 8 : 1-25","Luk 15"],
    qidase: {
      epistle: "1Tm 3 : 1 - 11",
      catholicEpistle: "2Pt 1 : 1 - 12",
      acts: "Act 17 : 5 - 13",
      psalm: "Ps 33 : 19",
      gospel: "Mat 5 : 1 - 17"
    },
    evening: ["Job            6","Acts 8 : 26-40","Luk 16"],
    ana: 7,
  },
  {
    gregorianMonth: 3,
    gregorianDay: 23,
    gregorianDate: "Mar 23",
    ethiopianDate: "7/13",
    morning: ["Job 7","Acts 9","Luk 17"],
    qidase: {
      epistle: "1Cr 6 : 9 - f",
      catholicEpistle: "Jam 4 : 6 - f",
      acts: "Act 6 : 1 - 8",
      psalm: "Ps 83 : 6, 7",
      gospel: "Mat 7 : 1 - 15"
    },
    evening: ["Job            8","Acts 10 : 1-29","Luk 18"],
    ana: 7,
  },
  {
    gregorianMonth: 3,
    gregorianDay: 24,
    gregorianDate: "Mar 24",
    ethiopianDate: "7/14",
    morning: ["Job 9","Acts 10 : 30-48","Luk 19"],
    qidase: {
      epistle: "Eph 5 : 21 - f",
      catholicEpistle: "1Jn 5 : 14 - f",
      acts: "Act 26 : 1 - f",
      psalm: "Ps 36 : 29, 30",
      gospel: "Luk 10 : 19 - 25"
    },
    evening: ["Job            10","Acts 11","Luk 20"],
    ana: 7,
  },
  {
    gregorianMonth: 3,
    gregorianDay: 25,
    gregorianDate: "Mar 25",
    ethiopianDate: "7/15",
    morning: ["Job 11","Acts 12","Luk 21"],
    qidase: {
      epistle: "1Tm 4 : 1 - f",
      catholicEpistle: "2Pt  1 : 11- 19",
      acts: "Act 11 : 23 - 26",
      psalm: "Ps 67 : 30, 31",
      gospel: "Luk 14 : 23 - f"
    },
    evening: ["Job            12","Acts 13 : 1-15","Luk 22"],
    ana: 5,
  },
  {
    gregorianMonth: 3,
    gregorianDay: 26,
    gregorianDate: "Mar 26",
    ethiopianDate: "7/16",
    morning: ["Job 13","Acts 13 : 16-42","Luk 23"],
    qidase: {
      epistle: "Rom 15 : 19 - f",
      catholicEpistle: "Jam 5 : 14 - f",
      acts: "Act 2 : 22 - 25",
      psalm: "Ps 3 : 4, 5",
      gospel: "Jhn 11 : 1 - 16"
    },
    evening: ["Job            14","Acts 14","Luk 24"],
    ana: 2,
  },
  {
    gregorianMonth: 3,
    gregorianDay: 27,
    gregorianDate: "Mar 27",
    ethiopianDate: "7/17",
    morning: ["Job 15","Acts 15 : 1-12","Jhn 1"],
    qidase: {
      epistle: "1Cr 16 : 1 - 12",
      catholicEpistle: "1Pt  2 :  1 - 11",
      acts: "Act 22 : 24 - f",
      psalm: "Ps 118 : 1, 2",
      gospel: "Luk 18 : 18 - 23"
    },
    evening: ["Job            16","Acts 15 : 13-41","Jhn 2"],
    ana: 3,
  },
  {
    gregorianMonth: 3,
    gregorianDay: 28,
    gregorianDate: "Mar 28",
    ethiopianDate: "7/18",
    morning: ["Job 17","Acts 16 : 1-15","Jhn 3"],
    qidase: {
      epistle: "Rom 16 : 3 - 16",
      catholicEpistle: "1Pt 3 : 7 - 15",
      acts: "Act 22 : 22 - f",
      psalm: "Ps 78 : 10, 11",
      gospel: "Luk 10 : 1 - 21"
    },
    evening: ["Job            18","Acts 16 : 16-40","Jhn 4"],
    ana: 1,
  },
  {
    gregorianMonth: 3,
    gregorianDay: 29,
    gregorianDate: "Mar 29",
    ethiopianDate: "7/19",
    morning: ["Job 19","Acts 17","Jhn 5"],
    qidase: {
      epistle: "Phi 1 : 12 - 18",
      catholicEpistle: "Jam 5 : 1 - 8",
      acts: "Act 24 : 10 - 22",
      psalm: "Ps 43 : 22, 23",
      gospel: "Jhn 11 : 17 - 47"
    },
    evening: ["Job            20","Acts 18","Jhn 6"],
    ana: 3,
  },
  {
    gregorianMonth: 3,
    gregorianDay: 30,
    gregorianDate: "Mar 30",
    ethiopianDate: "7/20",
    morning: ["Job 21","Acts 19 : 1-20","Jhn 7"],
    qidase: {
      epistle: "Eph 2 : 1 - f",
      catholicEpistle: "2Jn 1 : 1 - 8",
      acts: "Act 7 : 44 - 51",
      psalm: "Ps 49 : 9, 10",
      gospel: "Luk 1 : 27 - 39"
    },
    evening: ["Job            22","Acts 19 : 21-40","Jhn 8"],
    ana: 2,
  },
  {
    gregorianMonth: 3,
    gregorianDay: 31,
    gregorianDate: "Mar 31",
    ethiopianDate: "7/21",
    morning: ["Job 23","Acts 20","Jhn 9"],
    qidase: {
      epistle: "1Cr 4 : 1 – 7",
      catholicEpistle: "2Jn 1 : 8  - f",
      acts: "Act 5 : 1 - 17",
      psalm: "Ps 8 : 2",
      gospel: "Mat 21 : 1 - 18"
    },
    evening: ["Job          24","Acts 21 : 1-16","Jhn 10"],
    ana: 11,
  }
];
