/** Auto-generated by scripts/build-lectionary-readings.mjs — do not edit by hand. */
import type { DayReadings } from './types';

export const mayReadings: DayReadings[] = [
  {
    gregorianMonth: 5,
    gregorianDay: 1,
    gregorianDate: "May 1",
    ethiopianDate: "8/22",
    morning: ["Ps 109 :5 -6","Lk  12 : 1 - 13","2Cr 1 : 1 - 12"],
    qidase: {
      catholicEpistle: "1Pt  1 : 6 - 10",
      acts: "Act  14 : 1 - 23",
      psalm: "Ps 78 : 10 - 11",
      gospel: "UNCLEAR - please verify"
    },
    evening: ["Mat  10 : 16 - 34","2Cr 12","Luk 3"],
    ana: null,
  },
  {
    gregorianMonth: 5,
    gregorianDay: 2,
    gregorianDate: "May 2",
    ethiopianDate: "8/23",
    morning: ["Pro 10","2Cr 13","Luk 4"],
    qidase: {
      epistle: "Heb 12 : 1 - 12",
      catholicEpistle: "2Pt  3: 16 - f",
      acts: "Act 17 27 - f",
      psalm: "Ps 49 : 3 - 5",
      gospel: "Mat  21 : 28 - 33"
    },
    evening: ["Pro            11","Gal 1","Luk 5"],
    ana: 7,
  },
  {
    gregorianMonth: 5,
    gregorianDay: 3,
    gregorianDate: "May 3",
    ethiopianDate: "8/24",
    morning: ["Pro 12","Gal 2","Luk 6"],
    qidase: {
      epistle: "1Cr  10 : 12 - 22",
      catholicEpistle: "1Jn   4 : 4 - 18",
      acts: "Act 8 : 1 - 13",
      psalm: "Ps 114 : 5 - 6",
      gospel: "Luk  18 :  1 - 9"
    },
    evening: ["Jer            2","Gal 3:1-14","Luk 7"],
    ana: 3,
  },
  {
    gregorianMonth: 5,
    gregorianDay: 4,
    gregorianDate: "May 4",
    ethiopianDate: "8/25",
    morning: ["Jer 3","Gal 3:15-29","Luk 8"],
    qidase: {
      epistle: "Eph  5 :  1 - 15",
      catholicEpistle: "1Jn  3 : 7 - 13",
      acts: "Act  17 : 16 - 30",
      psalm: "Ps 72 : 23 - 24",
      gospel: "Mrk  13 : 9 - 14"
    },
    evening: ["Jer            4","Gal 4","Luk 9, 10"],
    ana: 7,
  },
  {
    gregorianMonth: 5,
    gregorianDay: 5,
    gregorianDate: "May 5",
    ethiopianDate: "8/26",
    morning: ["Ps 39 : 7 - 8","Mrk 15 : 1 - 42","2Cr 8 : 4 - 10"],
    qidase: {
      catholicEpistle: "1Pt 2 : 21 - f",
      acts: "Act 5 : 29 - 34",
      psalm: "Ps 55 : 3 - 5",
      gospel: "Mat 10 : 16 - 24"
    },
    evening: ["Jer            5","Gal 5","Luk 11"],
    ana: 3,
  },
  {
    gregorianMonth: 5,
    gregorianDay: 6,
    gregorianDate: "May 6",
    ethiopianDate: "8/27",
    morning: ["Jer 6","Gal 6","Luk 12"],
    qidase: {
      epistle: "Rom  4 : 1 - 14",
      catholicEpistle: "Jam 2 : 19 - f",
      acts: "Act  7 : 1 - 9",
      psalm: "Ps 140 : 9",
      gospel: "Luk  12 : 8 - 17"
    },
    evening: ["Jer            7","Eph 1","Luk 13"],
    ana: 5,
  },
  {
    gregorianMonth: 5,
    gregorianDay: 7,
    gregorianDate: "May 7",
    ethiopianDate: "8/28",
    morning: ["Jer 8","Eph 2","Luk 14"],
    qidase: {
      epistle: "Col.  4 : 10 - 14",
      catholicEpistle: "1Jn 4 : 9 - 18",
      acts: "Act 13 : 4 - 16",
      psalm: "Ps 18 : 3 - 4",
      gospel: "Luk  10 : 1 - 12"
    },
    evening: ["Jer          9","Eph 3","Luk 15"],
    ana: 13,
  },
  {
    gregorianMonth: 5,
    gregorianDay: 8,
    gregorianDate: "May 8",
    ethiopianDate: "8/29",
    morning: ["Ps 115 : 6 - 7","Luk  10 : 1 - 12","2Tm  4 : 1 - 20"],
    qidase: {
      catholicEpistle: "1Pt  5 : 12 - f",
      acts: "Act 15 : 36 - f",
      psalm: "Ps 83 : 6 - 7",
      gospel: "Jhn 10 : 1 - 19"
    },
    evening: ["Jer            10","Eph 4","Luk 16"],
    ana: 1,
  },
  {
    gregorianMonth: 5,
    gregorianDay: 9,
    gregorianDate: "May 9",
    ethiopianDate: "8/30",
    morning: ["Ps 44 : 12 - 13","Mat 1 : 1 - 18","Gal  4 : 1 - 13"],
    qidase: {
      catholicEpistle: "1Pt 1 : 8 - 13",
      acts: "Act  7 : 44 - 51",
      psalm: "Ps 86 : 1 - 2",
      gospel: "Luk  1 :  39 - 57"
    },
    evening: ["Jer            11","Eph 5","Luk 17"],
    ana: 4,
  },
  {
    gregorianMonth: 5,
    gregorianDay: 10,
    gregorianDate: "May 10",
    ethiopianDate: "9/1",
    morning: ["Jer 12","Eph 6","Luk 18"],
    qidase: {
      epistle: "1Cr  4 : 8 - 14",
      catholicEpistle: "Jam  5 : 10 - 12",
      acts: "Act  14 : 21 - f",
      psalm: "Ps 91 : 12 - 13",
      gospel: "Mt  7 : 21 - f"
    },
    evening: ["Jer          13","Phl 1","Luk 19"],
    ana: 11,
  },
  {
    gregorianMonth: 5,
    gregorianDay: 11,
    gregorianDate: "May 11",
    ethiopianDate: "9/2",
    morning: ["Jer 14","Phl 2","Luk 20"],
    qidase: {
      epistle: "Rom 16 : 21 - f",
      catholicEpistle: "1Jn 2 : 27 - f",
      acts: "Act 17 P 5 - 13",
      psalm: "Ps 18 : 3 - 4",
      gospel: "Luk 10 : 1 - 12"
    },
    evening: ["Jer            15","Phl 3","Luk 21"],
    ana: 1,
  },
  {
    gregorianMonth: 5,
    gregorianDay: 12,
    gregorianDate: "May 12",
    ethiopianDate: "9/3",
    morning: ["Jer 16","Phl 4","Luk 22"],
    qidase: {
      epistle: "1Tm  3 : 1 - 11",
      catholicEpistle: "1Pt  5 : 1 - 8",
      acts: "Act 14 : 23 - f",
      psalm: "Ps 83 : 6 - 7",
      gospel: "Mat 25 : 14 - 31"
    },
    evening: ["Jer            17","Col 1","Luk 23"],
    ana: 5,
  },
  {
    gregorianMonth: 5,
    gregorianDay: 13,
    gregorianDate: "May 13",
    ethiopianDate: "9/4",
    morning: ["Jer 18","Col 2","Luk 24"],
    qidase: {
      epistle: "Heb  11 : 32 - f",
      catholicEpistle: "2Pt  1 : 19 - f",
      acts: "Act  7 : 51 - 55",
      psalm: "Ps 21 : 10 - 11",
      gospel: "Mat 21 : 33 - f"
    },
    evening: ["Jer            19","Col 3","Jhn 1"],
    ana: 5,
  },
  {
    gregorianMonth: 5,
    gregorianDay: 14,
    gregorianDate: "May 14",
    ethiopianDate: "9/5",
    morning: ["Jer 20","Col 4","Jhn 2"],
    qidase: {
      epistle: "Rom  6 : 15 - f",
      catholicEpistle: "1Pt  3 : 10 - 15",
      acts: "Act 16 : 35 - f",
      psalm: "Ps 24 : 4",
      gospel: "Lk 12 : 32 - 41"
    },
    evening: ["Jer            21","1Th 1","Jhn 3"],
    ana: 5,
  },
  {
    gregorianMonth: 5,
    gregorianDay: 15,
    gregorianDate: "May 15",
    ethiopianDate: "9/6",
    morning: ["Jer 22","1Th 2","Jhn 4"],
    qidase: {
      epistle: "1Tm  3 : 1 - 11",
      catholicEpistle: "1Pt  2 : 4 - 11",
      acts: "Act 20 : 28 31",
      psalm: "Ps 83 : 6 - 7",
      gospel: "Mt 18 : 1 - 12"
    },
    evening: ["Jer            23","1Th 3","Jhn 5"],
    ana: 6,
  },
  {
    gregorianMonth: 5,
    gregorianDay: 16,
    gregorianDate: "May 16",
    ethiopianDate: "9/7",
    morning: ["Jer 24","1Th 4","Jhn 6"],
    qidase: {
      epistle: "1Tm  6 : 7 - f",
      catholicEpistle: "Jam  1 : 7 - 17",
      acts: "Act 13 : 1 – 13",
      psalm: "Ps 118 : 70 - 71",
      gospel: "Mt 6 : 19 - f"
    },
    evening: ["Jer            24","1Th 5","Jhn 7"],
    ana: 7,
  },
  {
    gregorianMonth: 5,
    gregorianDay: 17,
    gregorianDate: "May 17",
    ethiopianDate: "9/8",
    morning: ["Jer 26","2Th 1","Jhn 8"],
    qidase: {
      epistle: "1Cr 11 : 1 - 17",
      catholicEpistle: "1Pt  3 : 1 - 7",
      acts: "Act 16 : 14 - 16",
      psalm: "Ps : 59 3 - 4",
      gospel: "Jhn 16 : 15 - 22"
    },
    evening: ["Jer          27","2Th 2","Jhn 9"],
    ana: 10,
  },
  {
    gregorianMonth: 5,
    gregorianDay: 18,
    gregorianDate: "May 18",
    ethiopianDate: "9/9",
    morning: ["Jer 28","2Th 3","Jhn 10"],
    qidase: {
      epistle: "Heb 11 : 32 - f",
      catholicEpistle: "2Pt  1 : 19 - f",
      acts: "Act  3 : 17 - f",
      psalm: "Ps 65 : 12",
      gospel: "Mat 18 : 19 - 23"
    },
    evening: ["Jer            29","1Tm 1","Jhn 11"],
    ana: 3,
  },
  {
    gregorianMonth: 5,
    gregorianDay: 19,
    gregorianDate: "May 19",
    ethiopianDate: "9/10",
    morning: ["Jer 30","1Tm 2","Jhn 12"],
    qidase: {
      epistle: "Eph  5 : 15 - 21",
      catholicEpistle: "Jam  5 : 12 -14",
      acts: "Act 26 : 24 - 30",
      psalm: "Ps 68 : 29, 30",
      gospel: "Luk  21 : 1 - 7"
    },
    evening: ["Jer          31","1Tm 3","Jhn 13"],
    ana: 11,
  },
  {
    gregorianMonth: 5,
    gregorianDay: 20,
    gregorianDate: "May 20",
    ethiopianDate: "9/11",
    morning: ["Ps83: 6, 7","Mat  5 : 1 -  17","Heb 13 : 13 - 22"],
    qidase: {
      catholicEpistle: "Jud  1 : 9 - 14",
      acts: "Act 13 : 16 - 20",
      psalm: "Ps 118 : 86 - 87",
      gospel: "Luk 10 : 29 - 38"
    },
    evening: ["Jer          32","1Tm 4","Jhn 14"],
    ana: 10,
  },
  {
    gregorianMonth: 5,
    gregorianDay: 21,
    gregorianDate: "May 21",
    ethiopianDate: "9/12",
    morning: ["Jer 33","1Tm 5","Jhn 15"],
    qidase: {
      epistle: "Eph  6 : 1 - 10",
      catholicEpistle: "1Pt  3 : 10 - 15",
      acts: "Act 21 : 27 - 31",
      psalm: "Ps 38 : 1 - 2",
      gospel: "Mat 20 : 1 - 17"
    },
    evening: ["Jer            34","1Tm 6","Jhn 16"],
    ana: 7,
  },
  {
    gregorianMonth: 5,
    gregorianDay: 22,
    gregorianDate: "May 22",
    ethiopianDate: "9/13",
    morning: ["Jer 35","2Tm 1","Jhn 17"],
    qidase: {
      epistle: "Gal  6 : 11 - f",
      catholicEpistle: "1Pt  4 : 12 - 17",
      acts: "Act  4 : 31 - f",
      psalm: "Ps 115 : 6 - 7",
      gospel: "Mat 10 : 1 - 17"
    },
    evening: ["Jer            36","2Tm 2","Jhn 18"],
    ana: 5,
  },
  {
    gregorianMonth: 5,
    gregorianDay: 23,
    gregorianDate: "May 23",
    ethiopianDate: "9/14",
    morning: ["Ps 31 : 2","Jhn 1 : 44 - f","Rom  8 : 24 - f"],
    qidase: {
      catholicEpistle: "Jud  1 : 17 – 23",
      acts: "Act 1  :  12 - 15",
      psalm: "Ps 18 : 3 - 4",
      gospel: "Mat 10 : 1 - 17"
    },
    evening: ["Jer            37","2Tm 3","Jhn 19"],
    ana: 1,
  },
  {
    gregorianMonth: 5,
    gregorianDay: 24,
    gregorianDate: "May 24",
    ethiopianDate: "9/15",
    morning: ["Jer 38","2Tm 4","Jhn 20"],
    qidase: {
      epistle: "Rev 1 : 1 - f",
      acts: "Act 10 : 14 - f",
      psalm: "Ps 106 : 29 - 30",
      gospel: "Jhn 21 : 20 - f"
    },
    evening: ["Jer            39","Tts 1","Jhn 21"],
    ana: 3,
  },
  {
    gregorianMonth: 5,
    gregorianDay: 25,
    gregorianDate: "May 25",
    ethiopianDate: "9/16",
    morning: ["Jer 40","Tts 2","Mat 1"],
    qidase: {
      epistle: "1Tm  3 : 1 - 8",
      catholicEpistle: "1Pt 5 : 1 - f",
      acts: "Act 20 : 28 - 31",
      psalm: "Ps 83 : 6, 7",
      gospel: "Luk 19 : 11 - 28"
    },
    evening: ["Jer            41","Tts 3","Mat 2"],
    ana: 9,
  },
  {
    gregorianMonth: 5,
    gregorianDay: 26,
    gregorianDate: "May 26",
    ethiopianDate: "9/17",
    morning: ["Jer 42","Plm 1","Mat 3"],
    qidase: {
      epistle: "2Cr 11 : 1 - 16",
      catholicEpistle: "1Pt  5 : 6 - 12",
      acts: "Act 10 : 44 - f",
      psalm: "Ps 118:61-63",
      gospel: "Mt 16 : 23 - f"
    },
    evening: ["Jer  43","Heb 1","Mat 4"],
    ana: 5,
  },
  {
    gregorianMonth: 5,
    gregorianDay: 27,
    gregorianDate: "May 27",
    ethiopianDate: "9/18",
    morning: ["Jer 44","Heb 2","Mat 5"],
    qidase: {
      epistle: "2Cr  1 : 1 - 13",
      catholicEpistle: "1Pt  1 : 6 - 10",
      acts: "Act  8 : 1 - 9",
      psalm: "Ps 117 : 16, 17",
      gospel: "Lk  3 : 10 - 19"
    },
    evening: ["Jer  45","Heb 3","Mat 6"],
    ana: 7,
  },
  {
    gregorianMonth: 5,
    gregorianDay: 28,
    gregorianDate: "May 28",
    ethiopianDate: "9/19",
    morning: ["Jer 46","Heb 4","Mat 7"],
    qidase: {
      epistle: "Rom 13 : 1 - 13",
      catholicEpistle: "1Pt  2 : 11 - 20",
      acts: "Act 13 : 40 - f",
      psalm: "Ps 74:2, 3",
      gospel: "Mt 16 : 24 - f"
    },
    evening: ["Jer            47","Heb 5","Mat 8"],
    ana: 7,
  },
  {
    gregorianMonth: 5,
    gregorianDay: 29,
    gregorianDate: "May 29",
    ethiopianDate: "9/20",
    morning: ["Jer  48","Heb 6","Mat 9"],
    qidase: {
      epistle: "Rev 12 : 1 - 5",
      catholicEpistle: "2Pt 1 : 1 - 12",
      psalm: "Ps 140:4",
      gospel: "Mat 18:6-19"
    },
    evening: ["Jer            49","Heb 7","Mat 10"],
    ana: 4,
  },
  {
    gregorianMonth: 5,
    gregorianDay: 30,
    gregorianDate: "May 30",
    ethiopianDate: "9/21",
    morning: ["Jer  50","Heb 8","Mat 11"],
    qidase: {
      epistle: "Rom 16 : 6 - 10",
      catholicEpistle: "1Jn 2 : 27 - f",
      acts: "Act 21 : 15 - 21",
      psalm: "Ps  18:3,4",
      gospel: "Luk 10 : 1 - 12"
    },
    evening: ["Jer            51","Heb 9","Mat 12:1-37"],
    ana: 1,
  },
  {
    gregorianMonth: 5,
    gregorianDay: 31,
    gregorianDate: "May 31",
    ethiopianDate: "9/22",
    morning: ["Ps 44:12, 13","Mat 10 : 16 - 32","Rom 16 : 7 - 10"],
    qidase: {
      catholicEpistle: "Jud 1 : 20 - f",
      acts: "Act 21 : 15 - 21",
      psalm: "Ps 44 : 9, 10",
      gospel: "Luk 1 : 17 - 25"
    },
    evening: ["Lam 1","Heb 11","Mat 13:1-30"],
    ana: 4,
  }
];
