/** Auto-generated by scripts/build-lectionary-readings.mjs — do not edit by hand. */
import type { DayReadings } from './types';

export const novemberReadings: DayReadings[] = [
  {
    gregorianMonth: 11,
    gregorianDay: 1,
    gregorianDate: "Nov 1",
    ethiopianDate: "1/26",
    morning: ["Gal 4:12-36","Jhn 13","Ps 44:9, 10"],
    qidase: {
      epistle: "Rom  10 : 9 - 16",
      catholicEpistle: "2Jn  1 : 5 -  8",
      acts: "Act  2 : 14 - 22",
      psalm: "Ps 104:14,15",
      gospel: "Jhn  11 : 38 - 46"
    },
    evening: ["Num 34, 35","Gal 5","Jhn 14"],
    ana: 3,
  },
  {
    gregorianMonth: 11,
    gregorianDay: 2,
    gregorianDate: "Nov 2",
    ethiopianDate: "1/27",
    morning: ["Festal hiatus","1Jn  1 : 4 - f","Act  1:1-6","Ps 18: 3, 4"],
    qidase: {
      psalm: "UNCLEAR - please verify",
      gospel: "Luk. 1 : 1-5"
    },
    evening: ["Num          36","Gal 6","Jhn 15"],
    ana: 1,
  },
  {
    gregorianMonth: 11,
    gregorianDay: 3,
    gregorianDate: "Nov 3",
    ethiopianDate: "1/28",
    morning: ["Deu 1","Eph 1","Jhn 16"],
    qidase: {
      epistle: "1Tm 6 : 17 - f",
      catholicEpistle: "Jam  1 : 12 - 19",
      acts: "Act  15:1-9",
      psalm: "Ps  83 : 6, 7",
      gospel: "Luk 6 : 36-f"
    },
    evening: ["Deu          2","Eph 2","Jhn 17"],
    ana: 5,
  },
  {
    gregorianMonth: 11,
    gregorianDay: 4,
    gregorianDate: "Nov 4",
    ethiopianDate: "1/29",
    morning: ["Deu 3","Eph 3","Jhn 18"],
    qidase: {
      epistle: "1Cr  14 : 26 - 34",
      catholicEpistle: "1Pt  3 : 5 - 10",
      acts: "Act  16:13-16",
      psalm: "Ps 78 : 2, 3",
      gospel: "Mrk  13 : 11 - 24"
    },
    evening: ["Deu  4","Eph 4","Jhn 19"],
    ana: 3,
  },
  {
    gregorianMonth: 11,
    gregorianDay: 5,
    gregorianDate: "Nov 5",
    ethiopianDate: "1/30",
    morning: ["Deu 5","Eph 5","Jhn 20"],
    qidase: {
      epistle: "Eph  7 : 14 - f",
      catholicEpistle: "1Pt  3 : 10 - 18",
      acts: "Act  11:23-27",
      psalm: "Ps 115 : 6-7",
      gospel: "Mat  10 : 32 - f"
    },
    evening: ["Ps 91 : 12, 13 5 Deu 6","Eph 6","Jhn 21"],
    ana: null,
  },
  {
    gregorianMonth: 11,
    gregorianDay: 6,
    gregorianDate: "Nov 6",
    ethiopianDate: "2/1",
    morning: ["Festal hiatus","1Jn 2 : 28 - 3:10","Act  6:1 - 8","Ps 113 : 22, 23"],
    qidase: {
      psalm: "UNCLEAR - please verify",
      gospel: "Luk  10 : 1 - 12"
    },
    evening: ["Deu          7","Phi 1","Mat  1"],
    ana: 4,
  },
  {
    gregorianMonth: 11,
    gregorianDay: 7,
    gregorianDate: "Nov 7",
    ethiopianDate: "2/2",
    morning: ["Deu 8","Phi 2","Mat 2"],
    qidase: {
      epistle: "1Cr 12 : 22 - 28",
      catholicEpistle: "1Pt  2 : 21 - f",
      acts: "Act  5:12-16",
      psalm: "Ps 55 : 1",
      gospel: "Jhn  3 : 11 - 25"
    },
    evening: ["Deu        9","Phi 3","Mat 3"],
    ana: 10,
  },
  {
    gregorianMonth: 11,
    gregorianDay: 8,
    gregorianDate: "Nov 8",
    ethiopianDate: "2/3",
    morning: ["Deu 10","Phi 4","Mat 4"],
    qidase: {
      epistle: "Heb  6 : 9 - 15",
      catholicEpistle: "1Pt  4 : 12 - f",
      acts: "Act  3:12-17",
      psalm: "Ps 111 : 2, 3",
      gospel: "Luk  20 : 37 - f"
    },
    evening: ["Deu          11","Col 1","Mat 5"],
    ana: 5,
  },
  {
    gregorianMonth: 11,
    gregorianDay: 9,
    gregorianDate: "Nov 9",
    ethiopianDate: "2/4",
    morning: ["Deu 12","Col 2","Mat 6"],
    qidase: {
      epistle: "2Cr  6 : 1 - 12",
      catholicEpistle: "1Jn  3 : 7 - 12",
      acts: "Act   9:20-23",
      psalm: "Ps 17 :39, 40",
      gospel: "Mrk  8:34-9:2"
    },
    evening: ["Deu          13","Col 3","Mat 6"],
    ana: 4,
  },
  {
    gregorianMonth: 11,
    gregorianDay: 10,
    gregorianDate: "Nov 10",
    ethiopianDate: "2/5",
    morning: ["Deu 14","Col 4","Mat 8"],
    qidase: {
      epistle: "2Tm  4 : 11 - f",
      catholicEpistle: "Jam  1 : 2 - 6",
      acts: "Act 10:37-43",
      psalm: "Ps 39 : 6",
      gospel: "Mat  16 : 24 - f"
    },
    evening: ["Deu          15","1Th 1","Mat 9"],
    ana: 5,
  },
  {
    gregorianMonth: 11,
    gregorianDay: 11,
    gregorianDate: "Nov 11",
    ethiopianDate: "2/6",
    morning: ["Deu 16","1Th 2","Mat 10"],
    qidase: {
      epistle: "Heb  10 : 32 - f",
      catholicEpistle: "1Pt  4  : 4 - 12",
      acts: "Act  4:10-19",
      psalm: "Ps 118 :47, 48",
      gospel: "Mat  16 : 24 - f"
    },
    evening: ["Deu  17","1Th 3","Mat 11"],
    ana: 11,
  },
  {
    gregorianMonth: 11,
    gregorianDay: 12,
    gregorianDate: "Nov 12",
    ethiopianDate: "2/7",
    morning: ["Deu  18:1-12","1Th 4:1-12","Mat 12:1-8"],
    qidase: {
      epistle: "Col  4 : 16 - f",
      catholicEpistle: "1Pt  1 : 1 - 7",
      acts: "Act  20:28-31",
      psalm: "Ps 111 : 6, 7",
      gospel: "Jhn 10 : 1 - 22"
    },
    evening: ["Deu          18:13-22","1Th 4:13-18","Mat 12:9-21"],
    ana: 5,
  },
  {
    gregorianMonth: 11,
    gregorianDay: 13,
    gregorianDate: "Nov 13",
    ethiopianDate: "2/8",
    morning: ["Deu 19:1-9","1Th 5:1-10","Mat 12:22-37"],
    qidase: {
      epistle: "1Tm  4 : 7 - f",
      catholicEpistle: "1Jn  2 : 15 - 22",
      acts: "Act 19:8-11",
      psalm: "Ps 1 : 2, 3",
      gospel: "Mat  12 : 9 - 14"
    },
    evening: ["Deu          19:10-21","1Th 5:11-28","Mat 12:38-50"],
    ana: 4,
  },
  {
    gregorianMonth: 11,
    gregorianDay: 14,
    gregorianDate: "Nov 14",
    ethiopianDate: "2/9",
    morning: ["Deu 20","2Th 1","Mat 13:1-30"],
    qidase: {
      epistle: "2Cr  11 : 29 - f",
      catholicEpistle: "1Pt   5 : 9 - f",
      acts: "Act   9:22-f",
      psalm: "Ps 43 : 22, 23",
      gospel: "Mat  10 : 32 - f"
    },
    evening: ["Deu          21","2Th 2","Mat 13:31-58"],
    ana: 3,
  },
  {
    gregorianMonth: 11,
    gregorianDay: 15,
    gregorianDate: "Nov 15",
    ethiopianDate: "2/10",
    morning: ["Deu 22","1Tm 3","Mat 14"],
    qidase: {
      epistle: "Rom  5 : 8 - f",
      catholicEpistle: "1Pt  2 : 9 - 13",
      acts: "Act  26:12-19",
      psalm: "Ps 24 :  7",
      gospel: "Jhn  19 : 31 - f"
    },
    evening: ["Deu          24","1Tm 1","Mat 15:1-20"],
    ana: 4,
  },
  {
    gregorianMonth: 11,
    gregorianDay: 16,
    gregorianDate: "Nov 16",
    ethiopianDate: "2/11",
    morning: ["Ps 88 : 3","Luk  22 : 14 - 24","2Cr  8 : 1 - 16"],
    qidase: {
      catholicEpistle: "2Jn  1 :  9 - f",
      acts: "Act  1:12-15",
      psalm: "Ps 36:35, 36",
      gospel: "Mat 2:19-f"
    },
    evening: ["Deu          25","1Tm 2","Mat 15:21-39"],
    ana: 2,
  },
  {
    gregorianMonth: 11,
    gregorianDay: 17,
    gregorianDate: "Nov 17",
    ethiopianDate: "2/12",
    morning: ["Ps 67 : 35","Jhn  14:1-15","Eph  5:23-28"],
    qidase: {
      catholicEpistle: "1Pt  4 : 12 – f",
      acts: "Act  27:21-27",
      psalm: "Ps 78 :10, 11",
      gospel: "Mat  10 : 16 - f"
    },
    evening: ["Deu  27","1Tm 4","Mat 17"],
    ana: 7,
  },
  {
    gregorianMonth: 11,
    gregorianDay: 18,
    gregorianDate: "Nov 18",
    ethiopianDate: "2/13",
    morning: ["Deu 28","1Tm 5","Mat 18"],
    qidase: {
      epistle: "Rev 4:6-f",
      acts: "Act  5:29-f",
      psalm: "Ps  17:10, 11",
      gospel: "Mat  18 : 10 - 15"
    },
    evening: ["Deu 29","1Tm 6","Mat 19:1-15"],
    ana: 5,
  },
  {
    gregorianMonth: 11,
    gregorianDay: 19,
    gregorianDate: "Nov 19",
    ethiopianDate: "2/14",
    morning: ["Deu 30","2Tm 1","Mat 19:16-30"],
    qidase: {
      epistle: "Col 2 : 5 - 13",
      catholicEpistle: "2Jn  1 : 6 – 12",
      acts: "Ac 15:22-30",
      psalm: "Ps 72 : 9",
      gospel: "Jhn  10 : 25 - f"
    },
    evening: ["Deu 31","2Tm 2","Mat 20:1-19"],
    ana: 5,
  },
  {
    gregorianMonth: 11,
    gregorianDay: 20,
    gregorianDate: "Nov 20",
    ethiopianDate: "2/15",
    morning: ["Deu 32","2Tm 3","Mat 20:20-34"],
    qidase: {
      epistle: "Tts  2 : 1 -  9",
      catholicEpistle: "1Pt  3 : 1 – 7",
      acts: "Act 17:24-30",
      psalm: "Ps 68 : 10, 11",
      gospel: "Mat  25 : 1 - 19"
    },
    evening: ["Deu 33","2Tm 4","Mat 21:1-32"],
    ana: 3,
  },
  {
    gregorianMonth: 11,
    gregorianDay: 21,
    gregorianDate: "Nov 21",
    ethiopianDate: "2/16",
    morning: ["Deu 34","Tts 1","Mat 21:33-46"],
    qidase: {
      epistle: "1Tm 5:5-11",
      catholicEpistle: "1Pt 3:5",
      acts: "Act 16:14-19",
      psalm: "Ps 44 : 9, 10",
      gospel: "Luk  18 : 1 - 9"
    },
    evening: ["Jos 1","Tts 2","Mat 22"],
    ana: 4,
  },
  {
    gregorianMonth: 11,
    gregorianDay: 22,
    gregorianDate: "Nov 22",
    ethiopianDate: "2/17",
    morning: ["Ps 20 : 1-2","Luk  19:11-28","Rom  9:17-24"],
    qidase: {
      catholicEpistle: "Jud  1:9-14",
      acts: "Act 20:28-31",
      psalm: "Ps 33 :  7, 8",
      gospel: "Mat 18 : 15 - 21"
    },
    evening: ["Jos 2","Tts 3","Mat 23"],
    ana: 7,
  },
  {
    gregorianMonth: 11,
    gregorianDay: 23,
    gregorianDate: "Nov 23",
    ethiopianDate: "2/18",
    morning: ["Jos 3","Plm 1","Mat 24:1-35"],
    qidase: {
      epistle: "Heb 12:22-25",
      catholicEpistle: "Jud  1:14-17",
      acts: "Act  12:6-12",
      psalm: "Ps 102 :19, 20",
      gospel: "Mat  25 : 31 - f"
    },
    evening: ["Jos 4","Heb 1","Mat 24:36-51"],
    ana: 5,
  },
  {
    gregorianMonth: 11,
    gregorianDay: 24,
    gregorianDate: "Nov 24",
    ethiopianDate: "2/19",
    morning: ["Jos 5","Heb 2","Mat 25:1-30"],
    qidase: {
      epistle: "1Cr 15:10-24",
      catholicEpistle: "1Pt  5 : 6 – f",
      acts: "Act  23:7-10",
      psalm: "Ps 26 :10, 11",
      gospel: "Jhn  4 : 47 - f"
    },
    evening: ["Jos 6:1-14","Heb 3:1-11","Mat 25:31-46"],
    ana: 7,
  },
  {
    gregorianMonth: 11,
    gregorianDay: 25,
    gregorianDate: "Nov 25",
    ethiopianDate: "2/20",
    morning: ["Jos 6:15-27","Heb 3:12-19","Mat 26:1-29"],
    qidase: {
      epistle: "Rom  14 : 12 - f",
      catholicEpistle: "1Pt   2:21-f",
      acts: "Act  13:1-13",
      psalm: "Ps 78:10,11",
      gospel: "Jhn  5 : 1 - 5"
    },
    evening: ["Jos 7","Heb 4","Mat 26:30-46"],
    ana: 3,
  },
  {
    gregorianMonth: 11,
    gregorianDay: 26,
    gregorianDate: "Nov 26",
    ethiopianDate: "2/21",
    morning: ["Jos 8","Heb 5","Mat 26:47-75"],
    qidase: {
      epistle: "2Cr  9 : 5 - f",
      catholicEpistle: "1Pt  5 : 2 – 12",
      acts: "Act  14:23-f",
      psalm: "Ps 20 : 1, 2",
      gospel: "Luk 14 : 7 - 16"
    },
    evening: ["Jos 9","Heb 6","Mat 27"],
    ana: 11,
  },
  {
    gregorianMonth: 11,
    gregorianDay: 27,
    gregorianDate: "Nov 27",
    ethiopianDate: "2/22",
    morning: ["Jos 10","Heb 7","Mat 28"],
    qidase: {
      epistle: "Phi  1:12 - 19",
      catholicEpistle: "1Pt  3:10-18",
      acts: "Act  16:14-25",
      psalm: "Ps 145 : 9",
      gospel: "Mat  10 : 16 - f"
    },
    evening: ["Jos 23; 24","Heb 8","Mrk 1"],
    ana: 10,
  },
  {
    gregorianMonth: 11,
    gregorianDay: 28,
    gregorianDate: "Nov 28",
    ethiopianDate: "2/23",
    morning: ["Jdg 1","Heb 9","Mrk 2"],
    qidase: {
      epistle: "Tts  2 : 1 - 20",
      catholicEpistle: "Jud  1 : 17 – f",
      acts: "Act  8:5-14",
      psalm: "Ps 145 : 9",
      gospel: "Jhn  6 : 4 - 15"
    },
    evening: ["Jdg 2; 3","Heb 10: 1-18","Mrk 3"],
    ana: 1,
  },
  {
    gregorianMonth: 11,
    gregorianDay: 29,
    gregorianDate: "Nov 29",
    ethiopianDate: "2/24",
    morning: ["Jdg 4","Heb 10:19-29","Mrk 4"],
    qidase: {
      epistle: "1Cr 12:28-f",
      catholicEpistle: "Jud  1 : 20 – f",
      acts: "Act 4:29-37",
      psalm: "Ps 18 : 7, 8",
      gospel: "Mat 10:1-17"
    },
    evening: ["Jdg 5","Heb 11: 1-16","Mrk 5"],
    ana: 3,
  },
  {
    gregorianMonth: 11,
    gregorianDay: 30,
    gregorianDate: "Nov 30",
    ethiopianDate: "2/25",
    morning: ["Jdg 6","Heb 11:17-40","Mrk 6"],
    qidase: {
      epistle: "Tts 1:5-12",
      catholicEpistle: "1Pt 5: 1- 20",
      acts: "Act 20:28-31",
      psalm: "Ps 83:6, 7",
      gospel: "Jhn 10:1-22"
    },
    evening: ["Jdg 7","Heb 13:1-16","Mrk 7"],
    ana: 2,
  }
];
