/** Auto-generated by scripts/build-lectionary-readings.mjs — do not edit by hand. */
import type { DayReadings } from './types';

export const octoberReadings: DayReadings[] = [
  {
    gregorianMonth: 10,
    gregorianDay: 1,
    gregorianDate: "Oct 1",
    ethiopianDate: "13/25",
    morning: ["Gen 37,38","Act 26","Mat 26:47-75"],
    qidase: {
      epistle: "Tts  1 : 5 - 12",
      catholicEpistle: "Jam 1: 2 - 13",
      acts: "Act 8: 28-31",
      psalm: "Ps 83: 6, 7",
      gospel: "Jhn 10: 1 –22"
    },
    evening: ["Gen 39","Act 27","Mat"],
    ana: 3,
  },
  {
    gregorianMonth: 10,
    gregorianDay: 2,
    gregorianDate: "Oct 2",
    ethiopianDate: "13/26",
    morning: ["Gen 40","Act 28","Mrk 1"],
    qidase: {
      epistle: "1Cr  5 : 3 - f",
      catholicEpistle: "2Jn  1 :  4 - f",
      acts: "Act 19:17-21",
      psalm: "Ps 34: 9,10",
      gospel: "Luk  1 : 39 - 57"
    },
    evening: ["Gen 41","Rom 1","Mrk  2"],
    ana: 5,
  },
  {
    gregorianMonth: 10,
    gregorianDay: 3,
    gregorianDate: "Oct 3",
    ethiopianDate: "13/27",
    morning: ["Gen 42","Rom 2","Mrk 3"],
    qidase: {
      epistle: "2Cr  4 : 7 - f",
      catholicEpistle: "1Pt  4 : 12 - f",
      acts: "Act 19: 8-11",
      psalm: "Ps 33:19,20",
      gospel: "Mrk 13 : 9 - 14"
    },
    evening: ["Gen 43","Rom 3","Mrk  4"],
    ana: 3,
  },
  {
    gregorianMonth: 10,
    gregorianDay: 4,
    gregorianDate: "Oct 4",
    ethiopianDate: "13/28",
    morning: ["Gen 44","Rom 4","Mrk 5"],
    qidase: {
      epistle: "2Tm  2 : 1 - 11",
      catholicEpistle: "1Pt  1 : 6 - 10",
      acts: "Act 24:11-22",
      psalm: "Ps 59: 3, 5",
      gospel: "Mrk  13 : 11 - 32"
    },
    evening: ["Gen 45","Rom 5","Mrk 6"],
    ana: 7,
  },
  {
    gregorianMonth: 10,
    gregorianDay: 5,
    gregorianDate: "Oct 5",
    ethiopianDate: "13/29",
    morning: ["Gen 46","Rom 6","Mrk 7"],
    qidase: {
      epistle: "1Cr  2 : 12 - f",
      catholicEpistle: "1Jn 2 : 20 - f",
      acts: "Act 10:39-f",
      psalm: "Ps 18: 4, 5",
      gospel: "Luk  10 :  1 - 12"
    },
    evening: ["Gen 47","Rom 7","Mrk 8"],
    ana: 3,
  },
  {
    gregorianMonth: 10,
    gregorianDay: 6,
    gregorianDate: "Oct 6",
    ethiopianDate: "13/30",
    morning: ["Gen 48","Rom 8:1-17","Mrk 9:1-32"],
    qidase: {
      epistle: "Rom  2 : 1 - 12",
      catholicEpistle: "2Pt  3 : 1 -  8",
      acts: "Act 20:9-28",
      psalm: "Ps 138:7, 8",
      gospel: "Mat 12 : 38 - 43"
    },
    evening: ["Gen 49","Acts 8:18-39","Mrk  9:33-50"],
    ana: 10,
  },
  {
    gregorianMonth: 10,
    gregorianDay: 7,
    gregorianDate: "Oct 7",
    ethiopianDate: "1/1",
    morning: ["Gen 50","Rom 9","Mrk 10"],
    qidase: {
      epistle: "Heb  12 : 1 -  11",
      catholicEpistle: "1Pt 2 : 20 -  f",
      acts: "Act  10:  5 - 9",
      psalm: "Ps 137:1, 2",
      gospel: "Luk   1 : 1 - 23"
    },
    evening: ["Exo 1","Rom 10","Mrk 11"],
    ana: 9,
  },
  {
    gregorianMonth: 10,
    gregorianDay: 8,
    gregorianDate: "Oct 8",
    ethiopianDate: "1/2",
    morning: ["Exo 2","Rom 11","Mrk 12"],
    qidase: {
      epistle: "Rom  5 : 8 - 12",
      catholicEpistle: "Jam  2  : 5 -14",
      acts: "Act  17 : 1 - 10",
      psalm: "Ps 131: 6, 7",
      gospel: "Mat  19 : 16 - 27"
    },
    evening: ["Exo 3","Rom 12","Mrk 13"],
    ana: 10,
  },
  {
    gregorianMonth: 10,
    gregorianDay: 9,
    gregorianDate: "Oct 9",
    ethiopianDate: "1/3",
    morning: ["Exo 4","Rom 13","Mrk 14"],
    qidase: {
      epistle: "Heb  11 : 8 - 22",
      catholicEpistle: "Jam  4 : 11 - f",
      acts: "Act  12 : 12 - f",
      psalm: "Ps 114: 8, 9",
      gospel: "Jhn  8 : 3 - 12"
    },
    evening: ["Exo 5","Rom 14","Mrk 15"],
    ana: 5,
  },
  {
    gregorianMonth: 10,
    gregorianDay: 10,
    gregorianDate: "Oct 10",
    ethiopianDate: "1/4",
    morning: ["Exo 6","Rom 15 ;    Mrk 16","Ps 47: 11, 12"],
    qidase: {
      epistle: "Gal  4 : 1 - 12",
      catholicEpistle: "1Jn  1 : 1 - f",
      acts: "Act  3 : 1 - 12",
      psalm: "Ps 2: 7, 8",
      gospel: "Luk  21 : 21 - f"
    },
    evening: ["Exo 7","Rom 16","Luk 1:1-38"],
    ana: 5,
  },
  {
    gregorianMonth: 10,
    gregorianDay: 11,
    gregorianDate: "Oct 11",
    ethiopianDate: "1/5",
    morning: ["Exo 8","1Cr 1","Luk 1:39-80"],
    qidase: {
      epistle: "1Cr  9 : 20 - f",
      catholicEpistle: "2Jn 1 : 8 - f",
      acts: "Act  20 : 28 - 31",
      psalm: "Ps 132:1,2",
      gospel: "Mrk  1 : 16 - 23"
    },
    evening: ["Exo 9","1Cr 2","Luk 2"],
    ana: 2,
  },
  {
    gregorianMonth: 10,
    gregorianDay: 12,
    gregorianDate: "Oct 12",
    ethiopianDate: "1/6",
    morning: ["Exo 10","1Cr 3","Luk  3"],
    qidase: {
      epistle: "1Cr 7 : 32 - f",
      catholicEpistle: "1Pt  3 : 1 - 5",
      acts: "Act  17 : 10 - 13",
      psalm: "Ps 102:14,15",
      gospel: "Mat  6 : 25 - f"
    },
    evening: [" Exo 11","1Cr  4","Luk 4"],
    ana: 2,
  },
  {
    gregorianMonth: 10,
    gregorianDay: 13,
    gregorianDate: "Oct 13",
    ethiopianDate: "1/7",
    morning: ["Exo 12","1Cr  5","Luk 5"],
    qidase: {
      epistle: "2Cr  4 : : 7 - f",
      catholicEpistle: "1Pt  5 : 5 - 12",
      acts: "Ac  20 : 1 - 7",
      psalm: "Ps 10 : 1, 2",
      gospel: "Mt  5 : 10 - 17"
    },
    evening: ["Exo            13","1Cr  6","Luk 6"],
    ana: 3,
  },
  {
    gregorianMonth: 10,
    gregorianDay: 14,
    gregorianDate: "Oct 14",
    ethiopianDate: "1/8",
    morning: ["Exo 14","1Cr  7","Luk 7"],
    qidase: {
      epistle: "Tt  2 : 1 - 9",
      catholicEpistle: "1Pt  5 : 2 - 5",
      acts: "Ac  20 : 28 - 31",
      psalm: "Ps 44: 9, 10",
      gospel: "Lk  10 : 38 - f"
    },
    evening: ["Exo            15","1Cr  8","Luk 8"],
    ana: 2,
  },
  {
    gregorianMonth: 10,
    gregorianDay: 15,
    gregorianDate: "Oct 15",
    ethiopianDate: "1/9",
    morning: ["Exo","1Cr 9","Luk 9:1-27"],
    qidase: {
      epistle: "1Cr  7 : 29 - f",
      catholicEpistle: "1Pt  1 : 16 - f",
      acts: "Ac  9 : 10 - 20",
      psalm: "Ps 67 : 21, 22",
      gospel: "Lk  10 : 17 - 25"
    },
    evening: ["Exo            17","1Cr  10:1-13","Luk 9:29-62"],
    ana: 5,
  },
  {
    gregorianMonth: 10,
    gregorianDay: 16,
    gregorianDate: "Oct 16",
    ethiopianDate: "1/10",
    morning: ["Festal hiatus","1Pt  4 : 12 - f","Ac  16 : 22 - 28","Ps 93: 6, 7"],
    qidase: {
      psalm: "UNCLEAR - please verify",
      gospel: "Mt  18 : 23 - f"
    },
    evening: ["Exo            18","1Cr  10:14-23","Luk 10"],
    ana: 3,
  },
  {
    gregorianMonth: 10,
    gregorianDay: 17,
    gregorianDate: "Oct 17",
    ethiopianDate: "1/11",
    morning: ["Exo 19","1Cr 11:1-16","Luk 11:1-26"],
    qidase: {
      epistle: "1Tm  5 : 5 - 10",
      catholicEpistle: "1Pt   5 : 9 - f",
      acts: "Ac  17 : 30 - f",
      psalm: "Ps 101:3-5",
      gospel: "Mt  10 : 32-f; Lk  2 : 36-39"
    },
    evening: ["Exo            20","1Cr 11:17-34","Luk 11:27-54"],
    ana: 2,
  },
  {
    gregorianMonth: 10,
    gregorianDay: 18,
    gregorianDate: "Oct 18",
    ethiopianDate: "1/12",
    morning: ["Exo 21","1Cr  12","Luk 12"],
    qidase: {
      epistle: "2Cr  11 : 23 - f",
      catholicEpistle: "Jam  1 : 12 - 17",
      acts: "Act  21 : 12 - 17",
      psalm: "Ps 33:17,18",
      gospel: "Mat  19 : 25 - f"
    },
    evening: ["Exo            22","1Cr 13","Luk 13"],
    ana: 5,
  },
  {
    gregorianMonth: 10,
    gregorianDay: 19,
    gregorianDate: "Oct 19",
    ethiopianDate: "1/13",
    morning: ["Exo 23","1Cr 14:1-25","Luk 14"],
    qidase: {
      epistle: "Heb  11 : 8 - 22",
      catholicEpistle: "Jam  4 : 11 - f",
      acts: "Act  12 : 12 - f",
      psalm: "Ps 114: 8, 9",
      gospel: "Jhn  8 : 3 - 12"
    },
    evening: ["Exo            24","1Cr 14:26-","Luk 15"],
    ana: 7,
  },
  {
    gregorianMonth: 10,
    gregorianDay: 20,
    gregorianDate: "Oct 20",
    ethiopianDate: "1/14",
    morning: ["Exo 32;  1Cr 15:1-32","Luk 16","Ps 47: 11, 12"],
    qidase: {
      epistle: "Gal  4 : 1 - 12",
      catholicEpistle: "1Jn  1 : 1 - f",
      acts: "Act  3 : 1 - 12",
      psalm: "Ps 2: 7, 8",
      gospel: "Luk  21 : 21 - f"
    },
    evening: ["Exo            33","1Cr 15:33","Luk 17"],
    ana: 7,
  },
  {
    gregorianMonth: 10,
    gregorianDay: 21,
    gregorianDate: "Oct 21",
    ethiopianDate: "1/15",
    morning: ["Exo 34","1Cr 16","Luk 18"],
    qidase: {
      epistle: "Tts  1 : 7 - 12",
      catholicEpistle: "1Pt  5 : 9 - f",
      acts: "Act 20:28-31",
      psalm: "Ps 131:9,10",
      gospel: "Mrk  13 : 9 - 42"
    },
    evening: ["Lev            18","2Cr 1","Luk 19"],
    ana: 5,
  },
  {
    gregorianMonth: 10,
    gregorianDay: 22,
    gregorianDate: "Oct 22",
    ethiopianDate: "1/16",
    morning: ["Lev 19","2Cr 2","Luk  20"],
    qidase: {
      epistle: "1Tm  4 : 9 - f",
      catholicEpistle: "Jam  3 : 1 - 5",
      acts: "Act 20:28-31",
      psalm: "Ps 83 : 6",
      gospel: "Mat  5 : 11 - 17"
    },
    evening: ["Lev            20","2Cr 3","Luk 21"],
    ana: 2,
  },
  {
    gregorianMonth: 10,
    gregorianDay: 23,
    gregorianDate: "Oct 23",
    ethiopianDate: "1/17",
    morning: ["Ps 88:19,10","Mt 19 : 1 - 16","1Tm  5 : 19 - f"],
    qidase: {
      catholicEpistle: "Jud  1 : 9 - 14",
      acts: "Act 13:22-29",
      psalm: "Ps 83:6,7",
      gospel: "Mat  9 : 9  - 32"
    },
    evening: ["Lev            26","2Cr 4","Luke 22:1-30"],
    ana: 8,
  },
  {
    gregorianMonth: 10,
    gregorianDay: 24,
    gregorianDate: "Oct 24",
    ethiopianDate: "1/18",
    morning: ["Num 11","2Cr   5","Luk  22:31-71"],
    qidase: {
      epistle: "2Cr  9 : 1 - 10",
      catholicEpistle: "Jam  1 : 9 - 17",
      acts: "Act  20 : 16 - 28",
      psalm: "Ps 91:12, 13",
      gospel: "Luk  12 : 26 - 32"
    },
    evening: ["Num          12","2Cr  6","Luk 23"],
    ana: 10,
  },
  {
    gregorianMonth: 10,
    gregorianDay: 25,
    gregorianDate: "Oct 25",
    ethiopianDate: "1/19",
    morning: ["Ps 144:10,11","Jn  14 : 8 - 15","1Cr  7:36 - f"],
    qidase: {
      catholicEpistle: "1Pt  2 : 18 - 21",
      acts: "Act  8:27 - f",
      psalm: "Ps 18: 3, 4",
      gospel: "Mat  19 : 26 - f"
    },
    evening: ["Num          13","2Cr 7","Luk  24"],
    ana: 10,
  },
  {
    gregorianMonth: 10,
    gregorianDay: 26,
    gregorianDate: "Oct 26",
    ethiopianDate: "1/20",
    morning: ["Num 14","2Cr  8","Jhn  1"],
    qidase: {
      epistle: "Rom  8 : 31 - 35",
      catholicEpistle: "Jud  1 : 17 - 22",
      acts: "Act 15:22-30",
      psalm: "Ps 21:22,23",
      gospel: "Mat  18 : 12 - 21"
    },
    evening: ["Num 15, 16","2Cr  9","Jhn 2"],
    ana: 3,
  },
  {
    gregorianMonth: 10,
    gregorianDay: 27,
    gregorianDate: "Oct 27",
    ethiopianDate: "1/21",
    morning: ["Num 17","2Cr  10","Jhn"],
    qidase: {
      epistle: "Ep  6 : 13 - 19",
      catholicEpistle: "1Pt  3 : 10 - 18",
      acts: "Ac  20 : 28 - 31",
      psalm: "Ps 21:4, 5",
      gospel: "Mat  5 : 1 - 17"
    },
    evening: ["Num 19, 20","2Cr  11:1-15","Jhn 4"],
    ana: 2,
  },
  {
    gregorianMonth: 10,
    gregorianDay: 28,
    gregorianDate: "Oct 28",
    ethiopianDate: "1/22",
    morning: ["Num 21","2Cr  11:16-33","Jhn 3"],
    qidase: {
      epistle: "2Tm  1 : 3 - 15",
      catholicEpistle: "1Pt  5 : 2 - 5",
      acts: "Act  7 : 54 - f",
      psalm: "Ps 50:10, 11",
      gospel: "Luk  21 : 1 - 7"
    },
    evening: ["Num            22","2Cr 12","Jhn 6"],
    ana: 3,
  },
  {
    gregorianMonth: 10,
    gregorianDay: 29,
    gregorianDate: "Oct 29",
    ethiopianDate: "1/23",
    morning: ["Num 23","2Cr  13","Jhn 5"],
    qidase: {
      epistle: "Tts  1 : 7 - 12",
      catholicEpistle: "1Pt  1 : 6 - 10",
      acts: "Act  20 : 31 - f",
      psalm: "Ps 35:8, 9",
      gospel: "Mrk  12 : 13 - 17"
    },
    evening: ["Num 24,","Gal 1","Jhn 8"],
    ana: 7,
  },
  {
    gregorianMonth: 10,
    gregorianDay: 30,
    gregorianDate: "Oct 30",
    ethiopianDate: "1/24",
    morning: ["Num 25","Gal 2","Jhn 7"],
    qidase: {
      epistle: "Tts  3 : 8 - 12",
      catholicEpistle: "1Jn   2: 22 - f",
      acts: "Act  20 : 28 - 31",
      psalm: "Ps 108:7, 8",
      gospel: "Mat  18  : 15 - 21"
    },
    evening: ["Num, 26, 27","Gal 3:1-14","Jhn 10"],
    ana: 2,
  },
  {
    gregorianMonth: 10,
    gregorianDay: 31,
    gregorianDate: "Oct 31",
    ethiopianDate: "1/25",
    morning: ["Num 30","Gal 3:15-29","Jhn 9"],
    qidase: {
      epistle: "Heb  12 : 11 - 25",
      catholicEpistle: "1Pt  4 : 6 - 12",
      acts: "Act  20  : 31 - f",
      psalm: "Ps 24:10",
      gospel: "Luk  4 : 27 - 33"
    },
    evening: ["Num            31","Gal 4:1-11","Jhn 12"],
    ana: 3,
  }
];
