/** Auto-generated by scripts/build-lectionary-readings.mjs — do not edit by hand. */
import type { DayReadings } from './types';

export const septemberReadings: DayReadings[] = [
  {
    gregorianMonth: 9,
    gregorianDay: 1,
    gregorianDate: "Sep 1",
    ethiopianDate: "12/25",
    morning: ["Sir 42","Jam 5","Jhn 3"],
    qidase: {
      epistle: "Heb  11 : 8 - 17",
      catholicEpistle: "1Pt  3 : 1 - 10",
      acts: "Act 16 : 1 - 17",
      psalm: "Ps 127 : 3",
      gospel: "UNCLEAR - please verify"
    },
    evening: ["Luk 20 : 5 - 8","1Pt 1:1-12","Jhn 4"],
    ana: null,
  },
  {
    gregorianMonth: 9,
    gregorianDay: 2,
    gregorianDate: "Sep 2",
    ethiopianDate: "12/26",
    morning: ["Sir 44","1Pt  1:13-25","Jhn 5"],
    qidase: {
      epistle: "Heb 5 : 1 - 10",
      catholicEpistle: "1Pt  3 : 14 - f",
      acts: "Act  3 : 17 -  f",
      psalm: "Ps 98 : 6- 7",
      gospel: "Jhn 12 : 26 - 31"
    },
    evening: ["Sir       45","1Pt 2","Jhn 6"],
    ana: 10,
  },
  {
    gregorianMonth: 9,
    gregorianDay: 3,
    gregorianDate: "Sep 3",
    ethiopianDate: "12/27",
    morning: ["Sir 46","1Pt  3","Jhn 7"],
    qidase: {
      epistle: "Rom  4 : 1 - 23",
      catholicEpistle: "Jam  2 : 20 - f",
      acts: "Act  7 : 1 - 9",
      psalm: "Ps 120 : 1- 2",
      gospel: "Mat  22 : 23 - 34"
    },
    evening: ["Sir         47","1Pt  4:1-11","Jhn 8"],
    ana: 4,
  },
  {
    gregorianMonth: 9,
    gregorianDay: 4,
    gregorianDate: "Sep 4",
    ethiopianDate: "12/28",
    morning: ["Sir 48","1Pt  4:12-19","Jhn 9"],
    qidase: {
      epistle: "Gal  3 : 15 - 21",
      catholicEpistle: "1Jn  4 : 9 - 18",
      acts: "Ac  20 : 28 - 34",
      psalm: "Ps  100 : 2",
      gospel: "Mat  5 : 1 - 17"
    },
    evening: ["Sir         49","1Pt  5","Jhn 10"],
    ana: 2,
  },
  {
    gregorianMonth: 9,
    gregorianDay: 5,
    gregorianDate: "Sep 5",
    ethiopianDate: "12/29",
    morning: ["Sir 50","2Pt  1","Jhn 11"],
    qidase: {
      epistle: "Heb  11 : 32 - f",
      catholicEpistle: "Jud  1 : 17 - f",
      acts: "Act  1 : 12 - 15",
      psalm: "Ps 100 : 6, 7   Mrk 1:1 - 9",
      gospel: "UNCLEAR - please verify"
    },
    evening: ["Sir         51","2Pt  2","Jhn 12"],
    ana: 1,
  },
  {
    gregorianMonth: 9,
    gregorianDay: 6,
    gregorianDate: "Sep 6",
    ethiopianDate: "12/30",
    morning: ["2Pt 3","Jhn 13","Pl  1 : 12 - 25"],
    qidase: {
      catholicEpistle: "1Jn  5 : 1 - 7",
      acts: "Ac  18 : 21 - f",
      psalm: "Ps  83 : 11",
      gospel: "Mt  14 : 1 - 7"
    },
    evening: ["Brk         2","1Jn 1","Jhn 14"],
    ana: 2,
  },
  {
    gregorianMonth: 9,
    gregorianDay: 7,
    gregorianDate: "Sep 7",
    ethiopianDate: "13/1",
    morning: ["1Jn 2","Jhn 15","Tt  1 : 1 - 11"],
    qidase: {
      catholicEpistle: "2Pt  3 : 6 - 14",
      acts: "Ac  4:31 - 36",
      psalm: "Ps 110 : 10",
      gospel: "Lk 10:1-12"
    },
    evening: ["Brk         4","1Jn 3","Jhn 16"],
    ana: 1,
  },
  {
    gregorianMonth: 9,
    gregorianDay: 8,
    gregorianDate: "Sep 8",
    ethiopianDate: "13/2",
    morning: ["Festal hiatus","Ps 109:3, 5","Hb  7 : 1 - 5","Jd 1 : 11 - 17"],
    qidase: {
      acts: "Ac  5:17-26",
      psalm: "Ps 49 :2, 3",
      gospel: "Mt  25 : 31 - f"
    },
    evening: ["Brk       5","1Jn 4","Jhn 17"],
    ana: 13,
  },
  {
    gregorianMonth: 9,
    gregorianDay: 9,
    gregorianDate: "Sep 9",
    ethiopianDate: "13/3",
    morning: ["1Jn 5","Jhn 18","2Tm  2 : 11 - f"],
    qidase: {
      catholicEpistle: "1Pt  5 : 1 - 6",
      acts: "Ac  15 : 19 - 25",
      psalm: "Ps 33 : 13,14",
      gospel: "Mt 18 : 23 - f"
    },
    evening: ["Sus","2Jn 1","Jhn 19"],
    ana: 13,
  },
  {
    gregorianMonth: 9,
    gregorianDay: 10,
    gregorianDate: "Sep 10",
    ethiopianDate: "13/4",
    morning: ["3Jn 1","Jhn 20","Hb  11 : 32 - f"],
    qidase: {
      epistle: "2 Pt  1 : 19 - f",
      acts: "Ac 13 : 1 - 12",
      psalm: "Ps 90 : 13,14",
      gospel: "Mt 5 : 1 - 19  Mk 16:15-19"
    },
    evening: ["Aza         1-34","Jud 1","Jhn 21"],
    ana: 5,
  },
  {
    gregorianMonth: 9,
    gregorianDay: 11,
    gregorianDate: "Sep 11",
    ethiopianDate: "13/5",
    morning: ["Hab 3","2Pt 3","Mt 25:31-46"],
    qidase: {
      epistle: "2Cr 5:17-f",
      catholicEpistle: "2Pt 3:8-f",
      acts: "Act 17:30-f",
      psalm: "Ps 95:2",
      gospel: "UNCLEAR - please verify"
    },
    evening: ["Luk 13:1-10","         Dan         12","Jhn 1:1-5"],
    ana: null,
  },
  {
    gregorianMonth: 9,
    gregorianDay: 12,
    gregorianDate: "Sep 12",
    ethiopianDate: "13/6",
    morning: ["Ps 64 : 11","Lk  4 : 16 - 23","2Cr  6 : 1 - 11"],
    qidase: {
      epistle: "Jm  5 : 8 - 13",
      acts: "Ac  5 : 12 - 17",
      psalm: "Ps 141 : 6,7",
      gospel: "Mt  11 : 1 - 20"
    },
    evening: ["Gen       1","Act 1","Mat 1"],
    ana: 1,
  },
  {
    gregorianMonth: 9,
    gregorianDay: 13,
    gregorianDate: "Sep 13",
    ethiopianDate: "13/7",
    morning: ["Ps 138:9, 10","Mt  14 : 1 - 13","1Cr  6:1-11"],
    qidase: {
      epistle: "Mk  6 : 14 - 30",
      catholicEpistle: "1Jn 3:10-16",
      acts: "Ac 13:24-28",
      psalm: "Ps 78:10, 11",
      gospel: "UNCLEAR - please verify"
    },
    evening: ["Gen       2","Act 2:1-21","Mat 2"],
    ana: 3,
  },
  {
    gregorianMonth: 9,
    gregorianDay: 14,
    gregorianDate: "Sep 14",
    ethiopianDate: "13/8",
    morning: ["Gen 3","Act 2:22-37","Mat 3"],
    qidase: {
      epistle: "2Ts  3 : 13 - f",
      catholicEpistle: "2Jn  1 : 8 - f",
      acts: "Ac  20 : 28 - 31",
      psalm: "Ps 55 : 13",
      gospel: "Mt 18:18-23"
    },
    evening: ["Gen       4","Act 3","Mat 4"],
    ana: 12,
  },
  {
    gregorianMonth: 9,
    gregorianDay: 15,
    gregorianDate: "Sep 15",
    ethiopianDate: "13/9",
    morning: ["Gen 5","Act 4","Mat 5"],
    qidase: {
      epistle: "1Tm  3 : 1 - 8",
      catholicEpistle: "1Pt  5 : 9 - f",
      acts: "Ac  7 : 44 - 51",
      psalm: "Ps 59 : 3, 5",
      gospel: "Jn  10 : 1 - 22"
    },
    evening: ["Gen         6","Act 5:1-16","Mat 6"],
    ana: 5,
  },
  {
    gregorianMonth: 9,
    gregorianDay: 16,
    gregorianDate: "Sep 16",
    ethiopianDate: "13/10",
    morning: ["Gen 7","Act 5:17-42","Mat 7"],
    qidase: {
      epistle: "1Tm  5 : 1 - 7",
      catholicEpistle: "1Pt  3 : 5 - 10",
      acts: "Act  16 : 8 - 16",
      psalm: "Ps 44 : 9, 10",
      gospel: "Mat  13 : 31 - 44"
    },
    evening: ["Gen 8","Act 6:1-30","Mat 8"],
    ana: 5,
  },
  {
    gregorianMonth: 9,
    gregorianDay: 17,
    gregorianDate: "Sep 17",
    ethiopianDate: "13/11",
    morning: ["Gen 9, 10","Act 7:1-34","Mat 9"],
    qidase: {
      epistle: "Rom  9 : 25 - f",
      catholicEpistle: "2Pt  1 : 19 - f",
      acts: "Act  28 : 25 - f",
      psalm: "Ps 104 : 14, 15",
      gospel: "Jhn  12 : 36 - f"
    },
    evening: ["Gen 11, 12","Act 7:35-60","Mat 10"],
    ana: 3,
  },
  {
    gregorianMonth: 9,
    gregorianDay: 18,
    gregorianDate: "Sep 18",
    ethiopianDate: "13/12",
    morning: ["Gen 13","Act 8:1-25","Mat 11"],
    qidase: {
      epistle: "Heb  13 : 13 - 22",
      catholicEpistle: "1Pt  3 : 14 - 18",
      acts: "Act  16 : 16 - 22",
      psalm: "Ps 83 : 6, 7",
      gospel: "Mrk 1 : 23 - 29"
    },
    evening: ["Gen 14","Act 8:26-40","Mat 12"],
    ana: 4,
  },
  {
    gregorianMonth: 9,
    gregorianDay: 19,
    gregorianDate: "Sep 19",
    ethiopianDate: "13/13",
    morning: ["Festal hiatus","Jud  1 : 9 - 12","Act  7 : 30 - 39","Ps 131:9    Ps 57:10,11"],
    qidase: {
      psalm: "UNCLEAR - please verify",
      gospel: "Mat  23 : 29 - f"
    },
    evening: ["Gen 15","Act 9","Mat 12:28-40"],
    ana: 9,
  },
  {
    gregorianMonth: 9,
    gregorianDay: 20,
    gregorianDate: "Sep 20",
    ethiopianDate: "13/14",
    morning: ["Gen 16","Act 10:1-29","Mat 13:1-30"],
    qidase: {
      epistle: "Rom  8 : 35 - f",
      catholicEpistle: "Jam  1 : 2 - 13",
      acts: "Act  20 : 16 - 22",
      psalm: "Ps 45 : 3, 4",
      gospel: "Mat  7 : 24 - f"
    },
    evening: ["Gen 17","Act 10:30-38","Mat 13:31-58"],
    ana: 13,
  },
  {
    gregorianMonth: 9,
    gregorianDay: 21,
    gregorianDate: "Sep 21",
    ethiopianDate: "13/15",
    morning: ["Gen 18","Act 11","Mat 14"],
    qidase: {
      epistle: "Rom  3 : 1 - f",
      catholicEpistle: "Jam  3 : 13 - f",
      acts: "Act 1:12-15",
      psalm: "Ps 44:9, 10",
      gospel: "Mat 25 : 1 - 14"
    },
    evening: ["Gen  19","Act 12","Mat 15:1-20"],
    ana: 4,
  },
  {
    gregorianMonth: 9,
    gregorianDay: 22,
    gregorianDate: "Sep 22",
    ethiopianDate: "13/16",
    morning: ["Gen 20","Act 13:1-15","Mat 15:21-39"],
    qidase: {
      epistle: "Heb  12 : 1 - 12",
      catholicEpistle: "Jam 3 : 1 - 13",
      acts: "Act  10:1- 9",
      psalm: "Ps 78 : 10, 11",
      gospel: "Luk  21 : 12 - 21"
    },
    evening: ["Gen 21","Act 13:16-52","Mat 16"],
    ana: 7,
  },
  {
    gregorianMonth: 9,
    gregorianDay: 23,
    gregorianDate: "Sep 23",
    ethiopianDate: "13/17",
    morning: ["Gen 22","Act 14","Mat 17"],
    qidase: {
      epistle: "1Cr  5 : 3   - 11",
      catholicEpistle: "Jud 1 : 9 - 20",
      acts: "Act  20:28-31",
      psalm: "Ps 33:7, 8",
      gospel: "Mat  18 : 15 - 19"
    },
    evening: ["Gen 23","Act 15:1-12","Mat 18"],
    ana: 11,
  },
  {
    gregorianMonth: 9,
    gregorianDay: 24,
    gregorianDate: "Sep 24",
    ethiopianDate: "13/18",
    morning: ["Gen 24","Act 15:13-41","Mat  19:1-15"],
    qidase: {
      epistle: "1Cr 7 : 12 - 18",
      catholicEpistle: "Jm  5 : 14 - 17",
      acts: "Ac  19:17-21",
      psalm: "Ps 31 :1, 2",
      gospel: "Luk  11 : 5 - 14"
    },
    evening: ["Gen 25","Act 161-15","Mat 19:16-30"],
    ana: 7,
  },
  {
    gregorianMonth: 9,
    gregorianDay: 25,
    gregorianDate: "Sep 25",
    ethiopianDate: "13/19",
    morning: ["Gen 26","Act 17","Mat 20:1-19"],
    qidase: {
      epistle: "1Cr  14 : 34 - f",
      catholicEpistle: "1Jn  2 : 18 - 21",
      acts: "Act  5:11-17",
      psalm: "Ps 59: 3, 5",
      gospel: "Mat  14 : 22 - f"
    },
    evening: ["Gen 27","Act 18","Mat 20:20-30"],
    ana: 3,
  },
  {
    gregorianMonth: 9,
    gregorianDay: 26,
    gregorianDate: "Sep 26",
    ethiopianDate: "13/20",
    morning: ["Gen 28","Act 19:1-20","Mat 21:1-32"],
    qidase: {
      epistle: "2Cr  3 : 12 - f",
      catholicEpistle: "2Pt  2 : 15 - f",
      acts: "Act 7:55-f",
      psalm: "Ps 64:3, 4",
      gospel: "Luk 10:30-38"
    },
    evening: ["Gen 29","Act 19:21-40","Mat 21:33-46"],
    ana: 3,
  },
  {
    gregorianMonth: 9,
    gregorianDay: 27,
    gregorianDate: "Sep 27",
    ethiopianDate: "13/21",
    morning: ["Gen 30","Act 20:1-16","Mat 23"],
    qidase: {
      epistle: "1Cr  3 : 10 - 18",
      catholicEpistle: "Jam  1 : 19 - f",
      acts: "Act  15:13-21",
      psalm: "Ps 50:18, 19  Jhn  10:22 - f",
      gospel: "UNCLEAR - please verify"
    },
    evening: ["Gen 31","Act 20:17-38","Mat 22"],
    ana: 4,
  },
  {
    gregorianMonth: 9,
    gregorianDay: 28,
    gregorianDate: "Sep 28",
    ethiopianDate: "13/22",
    morning: ["Festal hiatus","Ps 83 : 6, 7","Mt  5 : 1 - 17-16","1Tm  5 : 9 - 16"],
    qidase: {
      catholicEpistle: "Jam  3 : 11 - f",
      acts: "Act  5:26 - 33",
      psalm: "Ps 31:6, 7  Jhn  19:25-28",
      gospel: "UNCLEAR - please verify"
    },
    evening: ["Gen 32","Act 21:1-16","Mat 24:1-35"],
    ana: 10,
  },
  {
    gregorianMonth: 9,
    gregorianDay: 29,
    gregorianDate: "Sep 29",
    ethiopianDate: "13/23",
    morning: ["Gen 33","Act 21: 17-40","Mat 24:36-51"],
    qidase: {
      epistle: "Rm 10 : 11 - f",
      catholicEpistle: "2Pt  3 : 14 - f",
      acts: "Act  14 : 26 - f",
      psalm: "Ps 88 : 8-10",
      gospel: "Lk  15 : 8  - 10"
    },
    evening: ["Gen 34","Act 22, 23","Mat 25:1-30"],
    ana: 5,
  },
  {
    gregorianMonth: 9,
    gregorianDay: 30,
    gregorianDate: "Sep 30",
    ethiopianDate: "13/24",
    morning: ["Gen 35","Act 24","Mat 25:31-46"],
    qidase: {
      epistle: "Eph  2 : 13 - f",
      catholicEpistle: "1Pt  5 : 1 - 5",
      acts: "Act  10 : 9 - 24",
      psalm: "Ps 83:6, 7     Jhn  10:1-22",
      gospel: "UNCLEAR - please verify"
    },
    evening: ["Gen 36","Act 25","Mat 26:1-47"],
    ana: 3,
  }
];
