/** Generated by scripts/build-media-21-catalog.mjs — do not edit by hand. */
export const MEDIA_21_CHANNEL = "21 MEDIA ሃያ አንድ ሚዲያ" as const;

export const MEDIA_21_CHANNEL_HANDLE = "@21media27" as const;

export const MEDIA_21_CHANNEL_ID = "UCn0hmEGoyL_tgNAOB-myXPw" as const;

export type Media21Track = { videoId: string; title: string };

export const MEDIA_21_TRACKS: Media21Track[] = [
  {
    "videoId": "qdiHtqotjcA",
    "title": "አንቺን ብቻ ቤተልሄም | Anchi Bicha Betelhem"
  },
  {
    "videoId": "aQBVWjteBic",
    "title": "ክበር ባለኝ ነገር | ያላንተ ለኔ — ዘማሪት ምርትነሽ ጥላሁን"
  },
  {
    "videoId": "sF7kwoWrkZs",
    "title": "እንዴት እንዳለፍኩት አላውቅም — ዘማሪ ቀነኒሳ ታቦር"
  },
  {
    "videoId": "ISvPD4aQxEo",
    "title": "በልቤ ከተማ | ክብሬ ነው ክብርህን መናገሬ | ማርያም እንወድሻለን | ጉባዔ ቃለ አዋዲ"
  },
  {
    "videoId": "01eOiu_kWb0",
    "title": "የጌታዬ እናት — ዘማሪት አዲላ አብዱራህማን"
  },
  {
    "videoId": "-Wz6h9SImiU",
    "title": "በንጹሕ ደሙ ያዳነን \"ሰባቱ መንጦላይት\" — ዲያቆን ብስራት ጨብሲ እና ዲያቆን ዮሴፍ ግርማ"
  },
  {
    "videoId": "-7sAGvDFQ7g",
    "title": "እኛ ግን የተሰቀለውን ክርስቶስን እንሰብካለን | በቸርነት | የወይን ሐረግ ነሽ — ዘማሪ ሐዋዝ ተገኝ እና ዘማሪ እዝራ ኃ/ሚካኤል"
  },
  {
    "videoId": "DMapbvQOg38",
    "title": "በታላቅ ጉባኤ ፊት | ሂዱ ንገሩ አውሩ ለዓለም | ለማርያም እንዘምራለን — ዘማሪት ሣራ መንግስቱ እና ዘማሪት በጸሎት አስማረ"
  },
  {
    "videoId": "J2hLOTaSUU8",
    "title": "ማረኝ — ዘማሪት ብሩክታዊት ንጋቱ"
  },
  {
    "videoId": "-S1nViKka4k",
    "title": "በአባቴ ቤት — ዘማሪት ሣራ መንግስቱ"
  },
  {
    "videoId": "AfXU0XW7K6g",
    "title": "መፃጉዕ — ዘማሪ ቀነኒሳ ታቦር"
  },
  {
    "videoId": "g3IXGqDqAcQ",
    "title": "ምኩራብ — ዘማሪት እድላዊት ፍሬው"
  },
  {
    "videoId": "xbLotxK_Phk",
    "title": "ቅድስት — ዘማሪ ዘ-ፋኑኤል አለቃ"
  },
  {
    "videoId": "2funaeuPSm4",
    "title": "ዘወረደ — ዘማሪት ኤደን ነዋይ"
  },
  {
    "videoId": "ivLrjXJg92I",
    "title": "እግዚአብሔር የወደቁትን ያነሳል | ምልክቴ ነሽ | ላመስግንህ የኔ ጌታ — ዲያቆን አቤል መክብብ"
  },
  {
    "videoId": "bkzgL-hvw-g",
    "title": "መድኃኔዓለም የለም የሚሳነው | ቸሩ ሆይ | በኤፍራታ ምድር — ዘማሪት ሲስተር ሕይወት ተፈራ"
  },
  {
    "videoId": "nlWA8nmdBzY",
    "title": "ከልዑላን ይልቅ | ውበት ነሽ ለቤቴ | ቸርነትህ ነው — ሊቀ ዲያቆናት ቀዳሜጸጋ ዮሐንስ"
  },
  {
    "videoId": "HgKnisFY8sI",
    "title": "ከኃጢአተኛው ድንኳን — ዲያቆን አቤል መክብብ"
  },
  {
    "videoId": "4n1fXF6Gmn4",
    "title": "ድንቅ አድርጎልኛል — ዲያቆን ፍሬዘር ደሳለኝ"
  },
  {
    "videoId": "0K2x9dsPUT4",
    "title": "ኪዳነ ምሕረት | ድንቅ አድርጎልኛል — ዲያቆን ፍሬዘር ደሳለኝ"
  },
  {
    "videoId": "FwGQQd5IO-g",
    "title": "በምን ደስ ላሰኝህ | የወደደኝ ጌታ ምን አድርጌለት ነው — ሙሐዘ ስብሀት ዳግማዊ ደርቤ"
  },
  {
    "videoId": "2yeqHrrSRlg",
    "title": "አለ በመንግስቱ ስንገፋ የሚያይ — ዘማሪት ኤደን ነዋይ"
  },
  {
    "videoId": "hjvoSEEqQbQ",
    "title": "እወድሃለው አበቱ ጉልበቴ | ሚካኤል የዋህ — ዘማሪ ይትባረክ ተገኝ"
  },
  {
    "videoId": "KhLA2Gxjd80",
    "title": "በማይነገር ስጦታ | ምስጢረኛዬ — ዲያቆን አቤል መክብብ"
  },
  {
    "videoId": "SPdEoGrVbEE",
    "title": "ስንቱን አለፍኩት ባንቺ ወጣው ስንቱን ተራራ — ዲያቆን ብስራት ጨብሲ"
  },
  {
    "videoId": "ax14PptUDII",
    "title": "ስንት ጊዜ ረዳሸኝ — ዘማሪት ኤደን ነዋይ"
  },
  {
    "videoId": "vL0VZ9YtKoU",
    "title": "በዘመናት የሸመገለ — ዲያቆን ፍሬዘር ደሳለኝ"
  },
  {
    "videoId": "m6fLoMb8KJ0",
    "title": "ቅዱስ ሚካኤል ፈጥኖ ደረሰልኝ — ዲያቆን ብስራት ጨብሲ"
  },
  {
    "videoId": "LxeCYEgdtF4",
    "title": "እወድሀለሁ አቤቱ ጉልበቴ — ዘማሪት ናርዶስ ካሳሁን"
  },
  {
    "videoId": "HUJssq30p0I",
    "title": "ልቤም ሲፈራ — ዘማሪት ብሩክታዊት ንጋቱ"
  },
  {
    "videoId": "m2DC0-OKUdg",
    "title": "የሲሎንዲስ ጥበብ — ዲያቆን ዮሴፍ ግርማ"
  },
  {
    "videoId": "2JSjkH7nac0",
    "title": "ለነፍሴ ነፍሷ ነሽ ለመንገዴ ፋና — ዲያቆን ብስራት ጨብሲ"
  },
  {
    "videoId": "0XLwMk6REAE",
    "title": "እመቤቴ ስልሽ ነይልኝ ለልጅሽ — ዘማሪት ናርዶስ ካሳሁን"
  },
  {
    "videoId": "iUz-CFYqU7I",
    "title": "ታውቂዋለሽና የእኔን ድካም ምግባር እንደሌለኝ — ዘማሪት ብሩክታዊት ንጋቱ"
  },
  {
    "videoId": "c2CqleWeW30",
    "title": "ነይ ነይ እምዬ ማርያም | ገብርኤል በሰማይ | በዘባነ ኪሩብ — ዲያቆን ፍሬዘር ደሳለኝ"
  },
  {
    "videoId": "464ex6BSVaw",
    "title": "ውለታህ ብዙ ተነግሮ አያልቅም — ዲያቆን ዮሴፍ ግርማ"
  },
  {
    "videoId": "J27aIoNDsFY",
    "title": "ነይ ነይ እመቤቴ — ዲያቆን ብስራት ጨብሲ"
  },
  {
    "videoId": "KEnYshUTClc",
    "title": "ሚካኤል ሚካኤል ይላል አንደበቴ — ዘማሪት ሣራ መንግስቱ"
  },
  {
    "videoId": "qLriQEvMH78",
    "title": "የተሻለ ነገር አስበህልኝ ነው — ዘማሪት እድላዊት ፍሬው"
  },
  {
    "videoId": "_hzTV-dIe5s",
    "title": "እቴ ሙሽራዬ | ግቢ ገብርኤል — ዲያቆን ፍሬዘር ደሳለኝ"
  },
  {
    "videoId": "SQC2Fl1031o",
    "title": "ቀኑ ከረፈደ ከመሸብኝ መጣሁ — ዘማሪ ይትባረክ ተገኝ"
  },
  {
    "videoId": "JFNg8RdS7T8",
    "title": "ማነው በፍቅሩ ያልተለወጠ — ዘማሪ ዘ-ፋኑኤል አለቃ"
  },
  {
    "videoId": "IsPmNpHKSj8",
    "title": "እርሱ ብቻ የማይሞት ነው — ዘማሪት ኤደን ነዋይ"
  },
  {
    "videoId": "aRlhWji2sno",
    "title": "ጌታ ተነስቷል"
  },
  {
    "videoId": "tMLOWlND7gE",
    "title": "የትኛው ስራዬ — ዲያቆን ብስራት ጨብሲ"
  },
  {
    "videoId": "zyvR2jTLkDI",
    "title": "የጴጥሮስን እንባ — ዘማሪት ሳራ መንግስቱ"
  },
  {
    "videoId": "3yJP8CHKwqQ",
    "title": "የያረድ ውብ ዜማ || አላፋት Ethiopian Orthodox Christian Amharic Song || Mekedonia Fundraising"
  },
  {
    "videoId": "786wgzpgb0k",
    "title": "ልቤ ያውቀዋል ያደረክልኝን ነገር — ዘማሪ ቀነኒሳ ታቦር"
  },
  {
    "videoId": "ZkElTtiRL9E",
    "title": "የፃድቅ ሰው ፀሎት — ዘማሪ ዘ-ፋኑኤል አለቃ"
  },
  {
    "videoId": "AdpvFA-d2dw",
    "title": "የኔ መሀሪ ሁሉን መርሻዬ — ዘማሪት ኤደን ነዋይ"
  },
  {
    "videoId": "13z5pjKvvKw",
    "title": "አንተ ከኔ ጋር ነህ አማኑኤል — ዘማሪት ሲስተር ሕይወት ተፈሪ"
  },
  {
    "videoId": "Nx_DASLLzVE",
    "title": "ሰላም ለኪ — ዲያቆን ፍሬዘር ደሳለኝ"
  },
  {
    "videoId": "BiFNT0Annqo",
    "title": "ሚካኤል ስለው ስሙን ስጠራ — ዘማሪት ብሩክታዊት ንጋቱ"
  },
  {
    "videoId": "xyCOkCMT8Tw",
    "title": "እኔስ ተስፋ አልቆርጥም — ዘማሪት ብሩክታዊት ንጋቱ"
  },
  {
    "videoId": "4Y1JO1atadI",
    "title": "አክሊለ ፅጌ ማርያም||እንዘ ተሐቅፊዮ"
  },
  {
    "videoId": "YvZtB-EoZFg",
    "title": "እግዚአብሔር ነው — ዘማሪት ናርዶስ ካሳሁን"
  },
  {
    "videoId": "oew14q3j9B4",
    "title": "ያለ አንተ ማን አስቦኛል — ዘማሪት ሳራ መንግሥቱ"
  },
  {
    "videoId": "_lisID8pRPg",
    "title": "ስድቤን አርቀሽ ነውሬን ሸፈንሽው — ዘማሪት ብሩክታዊት ንጋቱ"
  },
  {
    "videoId": "XxOXcy39pGs",
    "title": "በምን በምን እንመስላት ድንግል ማርያምን"
  },
  {
    "videoId": "JiyDanITec8",
    "title": "እኔስ በምግባሬ ደካማ ሆኛለሁ — ዲያቆን ዮሐንስ አድማሱ"
  },
  {
    "videoId": "--W1cHBSlzc",
    "title": "አቤቱ የሆነብንን አስብ || አንድ አድርገን || አርቲስት እህቶቻችን ለቤተክርስቲያናችሁ ድምፅ ስለሆናችሁ እናመሰግናለን!"
  },
  {
    "videoId": "3C1yVWRY3KQ",
    "title": "ምክንያት ስላለኝ ነው — ዘማሪት ሳራ መንግስቱ"
  },
  {
    "videoId": "pUQ4lWUba28",
    "title": "ደጅ ጠናሁ ቆይቼ ኪዳነ ምህረትን — ዘማሪት ናርዶስ ካሳሁን"
  },
  {
    "videoId": "gB1Z2OBR4KQ",
    "title": "አንተ ደጉ ሳምራዊ — ዲ/ን ዳዊት ጥላሁን"
  },
  {
    "videoId": "u9UkmqJQ2ks",
    "title": "ዮሐንስን ይዛ — ዘማሪት ሳራ መንግሥቱ"
  },
  {
    "videoId": "VAqqbfrGmXw",
    "title": "ወየው አንድ ልጄ — ዘማሪት በጸሎት አስማረ"
  },
  {
    "videoId": "ZdIf31zYr5Y",
    "title": "ሃሌ ሉያ — ዲ/ን ቅዱስ ዮሴፍ"
  },
  {
    "videoId": "pE5G5NLYoqw",
    "title": "ይህችን ዓመት ተወኝ — ዲ/ን ዳዊት ጥላሁን"
  },
  {
    "videoId": "szfuDFp9CYk",
    "title": "ምናል ብታስተምረኝ — ዘማሪት ሳራ መንግስቱ"
  },
  {
    "videoId": "3fGDGrdbCcI",
    "title": "ተወልደ ናሁ እም ድንግል"
  },
  {
    "videoId": "TSrrFXiwcq0",
    "title": "ኑ በእግዚአብሔር ደስ ይበለን | ስምሽን ጠርቼ መቼ አፍራለሁ — ዘማሪት አዜብ ከበደ"
  },
  {
    "videoId": "lyRtaASx6fI",
    "title": "ዛሬም አለሽ በልቤ — ዘማሪት ናርዶስ ካሳሁን"
  },
  {
    "videoId": "Q9nwbBYj-TU",
    "title": "አኑሮኛል ቸርነትህ | ስምሽን ለልጅ ልጅ — ዘማሪት ምርትነሽ ጥላሁን"
  },
  {
    "videoId": "tihJJuMLNns",
    "title": "ወዶናልና ዳግም አይጠላንም — ዘማሪት ባንቺአየሁ ሰይፉ"
  },
  {
    "videoId": "uUnNIOzaH7Q",
    "title": "ተሰድጄም ሀገር አለኝ — ዲያቆን ዮሐንስ አድማሱ"
  },
  {
    "videoId": "Gi0bJib4HJg",
    "title": "በቃልህ ልኑር — ዲ/ን ቅዱስ ዮሴፍ"
  },
  {
    "videoId": "MxYBiFf9hrQ",
    "title": "በውስጥ ሰውነቴ — ዘማሪት ናርዶስ ካሳሁን"
  },
  {
    "videoId": "i-1rWDpTKnw",
    "title": "ከታናሽነቴ ጀምረህ — ዘማሪት በጸሎት አስማረ"
  },
  {
    "videoId": "0XiWIoGe79A",
    "title": "ባርክ ለነ"
  },
  {
    "videoId": "f7xynYvk1CY",
    "title": "አለማመኔን እርዳው ጌታዬ — ዲያቆን ማኅደረልዑል ፍሰሃ"
  },
  {
    "videoId": "wcBJ4sA6_aE",
    "title": "ማነው ሚቆመው ፊትህ — ዘማሪት መቅደላዊት ንጋቱ"
  },
  {
    "videoId": "wPzL1iOxqkM",
    "title": "ከማህፀን እስከ ሽምግልና — ዘማሪት ሳራ መንግስቱ"
  },
  {
    "videoId": "u1n9ZS1KkGU",
    "title": "ገብርኤል በሰማይ ኤልሳቤጥ በምድር — ዲ/ን ዳዊት ጥላሁን"
  },
  {
    "videoId": "mD1MCJ1E4tw",
    "title": "የጎጆዬ ሰላም — ዘማሪት ፌቨን እዮብ"
  },
  {
    "videoId": "JT-AmVzmnRM",
    "title": "ምስለ ፍቁር ወልዳ — ዲያቆን ብስራት ጨብሲ"
  },
  {
    "videoId": "66VjQkgnVRM",
    "title": "ድንግል እናቴ ነይ ድረሽልኝ — ዘማሪት ናርዶስ ካሳሁን"
  },
  {
    "videoId": "OIsGs74_-8U",
    "title": "ድንግል እናታችን — ዘማሪት ሲስተር ሕይወት ተፈሪ"
  },
  {
    "videoId": "3vfwQZSlIq8",
    "title": "እመኑ በእርሱ ድንቅ ያደርጋል ጌታ"
  },
  {
    "videoId": "aTZfT71HDec",
    "title": "በድንኳኔ እልልታ ሙሉ ነው — ዘማሪ ይትባረክ ተገኝ"
  },
  {
    "videoId": "iCDcaz9bJY4",
    "title": "ክብሬ ነው ክብርህን መናገሬ — ዘማሪ ቀሲስ ምንዳዬ ብርሃኑ"
  },
  {
    "videoId": "zU2uOZ58TH8",
    "title": "ቸርነትህ ነው ያደረሰኝ እስከ ዛሬ — ዘማሪት ሩታ ደመላሽ"
  },
  {
    "videoId": "DI2IIu5OflQ",
    "title": "የጌታዬ እናት ማርያም — ዘማሪት ወርቅነሽ ኃይሉ"
  },
  {
    "videoId": "cf9IT88IuME",
    "title": "ቅኔ ከአፌ ፈሰሰ — ዘማሪት ሳምራዊት አበበ"
  },
  {
    "videoId": "3T6Pd2pjYSI",
    "title": "የመልካሞች መልካም — ዲያቆን ብስራት ጨብሲ"
  },
  {
    "videoId": "LbgEETYaVhk",
    "title": "ማርያም እንወድሻለን"
  },
  {
    "videoId": "lpQSJtjn_nE",
    "title": "በእናቴ እቅፍ ልጅ ሆኜ ገና — ዘማሪት በጸሎት አስማረ"
  },
  {
    "videoId": "_-xtweOBWlg",
    "title": "ልቤ በእግዚአብሔር ጸና — ዘማሪት ሔዋን ጌታቸው"
  },
  {
    "videoId": "eqMN7pUH36Y",
    "title": "ማሪኝ እና ልሂድ — ዘማሪት ናርዶስ ካሳሁን"
  },
  {
    "videoId": "iLv9ssVlX30",
    "title": "ሰላሜ ባንተ ነው — ዲያቆን ማኅደረልዑል ፍሰሃ"
  },
  {
    "videoId": "W5O3vZz8PQg",
    "title": "ደጅሽ ላይ ቆሜ እጠራሻለሁ — ዘማሪት ባንቺአየሁ ሰይፉ"
  },
  {
    "videoId": "JysZ3QKsiYg",
    "title": "ያለፈው ዘመኔ ይበቃኛል — ዲ/ን ቅዱስ ዮሴፍ"
  },
  {
    "videoId": "sDcw9Rd7LP8",
    "title": "መክፈል የማልችለው አለብኝ ውለታ — ዘማሪት ጤናዬ አሰፋ"
  },
  {
    "videoId": "Ac6t3IzVVCI",
    "title": "ስምሽን ስጠራው — ዲያቆን ዮሴፍ ግርማ"
  },
  {
    "videoId": "1uW66MKOnOU",
    "title": "ተነስቷል በዚህ የለም || ሂዱ ንገሩ አውሩ ለዓለም"
  },
  {
    "videoId": "izZZulTXA6E",
    "title": "ሆሳዕና በአርያም hosanna"
  },
  {
    "videoId": "C17dl-hpNis",
    "title": "ጌታዬ ሆነ ደም ግባት አልባ — ዲያቆን ብስራት ጨብሲ"
  },
  {
    "videoId": "DRbJHgfy3Y0",
    "title": "አዘነች ድንግል አለቀሰች — ዘማሪት ናርዶስ ካሳሁን"
  },
  {
    "videoId": "KfBLTe--EJo",
    "title": "ወልድን ፍቅር ሳበው — ዘማሪት ሳራ መንግስቱ"
  },
  {
    "videoId": "mjrKxC0727A",
    "title": "ዓለምን ለማዳን የተሰቀለው — ዘማሪት ቤተልሔም ሙሉጌታ"
  },
  {
    "videoId": "bZK_uiLHuwY",
    "title": "ሀሌ ሀሌ ሉያ — ዲያቆን ዮሐንስ አድማሱ"
  },
  {
    "videoId": "SSdJ_9Mp99A",
    "title": "Eskemaezenu \"እስከ ማዕዜኑ\" — ዲያቆን ዮሴፍ ግርማ"
  },
  {
    "videoId": "--w9A-moMBQ",
    "title": "አንቺ ነሽ ተስፋው ለፍጥረት — ዲ/ን ዳዊት ጥላሁን"
  },
  {
    "videoId": "tNsOXu0UqPM",
    "title": "ስለረዳሽኝ እመቤቴ አወድስሻለሁ — ዘማሪት ጤናዬ አሰፋ"
  },
  {
    "videoId": "CJjBFIVphJw",
    "title": "ላመስግንህ የእኔ ጌታ — ዘማሪት ናርዶስ ካሳሁን"
  },
  {
    "videoId": "AUr_qM0SCNI",
    "title": "ውበት ነሽ ለቤቴ ለኑሮዬ ፋና — ዘማሪት ቤተልሔም ሙሉጌታ"
  },
  {
    "videoId": "9x42zIjhIHI",
    "title": "እውነተኛ ሰላም ያለው ከቤትህ ነው — ዘማሪት በጸሎት አስማረ"
  },
  {
    "videoId": "p3PoIgrmsL8",
    "title": "ድንግል ሆይ ወደኔ ትመጪ ዘንድ — ዲ/ን ሳይዛና ጌታቸው"
  },
  {
    "videoId": "MTrn3ZukLD0",
    "title": "የልቤን በልቤ ይዤ ከፊትሽ ቆሚያለው — ዘማሪት ናርዶስ ካሳሁን"
  },
  {
    "videoId": "fbMv8pB87R8",
    "title": "እንደ እኔ የማርከው ማንን ነው — ዲያቆን ብስራት ጨብሲ"
  },
  {
    "videoId": "l9QF2M351jI",
    "title": "ዘማሪት ሲስተር ልድያ ታደሰ — የእምነትሽ ፅናት"
  },
  {
    "videoId": "793laEbZIsc",
    "title": "ሰብሕዎ ለአምላክነ መዝሙር || ethiopian orthodox mezmur"
  },
  {
    "videoId": "III3Z4rGrRI",
    "title": "ስለ ማይነገር ስጦታው — ሊቀ ልሣናት ቸርነት ሰናይ"
  },
  {
    "videoId": "Shm5zguOQFM",
    "title": "ኦ እመቤቴ በእውነት እንወድሻለን — ሊቀ መዘምራን ቴዎድሮስ ዮሴፍ"
  },
  {
    "videoId": "_3eU5W4OBQ0",
    "title": "ዘማሪት ምርትነሽ ጥላሁን — ማርያም"
  },
  {
    "videoId": "SgiI6pa9O3o",
    "title": "አለ በሰማይ ስንገፋ የሚያይ — ዘማሪት መቅደስ ማርዬ"
  },
  {
    "videoId": "P4f3UzFcEc4",
    "title": "አበረታኝ ፍቅር — ዘማሪ ዳግማዊ ደርቤ"
  },
  {
    "videoId": "2tECbnl9vwE",
    "title": "የሰማይ ደጅ ናት — ዘማሪት ህይወት ወልዴ"
  },
  {
    "videoId": "xrDpoyBFTTY",
    "title": "እወድሃለው አቤቱ ጉልበቴ — ዘማሪ ይትባረክ ተገኝ"
  },
  {
    "videoId": "maGWtsd3RyM",
    "title": "ስለረዳሽኝ እመቤቴ አወድስሻለሁ — ሊቀ ልሣናት ቸርነት ሰናይ"
  },
  {
    "videoId": "xZGuxbMAqEM",
    "title": "እኔ አንተ ፊት — ሊቀ መዘምራን ቴዎድሮስ ዮሴፍ"
  },
  {
    "videoId": "vuEEFS1sxzs",
    "title": "Aniif Manni Koo Waqayoon — Farfatuu Mabiratee Taddasaa (Afan Oromo)"
  },
  {
    "videoId": "dMu9uZJ_x0s",
    "title": "የተሸከምከኝ ሆይ ዛሬም ተሸከመኝ — ዘማሪት ሕይወት ተፈሪ"
  },
  {
    "videoId": "8ijpPaq-7xQ",
    "title": "ጌታ ተነስቷል እልል በሉ — ዘማሪ ይትባረክ ተገኝ"
  },
  {
    "videoId": "TOjR7f258yg",
    "title": "በፍርድ አደባባይ — ዲያቆን ቀዳሜጸጋ ዮሐንስ"
  },
  {
    "videoId": "CJ8hy_HykdA",
    "title": "ልጅ እና አባት | ልጄ ሆይ — ዲያቆን ቀዳሜጸጋ ዮሐንስ"
  },
  {
    "videoId": "7HNSChgyRJU",
    "title": "አለብኝ ውለታ ፍቅሩን ልናገር — ዘማሪት የሮም መኮንን"
  }
];
