/** Generated by scripts/build-spot-church-catalog.mjs — do not edit by hand. */
export const SPOT_CHURCH_CHANNEL = "SPOT Church" as const;

export const SPOT_CHURCH_CHANNEL_ID = "UCtBsjKsdqdAFHv_snt-otmA" as const;

export type SpotChurchTrack = { videoId: string; title: string };

export type SpotChurchPlaylist = {
  id: string;
  album: string;
  tracks: SpotChurchTrack[];
};

export const SPOT_CHURCH_PLAYLISTS: SpotChurchPlaylist[] = [
  {
    "id": "rise-and-measure",
    "album": "Rise & Measure",
    "tracks": [
      {
        "videoId": "kGaqDpBNk18",
        "title": "Rise & Measure (Week 8)"
      },
      {
        "videoId": "SMXzw92LP7g",
        "title": "Rise & Measure (Week 6)"
      },
      {
        "videoId": "j-ln2mB-jjk",
        "title": "Rise & Measure (Week 5)"
      },
      {
        "videoId": "I23KaK8Tq10",
        "title": "Rise & Measure (Week 4)"
      },
      {
        "videoId": "Pyay0iBNzh8",
        "title": "Rise & Measure (Week 3)"
      },
      {
        "videoId": "63lkpU7ESc0",
        "title": "Rise & Measure (Week 2)"
      },
      {
        "videoId": "4VvXr9OYSdA",
        "title": "Rise & Measure (Week 1)"
      }
    ]
  },
  {
    "id": "great-lent-2026",
    "album": "Great Lent 2026",
    "tracks": [
      {
        "videoId": "r8oEIePeAsI",
        "title": "The Resurrection Of Christ"
      },
      {
        "videoId": "WpjEPKRG1h0",
        "title": "Why Are You Seeking the Living Among the Dead? || Holy 50 Reflection"
      },
      {
        "videoId": "C3lqJHOCxpY",
        "title": "The Three Running Souls || Resurrection Sunday"
      },
      {
        "videoId": "vpyBG03oVEA",
        "title": "Communion with Christ || Bright Saturday Reflection"
      },
      {
        "videoId": "441Yh60nkqc",
        "title": "Bring Your Brokenness to Christ || Good Friday Reflection"
      },
      {
        "videoId": "K4PpzcwKk68",
        "title": "Christ Still Wants You At The Table || Holy Thursday Reflection"
      },
      {
        "videoId": "z_KvxTLdovI",
        "title": "Abundance of Love || Holy Wednesday Reflection"
      },
      {
        "videoId": "yPOqrnZRjzU",
        "title": "Are You Ready for Christ? || Holy Tuesday Reflection"
      },
      {
        "videoId": "5eYEcDdiV6I",
        "title": "Conforming to the World || Holy Monday Reflection"
      },
      {
        "videoId": "9nvVKlFGjXA",
        "title": "Blessed is He, That Comes in the Name of the Lord, Hosanna in the Highest || Matthew 21: 1-11"
      },
      {
        "videoId": "J4gVYI2WJAo",
        "title": "Trust in the Lord || Lenten Reflection"
      },
      {
        "videoId": "KOKdoSgm0Ic",
        "title": "Your King is Here, O' Israel"
      },
      {
        "videoId": "k8m6Q04SIJw",
        "title": "In the Cover of Night || Lenten Reflection"
      },
      {
        "videoId": "Ua1rUhaUfMI",
        "title": "We Speak What We Know, And Testify What We Have Seen || John 3: 1-12"
      },
      {
        "videoId": "-SJqykgtfLQ",
        "title": "Psalm 40:8-9 || Reflection"
      },
      {
        "videoId": "tYmwJ98yEaw",
        "title": "The Lord Gives Intentionally"
      },
      {
        "videoId": "_PBjwG2CytY",
        "title": "Multiplying Talents || Lenten Reflection"
      },
      {
        "videoId": "fqYyI5bw91k",
        "title": "Psalm 50:2-3 || Reflection"
      },
      {
        "videoId": "dVNsDdiHnyA",
        "title": "I Will Make You Ruler of Many Things || Matthew 25: 14-40"
      },
      {
        "videoId": "kxL_4duJ4r4",
        "title": "My way vs. God's Way || Lenten Reflection"
      },
      {
        "videoId": "XTDK43PZY0Q",
        "title": "The Mount of Olives"
      },
      {
        "videoId": "w5fy0TfUbS8",
        "title": "Whoever Reads, Let Him Understand || Matthew 24: 1-36"
      },
      {
        "videoId": "Rx4GEwgGDAE",
        "title": "Paralysis || Lenten Reflection"
      },
      {
        "videoId": "iEfUs75_iO0",
        "title": "Do You Want to Be Made Well?"
      },
      {
        "videoId": "4MzUu-9XNCY",
        "title": "Healing Beyond the Pool || John 5: 1-25"
      },
      {
        "videoId": "T7ogmaKRONY",
        "title": "Sacrament of the Unction of the Sick Service"
      },
      {
        "videoId": "F0iplTH9lFA",
        "title": "Seek the Lord || Lenten Reflection"
      },
      {
        "videoId": "JQn7vTAr3lQ",
        "title": "Has Zeal for My Father's House Consumed Me?"
      },
      {
        "videoId": "npVckYdcC9g",
        "title": "Relinquishing Control || Lenten Reflection"
      },
      {
        "videoId": "NO-UnHTN1ls",
        "title": "Where is Your Treasure?"
      },
      {
        "videoId": "36BngGYej00",
        "title": "Your Father Who Is In a Secret Place Will Reward You Openly || Matthew 6: 16-24"
      },
      {
        "videoId": "3YgN8piZLbE",
        "title": "Christ’s Humble Descent || Lenten Reflection"
      },
      {
        "videoId": "Uar0M6o-3cc",
        "title": "With His Mercifulness || English Spiritual Hymn"
      },
      {
        "videoId": "iLBd2-nBFY8",
        "title": "The One that Descends"
      },
      {
        "videoId": "fORJ7m3vt6s",
        "title": "The Light Has Come Into The World || John 3:5-25"
      }
    ]
  },
  {
    "id": "road-to-damascus",
    "album": "Road to Damascus",
    "tracks": [
      {
        "videoId": "wWPilRpMq3E",
        "title": "Violence to Live"
      },
      {
        "videoId": "h1wrWQS7A8c",
        "title": "The Golden Censor - Sermon"
      },
      {
        "videoId": "Joc-9RVYrn8",
        "title": "Us vs. The World"
      },
      {
        "videoId": "tt8BUVR4Suo",
        "title": "The Plight of a Righteous Man"
      },
      {
        "videoId": "oM4DPBBF8aw",
        "title": "A Bridge to a Lost Connection || RTD Sermon"
      },
      {
        "videoId": "Myli_LN69EE",
        "title": "Be Alive Now || RTD Sermon"
      },
      {
        "videoId": "aWu63PpA_uQ",
        "title": "Embracing the Unexpected Plan || RTD Sermon"
      },
      {
        "videoId": "V4CTce2g3dI",
        "title": "The Truth, And Our Fear Of Living It || RTD Sermon"
      },
      {
        "videoId": "q_NihoP62k8",
        "title": "Create in Me a Loving Heart || RTD Sermon"
      },
      {
        "videoId": "DlCAlOYgXp0",
        "title": "REAL ID: Identity in Christ || RTD Sermon"
      },
      {
        "videoId": "tEMpNxxo2Ng",
        "title": "When The Story Becomes A Revelation || RTD Sermon"
      },
      {
        "videoId": "YNticlhkmGg",
        "title": "Am I in a Spiritual Winter? || RTD Sermon"
      },
      {
        "videoId": "TrlFsI3kAOQ",
        "title": "Faith Tested Through Fire || RTD Sermon"
      },
      {
        "videoId": "1DjSDhJAQsY",
        "title": "Keep Your Guard Up: Don't Let Your Mind Wander"
      },
      {
        "videoId": "eRHjVbUZD1Q",
        "title": "For He has won, the Winner of Winners || RTD Sermon"
      },
      {
        "videoId": "GFlGulv917s",
        "title": "Unshakeable Confidence || RTD Sermon"
      },
      {
        "videoId": "_6tK7R919jA",
        "title": "Beloved & Needed || RTD Sermon"
      }
    ]
  }
];
