/** Generated by scripts/build-zehohite-birhan-catalog.mjs — do not edit by hand. */
export const ZEHOHITE_BIRHAN_CHANNEL = "ዘኆኅተ ብርሃን ሚዲያ" as const;

export const ZEHOHITE_BIRHAN_CHANNEL_HANDLE = "@zehohitebirhan_official" as const;

export const ZEHOHITE_BIRHAN_CHANNEL_ID = "UCWOJoa6AObS9tW4WUCdZbrg" as const;

export const ZEHOHITE_BIRHAN_ENGLISH_ALBUM = "English Hymns" as const;

export const ZEHOHITE_BIRHAN_AMHARIC_ALBUM = "Amharic Hymns" as const;

export type ZehohiteBirhanTrack = { videoId: string; title: string };

export type ZehohiteBirhanPlaylist = {
  id: string;
  album: string;
  language: 'english' | 'amharic';
  tracks: ZehohiteBirhanTrack[];
};

export const ZEHOHITE_BIRHAN_PLAYLISTS: ZehohiteBirhanPlaylist[] = [
  {
    "id": "english",
    "album": "English Hymns",
    "language": "english",
    "tracks": [
      {
        "videoId": "3V5zhgW2bes",
        "title": "#new 🛑 ልጅነቴ ልጅነቴ 🛑 || ድንቅ የልጆች መዝሙር አልበም || Children's Song || Yelijoch Mezmur"
      },
      {
        "videoId": "6YEPHypqfcM",
        "title": "#New🛑የእመቤታችን የኅዳር ጽዮን መዝሙራት🛑 ||Hymn of Praise to Saint Mary & the Ark of Zion || Orthodox Mezmur"
      },
      {
        "videoId": "PpjUiON9deY",
        "title": "🌹 HYMNS OF THE SEASON OF FLOWERS || የወርኃ ጽጌ መዝሙራት 🌹 || ORTHODOX ENGLISH MEZMUR ||"
      },
      {
        "videoId": "0_tNvw4oVwI",
        "title": "🌹 የወርኃ ጽጌ መዝሙራት 🌹 || Hymns of the Season of Roses"
      },
      {
        "videoId": "sS_Uolm6VBA",
        "title": "🛑 Wonderful Are Your Deeds 🛑 || ድንቅን የምትሠራ || St. Michael English Hymn"
      },
      {
        "videoId": "6W_CmOANOlA",
        "title": "🛑 የኅዳር ቅዱስ ሚካኤል በዓል መዝሙራት🛑 || Hymns of the feast of Saint Michael || Non-stop Orthodox Mezmur."
      },
      {
        "videoId": "xGKMCgPhwjQ",
        "title": "🛑ANNUNCIATION AND NATIVITY HYMNS🛑 || የብሥራት እና የልደት መዝሙራት || Ethiopian Christmas"
      },
      {
        "videoId": "6OkXROXg-Ro",
        "title": "🛑The Road To Bethlehem 🛑| Nativity Story From Ethiopia | Hohite Engish"
      },
      {
        "videoId": "uD4n4ih7mac",
        "title": "A GREAT MELODY || THE ASCENSION OF OUR LORD"
      },
      {
        "videoId": "SI07q6u9a10",
        "title": "Ethiopian Epiphany"
      },
      {
        "videoId": "ohhn3OKkUd8",
        "title": "Hymns of Timket (Epiphany) & Cana of Galilee || የጥምቀት እና ቃና ዘገሊላ መዝሙራት ስብስብ"
      },
      {
        "videoId": "EE5pAk3rFwc",
        "title": "The Celebration of Epiphany in Ethiopia"
      },
      {
        "videoId": "Pv93G0Koq2o",
        "title": "THE FEAST OF ETHIOPIAN EPIPHANY"
      },
      {
        "videoId": "DMHZqD4ipwE",
        "title": "THE SEVEN CURTAINS"
      },
      {
        "videoId": "LauCExFpmbE",
        "title": "THE SEVEN CURTAINS || ሰባቱ መንጦላዕት"
      },
      {
        "videoId": "tKbTeGqwWNA",
        "title": "Where are you celebrating the feast of Epiphany?"
      },
      {
        "videoId": "G06bhZJAvqI",
        "title": "የልደታ መዝሙሮች ! #orthdoxmezmur #newvideo"
      },
      {
        "videoId": "IqTogbWfIQA",
        "title": "የስቅለት መዝሙሮች ! #orthdoxmezmur #newvideo"
      }
    ]
  },
  {
    "id": "amharic",
    "album": "Amharic Hymns",
    "language": "amharic",
    "tracks": [
      {
        "videoId": "-kkz_oSyqD0",
        "title": "#new 🛑 የጌታችን ዕርገት መዝሙራት || ዐቢይ ዜማ || ሞኦ ለሞት"
      },
      {
        "videoId": "UW3V3wEiiTc",
        "title": "🛑 \"የማርያም መንገድ\" መዝሙር ምርቃት 🛑"
      },
      {
        "videoId": "URpZY6D5Nt0",
        "title": "🛑 ለዛቲ ድንግል | የአስተርእዮ ማርያም ወረብ"
      },
      {
        "videoId": "RwEZldF9HYQ",
        "title": "🛑 ለፍትሐዊው አምላክ ፍትሕ አጓደሉ ! 🛑 ዲያቆን ዘላለም ታዬ"
      },
      {
        "videoId": "COjpln745Xg",
        "title": "🛑 ላመስግንህ የኔ ጌታ | ኆኅተ ዜማ"
      },
      {
        "videoId": "h8qLPbvXf5I",
        "title": "🛑 ሕማማትን በኢትዮጵያውያን ባሕል 🛑 ዲያቆን ሕሊና በለጠ"
      },
      {
        "videoId": "f3L0mu-OXak",
        "title": "🛑 ቅዱሳት እማት 🛑 | | ዘኆኅተ ብርሃን አልበም ቁጥር 1 | ኆኅተ ዜማ"
      },
      {
        "videoId": "bts1Tp49Uww",
        "title": "🛑 በቤተመቅደስህ ያሳደግኸኝ || ዘማሪት ሳራ መንግሥቱ"
      },
      {
        "videoId": "WkAHz0b4Okg",
        "title": "🛑 ተፈጸመ ማኅሌተ ጽጌ || አክሊለ ጽጌ || እንዘ ተሐቅፊዮ || አዘክሪ ድንግል || ገሊላ እትዊ || አዲስ የጽጌ መዝሙራት ስብስብ"
      },
      {
        "videoId": "Lh7Tl1ca4Kg",
        "title": "🛑 ቸርነትህ ነው || ኑ ለምስጋና || ዘማሪ ቀሲስ ምንዳዬ ብርሃኑ"
      },
      {
        "videoId": "N_j869wW9sU",
        "title": "🛑 ነገረ ማርያም | ዲ/ን ሄኖክ ኃይሌ |"
      },
      {
        "videoId": "xFOm6nwpa9k",
        "title": "🛑 አመሰግናለሁ ጸጋሽን 🛑 | እሴብሕ ጸጋኪ በአማርኛ | ዲ/ን በአምላክ ይልማ |"
      },
      {
        "videoId": "g-c9A566bIY",
        "title": "🛑 አበባ 🛑 ልዩ የሕፃናት መዝሙር || የማርያም መንገድ ||"
      },
      {
        "videoId": "GpN1Ad1N6rY",
        "title": "🛑 ከሚጠቡ አንደበት ምስጋናን አዘጋጀህ! || የማርያም መንገድ መዝሙር ምርቃት ||"
      },
      {
        "videoId": "2lgUVEKVrX8",
        "title": "🛑 ከቤተ-ክርስቲያን የተለዩ ሰዎችን መዝሙር መስማት ይቻላል? 🛑"
      },
      {
        "videoId": "G0VJl6otN_Y",
        "title": "🛑 ወላዲተ አምላክ | ኆኅተ ዜማ"
      },
      {
        "videoId": "mqjkeNUE7no",
        "title": "🛑 የመስቀል መዝሙራት 🛑 || Ethiopian Orthodox Hymns on the Feast Finding of the True Cross ||"
      },
      {
        "videoId": "7nQIVX00hlQ",
        "title": "🛑 የሰሙነ ሕማማት ዕለታት 🛑 በዲያቆን ዘላለም ታዬ"
      },
      {
        "videoId": "oMjh9xG9nBU",
        "title": "🛑 የሰኔ 21 - ሕንጸተ ቤተክርስቲያን ወረብ 🛑 እግዚአብሔር ውእቱ || በዘኆኅተ ብርሃን ዘማርያን"
      },
      {
        "videoId": "J0blCfWdBVU",
        "title": "🛑 የሰንበት ቤት 🛑 | ዘኆኅተ ብርሃን መዝሙር አልበም ቁጥር 1 | ኆኅተ ዜማ"
      },
      {
        "videoId": "dBufuRvBUxk",
        "title": "🛑 የትንሣኤ መዝሙራት ስብስብ 🛑|| በኆኅተ ብርሃን ሰንበት ትምህርት ቤት መዘምራን"
      },
      {
        "videoId": "4Ut7KkrhpZA",
        "title": "🛑 የአስተርእዮ ማርያም መዝሙራት ስብስብ 🛑"
      },
      {
        "videoId": "tol7PXZ7xrM",
        "title": "🛑 ድንቅን የምትሠራ 🛑 | የቅዱስ ሚካኤል መዝሙር | ዘኆኅተ ብርሃን አልበም ቁጥር 1 | ኆኅተ ዜማ"
      },
      {
        "videoId": "2-eW-6uWEZM",
        "title": "🛑በትሕትና 🛑| ዘኆኅተ ብርሃን መዝሙር አልበም ቁጥር 1 | ኆኅተ ዜማ"
      },
      {
        "videoId": "5WMFVOxZSbs",
        "title": "🛑እስክታገኘው ድረስ አጥብቃ የማትፈልግ ሴት ማን ናት? | ዲ/ን ብርሃኑ አድማስ"
      },
      {
        "videoId": "HaoB1llNtmM",
        "title": "🛑እግዚአብሔርን አመስግኑ🛑| ዘኆኅተ ብርሃን መዝሙር አልበም ቁጥር 1 | ኆኅተ ዜማ"
      },
      {
        "videoId": "1ib8PrNS7A4",
        "title": "🛑ዕቀበነ | ኆኅተ ዜማ"
      },
      {
        "videoId": "2adXY311-JQ",
        "title": "🛑የጥምቀት መዝሙራት ስብስብ🛑 | ኆኅተ ዜማ"
      },
      {
        "videoId": "CRIc4npgsuQ",
        "title": "🛑ድንቅ የልጆች መዝሙር 🛑 || \"የማርያም መንገድ\" መዝሙር አልበም ክፍል 2 ||"
      },
      {
        "videoId": "usNQNpEagmI",
        "title": "🛑ጥዒሞ አንከረ 🛑 | ወረብ በኆኅተ ብርሃን ሰ/ት/ቤት መዘምራን"
      },
      {
        "videoId": "pV4QqzYmoeQ",
        "title": "ልጅነቴ - የማርያም መንገድ የተሰኘው ልዩ የሕፃናት መዝሙር አልበም"
      },
      {
        "videoId": "UJq-zeb4_ps",
        "title": "ልጅነቴ - የማርያም መንገድ የተሰኘው ልዩ የሕፃናት መዝሙር አልበም"
      },
      {
        "videoId": "esZAddl9PEw",
        "title": "ልጅነቴ - የማርያም መንገድ የተሰኘው ልዩ የሕፃናት መዝሙር አልበም"
      },
      {
        "videoId": "kKVGvh7BN78",
        "title": "ልጅነቴ - የማርያም መንገድ የተሰኘው ልዩ የሕፃናት መዝሙር አልበም"
      },
      {
        "videoId": "-EB6hg3q6Js",
        "title": "ምዕረ በዘባንኪ - የጽጌ መዝሙራት ስብስብ በኆኅተ ብርሃን ዘማርያን"
      },
      {
        "videoId": "5wuaxO8ydGo",
        "title": "ተለቀቀ! 🛑 የማርያም መንገድ 🛑 || ልዩ የሕፃናት መዝሙር ||"
      },
      {
        "videoId": "eBz6of_Blvw",
        "title": "ትንሣኤከ | ኆኅተ ዜማ |"
      },
      {
        "videoId": "Lace3ZCB2iw",
        "title": "አፈ ንህብ - የጽጌ መዝሙራት ስብስብ በኆኅተ ብርሃን ዘማርያን"
      },
      {
        "videoId": "GmEuHXA6NSw",
        "title": "አፈ ንህብ - የጽጌ መዝሙራት ስብስብ በኆኅተ ብርሃን ዘማርያን"
      },
      {
        "videoId": "EWaZC-ShTxE",
        "title": "እልል እልል በሉ | ኆኅተ ዜማ |"
      },
      {
        "videoId": "jZM8aD3MnZU",
        "title": "ወስኑሰ ለያዕቆብ -- ሙሉውን መዝሙር ያድምጡ"
      },
      {
        "videoId": "64WMp2LGt0g",
        "title": "ዘኆኅተ ብርሃን | ኆኅተ ዜማ"
      },
      {
        "videoId": "EGZD61RGOwc",
        "title": "ዘኆኅተ ብርሃን ሙሉ የመዝሙር አልበም | ቁጥር 1"
      },
      {
        "videoId": "vNnK6kdfLlA",
        "title": "የሆሣዕና መዝሙራት ስብስብ በኆኅተ ብርሃን ዘማርያን"
      },
      {
        "videoId": "jHdTZU3LAs4",
        "title": "የማርያም መንገድ የተሰኘው ልዩ የሕፃናት መዝሙር አልበም"
      },
      {
        "videoId": "9ULmit2e8ME",
        "title": "የቅድስት ሥላሴ መዝሙራት ስብስብ | ኆኅተ ዜማ"
      },
      {
        "videoId": "2VGuO8Os4TQ",
        "title": "የትንሣኤ መዝሙራት ስብስብ"
      },
      {
        "videoId": "3hW2Vp8aB1Q",
        "title": "የትንሣኤ መዝሙራት ስብስብ"
      },
      {
        "videoId": "CSBVzhnMUPs",
        "title": "የትንሣኤ መዝሙራት ስብስብ"
      },
      {
        "videoId": "-OX_SeDd354",
        "title": "የኆኅተብርሃን ቤተ ክርስቲያን የምሥረታ ታሪክ | በዲ/ን ሕሊና በለጠ"
      },
      {
        "videoId": "1cRSiZn26DQ",
        "title": "የደብረ ምጥማቅ መዝሙራት ስብስብ || የግንቦት 21 መዝሙራት"
      },
      {
        "videoId": "0gzzRFTy3lU",
        "title": "የጌታችን ልደት መዝሙራት | ኆኅተ ዜማ"
      },
      {
        "videoId": "pfR3doif26s",
        "title": "ድንቅ የልጆች መዝሙር - ሙሉውን ይመልከቱ"
      },
      {
        "videoId": "VbULn3QQOXA",
        "title": "ድንቅ የልጆች መዝሙር - ሙሉውን ይመልከቱ"
      },
      {
        "videoId": "tUGI6p8iNVQ",
        "title": "ድንቅ የልጆች መዝሙር - ሙሉውን ይመልከቱ"
      }
    ]
  }
];
