/**
 * Curated Ahadu Studios albums (Spotify / Apple Music tracklists).
 * sync-mezmur.mjs resolves titles on YouTube (+ Topic overrides).
 */
export const AHADU_CHANNEL_ID = 'UCtsUZLiOwTycJ4xO8tWenVQ';

/** Later entries win when the same YouTube video appears on multiple albums. */
export const AHADU_ALBUMS = [
  {
    album: 'Translated Hymns (Volume I)',
    language: 'english',
    type: 'praise',
    songs: [
      'Let Us Give Praise',
      'Before the Most High',
      'Your Love Allured Me',
      'Our Heavenly Father',
      'I Called Unto My Dear Lord',
      'I Found Tranquility',
      'In That Very Hour',
      'With His Mercifulness',
      'Alpha and Omega',
      'Hosanna in Ariyam',
      'The God of Abraham',
      'The Lord Has Risen',
      'Soaring With His Grand Wings',
      'Help My Unbelief My Lord',
      'Praise the Trinity',
    ],
  },
  {
    album: 'Translated Hymns (Volume II)',
    language: 'english',
    type: 'praise',
    songs: [
      'Lord it is Your Grace',
      'You Triumph the Works of Evil',
      'I Will Forever Sing for My Lady',
      'O Virgin Mary',
      'Melody of Yared',
      'I Know the One Who Has Saved Me',
      'O the Archangel',
      'Mother of God Virgin Mary',
      'His Miracles and Deeds',
      'God Will Lead Me',
      'Your Name Gives Me the Strength',
      'My Benevolent Lord',
      'Praises of Mary',
      'There is No One Like You',
      'To Mother Mary',
    ],
  },
  {
    album: 'Translated Hymns (Volume III)',
    language: 'english',
    type: 'praise',
    songs: [
      'I Will Praise You With Melodies',
      'The Cross is the Light',
      'Undeserving I Am',
      "To Receive the Lord's Love",
      'The Son Has Been Born',
      'My Strength and Power',
      'Without You My Lord',
      'The Gracious and Adored Interceder',
      'The Good Samaritan',
      'Holy Virgin Mary',
      'Emmanuel',
      'Truly With Glory the Lord is Risen',
      'Filled With Praises',
      'Come All Let Us Rejoice',
      'St. Michael He is Set Apart',
    ],
  },
  {
    album: 'Translated Hymns (Volume IV)',
    language: 'english',
    type: 'praise',
    songs: [
      'He Saved Me My Lord',
      "By the Lord's Grand Design",
      'The Word Spoke to Her',
      'I Call Out Your Name',
      'Bless This New Year',
      'The Cross Has Shined',
      'My Home is Filled',
      'There is Power in Your Words',
      "For My Eyes Have Witnessed the Lord's Salvation",
      'Our Lord and King of Peace',
      'Epiphany',
      'He is Praised',
      'Covenant of Mercy',
      "We Can't Forget",
      'The Almighty God is Gracious',
    ],
  },
  {
    album: 'Translated Hymns (Volume V)',
    language: 'english',
    type: 'praise',
    songs: [
      "My Lord's Appearance",
      'Go Forth Testify',
      "He's Done Wonders for Me",
      'She is Born For Us All',
      'We Offer You Glory and Praise',
      "Within the Sinner's Tent",
      'Tewahedo',
      'From a Womb Poetry Was Heard',
      'In Your Temple O Lord',
      'From the Scorching Flames',
      "The Virgin's Resurrection",
      'Almighty is Our God',
      'TekleHaymanot the Monastic',
      'With His Love the Lord Rescued Me',
      'The Cross Has Been Found',
    ],
  },
  {
    album: 'Cana',
    language: 'english',
    type: 'praise',
    songs: [
      'Cana of Galilee',
      'Bless Our Matrimony',
      'Come All and Then Marvel',
      'Our Bride and Groom',
      'Illuminating Are the Works of Emmanuel',
      'Be Filled With Glee',
      "In Cana's Water",
      'Two Hearts Have Become One',
      'For All That He Has Done',
    ],
  },
  {
    album: 'Praise Night || 2024 OTYD Winter Conference',
    language: 'english',
    type: 'praise',
    songs: [
      'Create in Me',
      'Praise the Trinity',
      'Without You My Lord',
      'The Spirit',
      'Your Love Allured Me',
      'City of Lord',
      'You Triumph the Works of Evil',
    ],
  },
  {
    album: 'My Guide',
    language: 'english',
    type: 'praise',
    songs: [
      'My Guide',
      'Create in Me',
      'City of Lord',
      'Lost',
      'Descend in Power',
      'Resemble Them',
      'Beseech for Us',
      'TekleHaymanot',
      'The Archangels',
    ],
  },
  {
    album: 'Glory to God (Volume I)',
    language: 'english',
    type: 'praise',
    songs: ['Glory to God (Volume I)'],
  },
  {
    album: 'Glory to God (Volume II)',
    language: 'english',
    type: 'praise',
    songs: ['Glory to God (Volume II)'],
  },
  {
    album: 'Glory to God (Volume III)',
    language: 'english',
    type: 'praise',
    songs: ['Glory to God (Volume III)'],
  },
  {
    album: 'Glory to God (Volume IV)',
    language: 'english',
    type: 'praise',
    songs: ['Glory to God (Volume IV)'],
  },
  {
    album: 'God of Creation',
    language: 'english',
    type: 'praise',
    songs: ['God of Creation'],
  },
];

/** Full-album YouTube uploads for Glory to God (canonical track title → video id). */
export const AHADU_GLORY_FULL_ALBUM_VIDEOS = {
  'Glory to God (Volume I)': 'SAAUjmTHdi4',
  'Glory to God (Volume II)': 'XqZJyo-dwlc',
  'Glory to God (Volume III)': '_gYVwkxIIKA',
  'Glory to God (Volume IV)': 'eKfABzpEyxY',
};

export const AHADU_TRACK_OVERRIDES = {
  ...AHADU_GLORY_FULL_ALBUM_VIDEOS,
  'God of Creation': 'WCnWgLmLUxI',
  'My Guide': 'BsQNjUkYs6w',
  'Create in Me': '0JL_D4aPdLU',
  'City of Lord': 'WABFP4wYPd0',
  Lost: '3XPocMwkI60',
  'Descend in Power': 'FfpZ00svoUY',
  'Resemble Them': 'a5D-KedpvyA',
  'Beseech for Us': 'qj91aBGED8g',
  'The Archangels': 'HMD4esyzlJY',
  'TekleHaymanot': 'XSPiiv0x2WU',
};

export const AHADU_TITLE_ALIASES = {
  'I Will Praise You With Melodies': ['I Will Praise You'],
  'I Will Forever Sing for My Lady': ['I Will Forever Sing for my Lady'],
  'O Virgin Mary': ["O' Virgin Mary"],
  'Hosanna in Ariyam': ['Hosanna In Ariyam'],
  "We Can't Forget": ['We Can\'t Forget'],
  "For My Eyes Have Witnessed the Lord's Salvation": ['For My Eyes'],
  'Truly With Glory the Lord is Risen': ['Truly With Glory'],
  'St. Michael He is Set Apart': ['St. mIchael he is set apart', 'St. Michael He Is Set Apart'],
  'City of Lord': ['City of the Lord'],
  'My Home is Filled': ['My Home is filled'],
  'TekleHaymanot': ['TekleHaymanot the Monastic'],
  'TekleHaymanot the Monastic': ['TekleHaymanot The Monastic'],
  'She is Born For Us All': ['She is Born for us all'],
  'We Offer You Glory and Praise': ['We Offer You Glory And Praise'],
  "Within the Sinner's Tent": ["Within the Sinner's tent"],
  "The Virgin's Resurrection": ['The Virgin\'s Resurrection'],
  "He's Done Wonders for Me": ['He\'s Done Wonders for Me'],
  'The Archangels': ['O the Archangel', 'The Archangel'],
  'Glory to God (Volume I)': ['Glory to God || Instrumental Album Vol. 1'],
  'Glory to God (Volume II)': ['Glory to God || Instrumental Album Vol. 2'],
  'Glory to God (Volume III)': ['Glory to God || Instrumental Album Vol. 3'],
  'Glory to God (Volume IV)': ['Glory to God || Instrumental Album Vol. 4'],
  'God of Creation': ['God of Creation || Praise Night', 'God of Creation || Original Song By Ahadu Studios'],
};
